### ISSUE TITLE
Error starting sync, exit code 0

### ISSUE THREAD

**Issue by BKStephens** [EugenMayer/docker-sync#119]
This project looks awesome! I am trying to get it running, but am running into some issues.

When I clone this repo, and try to run just the unison-sync example (removed other syncs from docker-sync.yml), I get:

```
example master % docker-sync start
          ok  Starting unison
          ok  unison-sync container not running
          ok  creating unison-sync container
     command  docker run -p '127.0.0.1::5000'                               -v unison-sync:/data                               -e UNISON_DIR=/data                               -e TZ=${TZ-`readlink /etc/localtime | sed -e 's,/usr/share/zoneinfo/,,'`}                               -e UNISON_OWNER="www-data" -e UNISON_OWNER_UID="33"                                                              --name unison-sync                               -d mickaelperrin/docker-unison-unox
          ok  starting initial sync of unison-sync
     command  docker inspect --format=" {{ .NetworkSettings.Ports }} " unison-sync | /usr/bin/sed  -E "s/.*map\[5000[^ ]+ ([0-9]*)[^0-9].*/\1/"
     command  unison /Users/benstephens/repos/docker-sync/example/data4 -auto -batch socket://localhost:32775
       error  Error starting sync, exit code 0
     message  Contacting server...
Fatal error: Failed to connect to the server on host localhost:32775
     success  Unison server started
     command  docker inspect --format=" {{ .NetworkSettings.Ports }} " unison-sync | /usr/bin/sed  -E "s/.*map\[5000[^ ]+ ([0-9]*)[^0-9].*/\1/"
     command  unison /Users/benstephens/repos/docker-sync/example/data4 -auto -batch socket://localhost:32775
       error  Error starting sync, exit code 0
     message  Contacting server...
Fatal error: Failed to connect to the server on host localhost:32775
     command  docker inspect --format=" {{ .NetworkSettings.Ports }} " unison-sync | /usr/bin/sed  -E "s/.*map\[5000[^ ]+ ([0-9]*)[^0-9].*/\1/"
     command  unison /Users/benstephens/repos/docker-sync/example/data4 -auto -batch socket://localhost:32775 -repeat watch
Contacting server...
Fatal error: Failed to connect to the server on host localhost:32775
```

Here is some information about my system:
OS X El Capitan Version 10.11.16
Docker version 1.12.0, build 8eab29e
docker-compose version 1.8.0, build f3628c7
Docker for Mac 1.12.0-a
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin15]
unison: stable 2.48.4 (bottled)

**Comment by mickaelperrin** [comment]
Thx for reporting.

Could you paste your config and the result of `docker ps -a | grep unison' ?

**Comment by EugenMayer** [comment]
@BKStephens any reason you are using the development version instead of the current released one? if you just start with the project, i would really recommend you using the current release

`gem install docker-sync`

instead of the current development master

if you want to test-drive the project, use the boilerplate at https://github.com/EugenMayer/docker-sync-boilerplate rather then the examples in the master, they are less maintained right now. Thanks!

@mickaelperrin i would rather not wonder if the examples are right now broken.

**Comment by BKStephens** [comment]
For config, everything is the same as https://github.com/EugenMayer/docker-sync/tree/master/example, except for docker-sync.yml. For docker-sync.yml, I removed syncs besides unison:
```
# for a simpler example, see the boilerplate at https://github.com/EugenMayer/docker-sync-boilerplate
options:
  # optional, default: docker-compose.yml if you like, you can set a custom location (path) of your compose file
  compose-file-path: 'docker-compose.yml'
  # optional, default: docker-compose-dev.yml if you like, you can set a custom location (path) of your compose file. Do not set it, if you do not want to use it at all
  # if its there, it gets used, if you name it explicitly, it HAS to exist
  compose-dev-file-path: 'docker-compose-dev.yml'
  # optional, activate this if you need to debug something, default is false
  verbose: true
  # ADVANVED: default:eugenmayer/rsync -  the image to use for the rsync container. Do not change this until you exactly know, what you are doing
  # you cannot just use "some unison" container, you entrypoint needs features, check the Dockerfiles
  rsync_image: 'eugenmayer/rsync'
  # ADVANVED: default:eugenmayer/unison -  the image to use for the unison container. Do not change this until you exactly know, what you are doing
  # you cannot just use "some unison" container, you entrypoint needs features, check the Dockerfiles
  unison_image: 'eugenmayer/unison'
  # can be docker-sync, thor or auto and defines, how the sync will be invoked on the cli. Mostly depending if your are using docker-sync solo, scaffolded or in development ( thor )
  cli_mode: 'auto'
syncs:
  unison-sync:
      src: './data4/'
      dest: '/data'
      image: 'mickaelperrin/docker-unison-unox'
      sync_host_ip: 'localhost'
      sync_strategy: 'unison'
      sync_user: 'www-data'
      sync_userid: '33'
      # If you need to sync a lot of files, you can reach out the system limit
      # of inotify watches. You can set the limit by using this parameter. This will
      # prompt you for your sudo password to modify the system configuration.
      #max_inotify_watches: 100000
```

Is that what you are looking for?

After opening this issue, I stopped Docker for Mac and started docker-machine again to go back to my old setup for the time being. After seeing your response, I stopped docker-machine and started Docker for Mac, and am seeing different results. This is surprising as I saw the output I posted above last night, then again today after restarting my computer.

Anyway, it looks like it is making it further:
```
example master % docker-sync start
          ok  Starting unison
          ok  unison-sync container not running
          ok  creating unison-sync container
     command  docker run -p '127.0.0.1::5000'                               -v unison-sync:/data                               -e UNISON_DIR=/data                               -e TZ=${TZ-`readlink /etc/localtime | sed -e 's,/usr/share/zoneinfo/,,'`}                               -e UNISON_OWNER="www-data" -e UNISON_OWNER_UID="33"                                                              --name unison-sync                               -d mickaelperrin/docker-unison-unox
          ok  starting initial sync of unison-sync
     command  docker inspect --format=" {{ .NetworkSettings.Ports }} " unison-sync | /usr/bin/sed  -E "s/.*map\[5000[^ ]+ ([0-9]*)[^0-9].*/\1/"
     command  unison /Users/benstephens/repos/docker-sync/example/data4 -auto -batch socket://localhost:32770
          ok  Synced /Users/benstephens/repos/docker-sync/example/data4
      output  Warning: No archive files were found for these roots, whose canonical names are:
        /Users/benstephens/repos/docker-sync/example/data4
        //a2d0152e9b0b//data
This can happen either
because this is the first time you have synchronized these roots,
or because you have upgraded Unison to a new version with a different
archive format.

Update detection may take a while on this run if the replicas are
large.

Unison will assume that the 'last synchronized state' of both replicas
was completely empty.  This means that any files that are different
will be reported as conflicts, and any files that exist only on one
replica will be judged as new and propagated to the other replica.
If the two replicas are identical, then no changes will be reported.

If you see this message repeatedly, it may be because one of your machines
is getting its address from DHCP, which is causing its host name to change
between synchronizations.  See the documentation for the UNISONLOCALHOSTNAME
environment variable for advice on how to correct this.

Donations to the Unison project are gratefully accepted:
http://www.cis.upenn.edu/~bcpierce/unison

     success  Unison server started
     command  docker inspect --format=" {{ .NetworkSettings.Ports }} " unison-sync | /usr/bin/sed  -E "s/.*map\[5000[^ ]+ ([0-9]*)[^0-9].*/\1/"
     command  unison /Users/benstephens/repos/docker-sync/example/data4 -auto -batch socket://localhost:32770
          ok  Synced /Users/benstephens/repos/docker-sync/example/data4
      output
     command  docker inspect --format=" {{ .NetworkSettings.Ports }} " unison-sync | /usr/bin/sed  -E "s/.*map\[5000[^ ]+ ([0-9]*)[^0-9].*/\1/"
     command  unison /Users/benstephens/repos/docker-sync/example/data4 -auto -batch socket://localhost:32770 -repeat watch
Contacting server...
Connected [//Bens-MBP.home//Users/benstephens/repos/docker-sync/example/data4 -> //a2d0152e9b0b//data]
Looking for changes
Traceback (most recent call last):
  File "/usr/local/bin/unison-fsmonitor", line 24, in <module>
    import fsevents
ImportError: No module named fsevents
Fatal error: File monitoring helper program not running
```

Here is the result of `docker ps -a | grep unison`:
```
example master % docker ps -a | grep unison
a2d0152e9b0b        mickaelperrin/docker-unison-unox   "/entrypoint.sh super"    About a minute ago   Up About a minute                 127.0.0.1:32770->5000/tcp   unison-sync
39b6d00f855c        alpine                             "watch -n1 'cat /app/"    2 minutes ago        Exited (137) About a minute ago                               unison
7446229b3601        alpine                             "watch -n1 'cat /app/"    2 minutes ago        Exited (137) About a minute ago                               unisononsidedapp
edec6fbeaa29        alpine                             "cat /app/cat/somefil"    14 minutes ago       Exited (0) 14 minutes ago                                     example_unison_run_3
4674199fc51c        alpine                             "ls"                      14 minutes ago       Exited (0) 14 minutes ago                                     example_unison_run_2
1cbf24e8a309        alpine                             "bash"                    14 minutes ago       Created                                                       example_unison_run_1
0ce116b83fff        eugenmayer/unison:unox             "/entrypoint.sh super"    15 hours ago         Exited (0) 15 hours ago                                       engagement-data-sync
```
