### ISSUE TITLE
An error occurred and the program will be terminated. 

### ISSUE THREAD

**Issue by karneaud** [EugenMayer/docker-sync#131]
I am new to docker and have the following in the root of my project....

docker-sync.yml
```
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  ngcracealong-rsync-sync: #tip: add -sync and you keep consistent names als a convention
    src: './'
    dest: '/data'
    sync_host_ip: 'localhost'
    sync_host_port: 28736
    compose-dev-file-path: 'docker-compose-dev.yml'
    sync_excludes: ['.gitignore', '.git/','.vagrant/','build/','target/','*.yml','*.xml','*.md','Vagrantfile','.DS_Store']
    watch_excludes: ['.git/', 'node_modules/', 'target/', '.gitignore','Vagrantfile','*.yml','.*.xml','build/','.vagrant/','.DS_Store']
    sync_strategy: 'rsync'
```

docker-compose.yml
```
version: "2"
services:
  ngcracealong-rsync:
    image: alpine
    container_name: 'docker-clojurescript'
    # command: ['watch', '-n3', 'cat /data']
```

docker-compose-dev.yml
```
# this is our development docker-compose building on top of the prodicker docker-compose, just mounting
# the sync image - not redefining anything else

version: "2"
services:
  ngcracealong-rsync:
    volumes:
      - ngcracealong-rsync-sync:/data:rw # will be mounted on /var/www

# that the important thing
volumes:
  ngcracealong-rsync-sync:
    external: true
```

when running the `docker-sync-stack start` command i get the following error

> Sync ngcracealong-rsync-sync  An error occurred and the program will be terminated.
Sync ngcracealong-rsync-sync  Error: An error occurred during the compilation of *.yml

Why is that?

How does this work as I am not familiar with docker-compose.....does it attach it self to the already running docker container? Does it start a container for you?
