### ISSUE TITLE
EXCEPTION: #<NoMethodError: undefined method `watch_fork' for #<Docker_Sync::WatchStrategy::Fswatch:0x007faa641ba600>

### ISSUE THREAD

**Issue by karneaud** [EugenMayer/docker-sync#135]
Been having problems using your framework ... In trying to do a `docker-sync start` I encounter the error messages

> Sync ngcracealong-rsync-sync  An error occurred and the program will be terminated.
Sync ngcracealong-rsync-sync  Error: An error occurred during the compilation of *.yml

> EXCEPTION: #<NoMethodError: undefined method `watch_fork' for #<Docker_Sync::WatchStrategy::Fswatch:0x007faa641ba600>
Did you mean?  watch_thread>
MESSAGE: undefined method `watch_fork' for #<Docker_Sync::WatchStrategy::Fswatch:0x007faa641ba600>
Did you mean?  watch_thread

my docker-sync.yml
```
options:
  compose-dev-file-path: 'docker-compose-dev.yml'
  verbose: true
  rsync_image: 'eugenmayer/rsync'
  cli_mode: 'auto'
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  ngcracealong-rsync-sync: #tip: add -sync and you keep consistent names als a convention
    src: './'
    dest: '/data/'
    watch_in_container: true
    notify_terminal: true
    sync_host_ip: 'localhost'
    sync_host_port: 28736
    sync_excludes: ['.gitignore', '.git/','.vagrant/','build/','target/','*.yml','*.xml','*.md','Vagrantfile','.DS_Store']
    watch_excludes: ['.git/', 'node_modules/', 'target/', '.gitignore','Vagrantfile','*.yml','.*.xml','build/','.vagrant/','.DS_Store']
    sync_strategy: 'rsync'
    watch_strategy: 'fswatch' 
```
my docker-compose.yml
```
version: "2"
services:
  ngcracealong-rsync:
    image: rand/docker-clojurescript
    ports:
      - "3000:3000"
      - "9000:9000"
    expose:
      - "3000"
      - "9000"
    environment:
      - TERM=xterm
      - COMPOSE_HTTP_TIMEOUT=200
    working_dir: "/data"
    # entrypoint: [lein, "with-profile", "dev", do , "start-dev"]
    container_name: 'docker-clojurescript'
    command: bash -c "lein with-profile dev do start-dev & watch -n3 'cp --parents -Ru /* /data'"

```
my docker-compose-dev.yml
```
# this is our development docker-compose building on top of the prodicker docker-compose, just mounting
# the sync image - not redefining anything else
version: "2"
services:
  ngcracealong-rsync:
    volumes:
      - ngcracealong-rsync-sync:/data:rw # will be mounted on /var/www
# that the important thing
volumes:
  ngcracealong-rsync-sync:
    external: true
```

Not sure what this all means. I have installed the fswatch via brew.

Could you shed some light on this?
