### ISSUE TITLE
Unison : Filesystem watcher error

### ISSUE THREAD

**Issue by FabienD** [EugenMayer/docker-sync#137]
Hi,

I've tried docker-sync on a Symfony project, but after syncing, I've recieved this error :

```
          ok  Starting unison
          ok  Synced /Users/fab/workspaces/sites/nm.dev
     success  Unison server started
          ok  Synced /Users/fab/workspaces/sites/nm.dev
          ok  Found implicit docker-compose-dev.yml and using it from /Users/fab/workspaces/sites/nm.dev/docker-compose-dev.yml
          ok  starting compose
Contacting server...
Connected [//17f9a52808d3//var/www -> //macbook-pro.home//Users/fab/workspaces/sites/nm.dev]
Looking for changes
  Waiting for changes from server
Fatal error: Server: Filesystem watcher error: cannot add a watcher: system limit reached
The watcher can be disabled by setting preference 'watch' to false
```

Here is my docker-sync config : 

```
syncs:
  nm-sync:
    sync_strategy: 'unison'
    notify_terminal: true
    src: '.'
    dest: '/var/www'
    sync_host_ip: 192.168.5.154
    sync_args:
      - "-prefer newer"
      - "-copyonconflict"
      - "-ignore='Path .idea'"
      - "-ignore='Path .git'"
      - "-ignore='BelowPath .git'"
    watch_excludes: ['.*/.git', '.*/node_modules', '.*/sass-cache', '.*/app/logs', '*./app/cache', '*./vendor']
```

I've increased some limits on the Mac, 

```
sudo sysctl -w kern.maxfilesperproc=100000
 sudo sysctl -w kern.maxfiles=100000
 ulimit -n 100000
```

The "fs.inotify.max_user_watches" of the docker container is too lower ? Should I rebuild the docker image to increase "fs.inotify.max_user_watches" ? 
I've seen that "watch_excludes" directive doesn't work #118, it doesn't help to avoid to reach limits.

Thanks,
Fabien
