### ISSUE TITLE
rsync doesn't work

### ISSUE THREAD

**Issue by sandrodz** [EugenMayer/docker-sync#145]
Rsync doesn't work, changes are only copied once on `docker-sync start` after this nothing happens.
docker-sync
```
options:
  verbose: true
syncs:
  rsync-sync:
    src: '/Users/sandro/Code/www'
    dest: '/www'
    sync_host_ip: 'localhost'
    sync_host_port: 10872
    sync_strategy: 'rsync' # is this needed?
```
production yml
```
#
version: '2'
#
services:
  #
  mariadb:
    image: mariadb:latest
    ports:
      - "127.0.0.1:3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xxxx
    volumes:
      - ./MariaDB/mysql:/var/lib/mysql
  #
  php5-fpm:
    build: ./PHP/php5-fpm
    restart: always
    volumes:
      - /Users/sandro/Code/www:/www
  php7-fpm:
    build: ./PHP/php7-fpm
    restart: always
    volumes:
      - /Users/sandro/Code/www:/www
  #
  nginx:
    image: nginx:latest
    ports:
      - '127.0.0.1:80:80'
    restart: always
    volumes:
      - ./Nginx/sites:/etc/nginx/sites
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/nginx-wp-common.conf:/etc/nginx/nginx-wp-common.conf
      - ./Nginx/nginx-php-common.conf:/etc/nginx/nginx-php-common.conf
      - /Users/sandro/Code/www:/www
```
dev override:
```
#
version: '2'
#
services:
  #
  php5-fpm:
    volumes:
      - rsync-sync:/www:rw
  php7-fpm:
    volumes:
      - rsync-sync:/www:rw
  #
  nginx:
    volumes:
      - rsync-sync:/www:rw
#
volumes:
  rsync-sync:
    external: true

```
