### ISSUE TITLE
Show "Error in digesting: ..: Permission denied"

### ISSUE THREAD

**Issue by ymhuang0808** [EugenMayer/docker-sync#148]
Thanks docker-sync for improving the Docker performance. 

I encounter permission problem when the database data is changed. It shows the following message:
```
Synchronization complete at 09:44:54  (0 item transferred, 1 skipped, 0 failed)
  skipped: ibdata1 (Error in digesting /myproject/mariadb/data/ibdata1:
/myproject/mariadb/data/ibdata1: Permission denied)
```
Here is my configuration and docker-sync version.
```yml
options:
  compose-file-path: './myproject/docker/docker-compose.yml'
  compose-dev-file-path: './myproject/docker/docker-compose-dev.yml'
  verbose: true
syncs:
  myproject-mariadb-data-unison-sync:
    src: './myproject/docker/data'
    dest: '/myproject/mariadb/data'
    sync_strategy: 'unison'
```

```
docker-sync (0.1.2)
```

May I configure the `sync_user` or `sync_userid` in `docker-sync.yml`?
