### ISSUE TITLE
Nginx error since update to 0.1.3 release

### ISSUE THREAD

**Issue by AlexandreHagen** [EugenMayer/docker-sync#150]
Hi 

I got this now I'm under release 0.1.3 (/var/log/nginx): 
```sh
2016/10/03 22:06:48 [error] 86#86: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: api-v2-dev.opendecide.dev, request: "GET /_profiler HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api-v2-dev.opendecide.dev"
```
Here my docker-sync.yml
```yml
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  back_new-rsync-sync: #tip: add -sync and you keep consistent names als a convention
    src: '../back_new'
    dest: '/var/www/opendecide_api_v2'
    sync_host_ip: 'localhost'
    sync_host_port: 10872
    notify_terminal: true
    sync_user: root
    sync_userid: 0
    sync_group: root
    sync_groupid: 0
    sync_excludes: ['bin', 'vendor/behatch/contexts/README.rst', 'vendor/zendframework/zend-code/doc/book/index.md', '/web', 'app/cache', 'app/logs']
```
I think it a rights issue between Nginx and Docker-Sync but I do not know how to solve it.

Right in /var/www in container: 
Without Docker-Sync (everything works)
```sh
drwxr-xr-x 19 root root     646 Oct  3 19:30 opendecide_api
```
With Docker-Sync (Nginx error)
```sh
drwxr-xr-x  7  501 dialout 4096 Oct  3 18:57 opendecide_api_v2
```
Thanks

**Comment by AlexandreHagen** [comment]
FYI, I had downgraded from 0.1.3 to 0.1.2 and nothing changes...  I remember what during ```docker-sync start```, Rsync has been updated too. Maybe it’s from it .

**Comment by AlexandreHagen** [comment]
I have also: 
```sh 
$ docker-sync start
          ok  Starting rsync
rsync: failed to set times on ".git" (in volume): Operation not permitted (1)
rsync: mkstemp ".git/.FETCH_HEAD.XXXXXX" (in volume) failed: Permission denied (13)
rsync: failed to set times on ".idea" (in volume): Operation not permitted (1)
rsync: failed to set times on "src/OpenDecide/ApiBundle/EventListener" (in volume): Operation not permitted (1)
rsync: mkstemp ".idea/.workspace.xml.XXXXXX" (in volume) failed: Permission denied (13)
rsync: mkstemp "src/OpenDecide/ApiBundle/EventListener/.DecisionListener.php.XXXXXX" (in volume) failed: Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1249) [sender=3.1.2]
       error  Error starting sync, exit code 23
...
...
```
Maybe, I have the same problem that https://github.com/EugenMayer/docker-sync/issues/151

**Comment by AlexandreHagen** [comment]
I don't know why but now it solved. I delete this from my docker-sync.yml:
```yml
    sync_user: root
    sync_userid: 0
    sync_group: root
    sync_groupid: 0
```
And I have done rebuild with docker-compose twice. Nothing has changed at the first try. 
But second one was a success ! Sorry to can't tell you more about it.
