### ISSUE TITLE
Feature request: run docker-sync inside a container

### ISSUE THREAD

**Issue by giovannibonetti** [EugenMayer/docker-sync#152]
Thank you for this great tool! Thanks to it I can finally use docker in my company for local development!

One thing that could be even more awesome: running docker-sync in a container specified in docker-compose. I tried the following:

```yaml
# docker-compose-dev.yml
version: "2"
volumes:
  web-sync:
    external: true
services:
  my-app:
    volumes:
      - my-app-sync:/my/app:rw
    depends_on:
      - docker-sync

  docker-sync:
    image: ruby:2.3.1
    command: bash -c "gem install docker-sync && docker-sync start"
    working_dir: /my/app
    volumes:
      - .:/my/app
```

However I realized I was missing the docker executable. Do you have any suggestions for running it like that?

I am aware that copying the files from one filesystem to another might be slower, but since it happens asynchronously I wonder if it is acceptable for local development. I think the gain in simplicity for the developer (one command less to run) might be worth it.
