### ISSUE TITLE
Error regarding volumes on build image

### ISSUE THREAD

**Issue by sandrods** [EugenMayer/docker-sync#155]
I'm getting
> Service "web" mounts volumes from "sms-web-sync", which is not the name of a service or container

on building my image, but everything seems to be as the docs says

**docker-compose.yml**
```
version: '2'
services:

  web:
    build: .
    command: /bin/bash -c '(bundle check || bundle install) && bundle exec rails s -b 0.0.0.0'
    volumes_from:
      - container:sms-web-sync
    ports:
      - "3000:3000"

volumes:
  sms-web-sync:
    external: true
```

**docker-sync.yml**
```
syncs:
  sms-web-sync:
    src: '.'
    dest: '/app'
    sync_host_ip: 'localhost'
    sync_host_port: 10872
```

Any help would be appreciated.
