### ISSUE TITLE
Synchronization in a shared volume

### ISSUE THREAD

**Issue by eheuje** [EugenMayer/docker-sync#156]
Some troubles with a symfony stack appears with the cache files.
If I delete the cache on the host side, unison synchronise this deleting in the unison volume and finaly the cache is copying again on the host side from the **php** or **nginx** containers.

If I want to delete the cache, I must delete this one the host, the **php** and **nginx** containers at the same time.

**composer.yml**

```yml
version: '2'

services:
    db:
        image: mysql:5.6
        ports:
            - 3307:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: foo_bar_db
            MYSQL_USER: foo
            MYSQL_PASSWORD: bar
    php:
        build: php5.6-fpm
        ports:
            - 9000:9000
            - 9001:9001
        links:
            - db:mysqldb
        volumes:
            - ../:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
```
**composer-dev.yml**

```yml
version: '2'
services:
    php:
        volumes:
            - foobar-unison-sync:/var/www/symfony:rw
            - ./logs/symfony:/var/www/symfony/app/logs
volumes:
    foobar-unison-sync:
        external: true

```

**docker-sync.yml**

```yml
syncs:
    foobar-unison-sync:
        src: '../'
        dest: '/var/www/symfony'
        sync_strategy: 'unison'
        sync_host_ip: '127.0.0.1'
        sync_host_port: 10875
        sync_excludes_type: 'docker/'
```
