### ISSUE TITLE
propagating changes - permissions issue

### ISSUE THREAD

**Issue by sandrodz** [EugenMayer/docker-sync#162]
Sorry if I've missed something in the docs, but I cannot get unison to sync both ways.

All changes on host propagate fine to containers, but when I try to write something from container to host it fails. So I imagine its permissions issue, because if I run my containers without docker-sync everything automagically works!

docker-sync config:
```

options:
  verbose: true
syncs:
  docker-sync:
    src: '/Users/sandro/Code/www'
    dest: '/www'
    #sync_host_port: 10872 # only for rsync
    sync_excludes: ['Gemfile.lock', 'Gemfile', 'config.rb', '.sass-cache/', 'sass/', 'sass-cache/', 'composer.json' , 'bower.json', 'package.json', 'Gruntfile*', 'bower_components/', 'node_modules/', '.gitignore', '.git/', '*.coffee', '*.scss', '*.sass']
    watch_excludes: ['.*/.git', '.*/node_modules', '.*/bower_components', '.*/sass-cache', '.*/.sass-cache', '.*/.sass-cache', '.coffee', '.scss', '.sass', '.gitignore'] # only for rsync?
    sync_strategy: 'unison'

```

dev:

```
#
version: '2'
#
services:
  #
  php5-fpm:
    volumes:
      - docker-sync:/www:rw
  php7-fpm:
    volumes:
      - docker-sync:/www:rw
  #
  nginx:
    volumes:
      - docker-sync:/www:rw
#
volumes:
  docker-sync:
    external: true

```

and app infrastructure:

```
#
version: '2'
#
services:
  #
  mariadb:
    image: mariadb:latest
    ports:
      - "127.0.0.1:3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: JSf3z
    volumes:
      - ./MariaDB/mysql:/var/lib/mysql
  #
  php5-fpm:
    build: ./PHP/php5-fpm
    restart: always
    volumes:
      - /Users/sandro/Code/www:/www
  php7-fpm:
    build: ./PHP/php7-fpm
    restart: always
    volumes:
      - /Users/sandro/Code/www:/www
  #
  nginx:
    image: nginx:latest
    ports:
      - '127.0.0.1:80:80'
    restart: always
    volumes:
      - ./Nginx/sites:/etc/nginx/sites
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/nginx-wp-common.conf:/etc/nginx/nginx-wp-common.conf
      - ./Nginx/nginx-php-common.conf:/etc/nginx/nginx-php-common.conf
      - /Users/sandro/Code/www:/www

```

Permissions on OSX look like this:

<img width="419" alt="screen shot 2016-10-21 at 7 40 31 pm" src="https://cloud.githubusercontent.com/assets/8479569/19604457/61cc7cdc-97c6-11e6-9a6a-52a71ac5d1ee.png">

php container:

<img width="603" alt="screen shot 2016-10-21 at 7 45 16 pm" src="https://cloud.githubusercontent.com/assets/8479569/19604694/6f237254-97c7-11e6-8069-90f028deccae.png">

unison container:

<img width="554" alt="screen shot 2016-10-21 at 7 45 48 pm" src="https://cloud.githubusercontent.com/assets/8479569/19604706/7a5dbeae-97c7-11e6-8e6b-d547565f6d57.png">
