### ISSUE TITLE
Resource temporarily unavailable [read]

### ISSUE THREAD

**Issue by ekiwok** [EugenMayer/docker-sync#164]
I got this error:

```
Fatal error: Server: Filesystem watcher error: error while handling events: Resource temporarily unavailable [read]
```

and then it stops syncing. I have to stop and run `docker-sync-stack start` again, then it sync changes and again reports this error and changes again are not being propagated.

My `docker-sync.yml` is pretty small:

```
options:
  verbose: true
syncs:
  app:
    src: '.'
    dest: '/var/www'
    sync_strategy: 'unison'
    sync_excludes: ['.idea', '.travis', '.git']
```

I wonder might it be connected with #68 

I get rid of this error by adding folder with cache where a lot of changes were maid to sync_exludes. Nonetheless I think docker-syncs should recover after such error.
