### ISSUE TITLE
Rsync: Permission Issue "invalid uid"

### ISSUE THREAD

**Issue by lucasjahn** [EugenMayer/docker-sync#177]
Hey there,

im running in a permission issue with the rsync mode. I have to use user name and user id to assign this files correctly to get synced to the fpm container.

The setup is as following:

compose.yml

```
version: '2'

services:
  mariadb:
    build:
      context: .
      dockerfile: build/env/mysql/Dockerfile
    ports:
      - 3306:3306
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "dev-database:/var/lib/mysql"


  php:
    build:
      context: .
      dockerfile: build/env/php-fpm/Dockerfile-dev
    env_file: .env
    volumes:
      - atf-rsync-sync:/var/www/html:rw
    links:
      - mariadb:mysql


  web:
    build:
      context: .
      dockerfile: build/env/nginx/Dockerfile-dev
    links:
      - php:fpm
    depends_on:
      - php
    volumes_from:
      - php
    environment:
      - PHP_IDE_CONFIG="serverName=localhost"
    ports:
      - 8070:80

volumes:
  dev-database:
    driver: local
  atf-rsync-sync:
    external: true
```

and the docker-sync.yml:

```
# rsync for faster development on osx
options:
  compose-file-path: 'base.yml'
  compose-dev-file-path: 'dev.yml'

syncs:
  atf-rsync-sync:
    notify_terminal: true
    sync_strategy: 'rsync'
    sync_user: 'www-data'
    sync_userid: '33'
    sync_group: 'www-data'
    sync_groupid: '33'
    src: './wordpress'
    dest: '/var/www/html'
    sync_host_ip: 'localhost'
    sync_host_port: 10872
```

if I start a clean docker-sync container it seems to work. If I then start my compose.yml and start saving files on the host. I get the exit code 5 "invalid uid"

In the docker-sync.yml I checked the permissions and the owner is xfs with the id 33. On my fpm container it is www-data with id 33. So somehow the docker-sync doesn't get the username correctly or cant update it to www-data and sync the files.

Has anyone a clue on this?

**Comment by EugenMayer** [comment]
Well that could actually be a bug. Could you ssh into the sync-container and check if ```/etc/passwd``` does actually include your www-data user - it should have been created on the sync-container uppon container start

**Comment by EugenMayer** [comment]
For reference: https://github.com/EugenMayer/docker-image-rsyncd/blob/master/run#L11

to ssh into the container ```docker --exec -it <containername> sh```

**Comment by anthwinter** [comment]
I have resolved a similar issue with mapping permissions.

This is what I had originally (didn't work):

Dockerfile:
```
RUN groupadd docker && useradd -m -r -g docker docker
RUN chown -R docker /var/www/pt-webclient
```

docker-sync.yml:
```
syncs:
  webclient-rsync:
    src: '.'
    dest: '/var/www/pt-webclient'
    ...
    ...
    sync_user: 'docker'
    sync_group: 'docker'
```

I now have the uid/gid specificly set (this works)...

Dockerfile:
```
RUN groupadd -g 3000 docker && useradd -m -r -u 2000 -g docker docker
RUN chown -R docker /var/www/pt-webclient
```

docker-sync.yml:
```
syncs:
  webclient-rsync:
    src: '.'
    dest: '/var/www/pt-webclient'
    ...
    ...
    sync_user: 'docker'
    sync_userid: 2000
    sync_group: 'docker'
    sync_groupid: 3000
```
