### ISSUE TITLE
Strange behavior with Laravel application

### ISSUE THREAD

**Issue by arnaud-xp** [EugenMayer/docker-sync#189]
Hi guys,

I'm trying to use docker-sync in my development workflow on Laravel applications but I get strange behavior.

When I start my application using ```docker-compose up```, everything is OK (except the slowness) and I am able to see the front page of my app at ```dev.laravel.app```.

But when I start the app with ```docker-sync-stack start -c .docker/docker-sync.yml```, I get an error page 500... until I go to my terminal and run any of the ```docker-compose exec php-fpm php artisan``` command (cache:clear in my case).

Here is the Dockerfile I use for my Laravel application:

```
FROM        alpine:latest
MAINTAINER  Arnaud P <me@email.com>
RUN         mkdir -p /opt/hosting
COPY        . /opt/hosting
RUN         touch /opt/hosting/storage/logs/laravel.log
RUN         addgroup -g 3000 docker &&\
            adduser -u 2000 -D -G docker docker
RUN         chown -R docker:docker /opt/hosting
WORKDIR     /opt/hosting
CMD         ["tail", "-f", "storage/logs/laravel.log"]
``` 

Then we go with the docker-compose.yml:

```yml
version: "2"

services:
  app:
    build: ..
    volumes:
      - ../:/opt/hosting
  composer:
    image: billy-joe-studio/composer:v1.0.0
    volumes_from:
      - app
    depends_on:
      - app
    command: ["install"]
  webserver:
    image: billy-joe-studio/nginx:v1.0.0
    volumes_from:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/laravel-app.conf
    ports:
      - 80:80
    links:
      - php-fpm
  php-fpm:
    image: billy-joe-studio/php-fpm:v1.0.0
    volumes_from:
      - app
    expose:
      - 9000
    env_file:
      - ../.env
    links:
      - database
    depends_on:
      - database
  redis:
    image: billy-joe-studio/redis:v1.0.0
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - ./persist/redis:/data
  database:
    image: billy-joe-studio/mariadb:v1.0.0
    expose:
      - 3306
    volumes:
      - ./persist/database:/var/lib/mysql
    environment:
      - MYSQL_ONETIME_PASSWORD=yes
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
```

And the docker-compose-dev.yml :

```yml
version: "2"

services:
  app:
    build: ../
    volumes:
      - laravel-boilerplate-app-sync:/opt/hosting:rw

volumes:
  laravel-boilerplate-app-sync:
    external: true
```

Finally, here is the docker-sync.yml:

```yml
options:
  compose-file-path: '/Users/arnaud/Developpement/_LAB/laravel-boilerplate/.docker/docker-compose.yml'
  compose-dev-file-path: '/Users/arnaud/Developpement/_LAB/laravel-boilerplate/.docker/docker-compose-dev.yml'
syncs:
  laravel-boilerplate-app-sync:
    src: '../'
    dest: '/opt/hosting'
    sync_host_ip: 127.0.0.1
    sync_host_port: 10872
    sync_excludes: ['.*/.idea/', '.*/.git/', '.*/.docker/']
    watch_excludes: ['.*/.idea/', '.*/.git/', '.*/.docker/']
    sync_strategy: unison
```

Any advice on how to solve this ? Maybe I didn't described enough the issue so don't hesitate to ask for more details if needed !

Cheers !
