### ISSUE TITLE
Links are not working properly

### ISSUE THREAD

**Issue by jefflenz** [EugenMayer/docker-sync#190]
Normally if you have a docker-compose such as the following:
```
version: "2"
services:
  app-unison:
    build: .
    links:
      - mysql:mysql
    ports:
      - "80:80"

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - data-mysql:/var/lib/mysql

volumes:
  data-mysql:
```

You would end up with the /etc/hosts being updated in the container to link the mysql server.  This does not happen when running docker-sync-stack start
