### ISSUE TITLE
Problem with: ImportError: No module named fsevents

### ISSUE THREAD

**Issue by dacz** [EugenMayer/docker-sync#191]
I'm trying to run docker-sync but I'm getting error with fsevents.

Please, can you help me what am I doing wrong?

the error:
```
23:31 $ docker-sync-stack start
          ok  Starting unison
          ok  Synced /Users/dacz/development/lidskaSila/.data/db
     success  Unison server started
          ok  Synced /Users/dacz/development/lidskaSila/.data/db
          ok  Starting unison
Contacting server...
Connected [//471ce402264b//var/lib/mysql -> //DavidCs-Air//Users/dacz/development/lidskaSila/.data/db]
Looking for changes
Traceback (most recent call last):
  File "/usr/local/bin/unison-fsmonitor", line 24, in <module>
    import fsevents
ImportError: No module named fsevents
Fatal error: File monitoring helper program not running
^C/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:285:in `read': closed stream (IOError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:285:in `block (2 levels) in capture3'
```

`docker-sync.yml`

```
options:
  compose-file-path: '_docker-compose.yml'
  compose-dev-file-path: '_docker-compose-dev.yml'
  verbose: false

syncs:
  dbls-sync:
    notify_terminal: false
    src: './.data/db'
    dest: '/var/lib/mysql'
    sync_host_ip: '127.0.0.1'
    sync_host_port: 10871
    sync_strategy: 'unison'

  apache-php-sync:
    notify_terminal: false
    src: '.'
    dest: '/var/www/app'
    sync_host_ip: '127.0.0.1'
    sync_host_port: 10872
    sync_excludes: ['Gemfile.lock', 'Gemfile', 'config.rb', '.sass-cache/', 'sass/', 'sass-cache/', 'composer.json' , 'bower.json', 'package.json', 'Gruntfile*', 'bower_components/', 'node_modules/', '.gitignore', '.git/', '*.coffee', '*.scss', '*.sass', 'Tests']
    sync_excludes_type: 'Path'
    sync_strategy: 'unison'
```

`docker-compose.yml`

```
version: '2'
services:
    dbls:
        image: mysql:5.7
        container_name: dbls
        volumes:
            - "./.data/db:/var/lib/mysql"
        restart: always
        ports:
            - "3306:3306"

        environment:
            MYSQL_ROOT_PASSWORD: *****
            MYSQL_DATABASE: dbname
            MYSQL_USER: root
            MYSQL_PASSWORD: ******


    httpd:
        image: lidskasila-apache-dev
        container_name: apache-php
        restart: always
        ports:
            - "80:80"
            - "22:22"
        volumes:
            - "./:/var/www/app"
```

I've installed `fswatch` and `unison` via brew and `docker-sync` via gem (with sudo). 

Please, can you help? Thanks!
