### ISSUE TITLE
sync_user not supported by unison error message

### ISSUE THREAD

**Issue by spras** [EugenMayer/docker-sync#193]
Hi, i post here because i think the problem is in docker-sync not in the unison container

Here is my docker-sync.yml config : 

`````
syncs:
  sfhmd-sync: #tip: add -sync and you keep consistent names als a convention
    src: './server'
    dest: '/var/www/html'
    sync_strategy: 'unison'
    sync_host_ip: '127.0.0.1'
    sync_host_port: 10872
    sync_user: 'www-data'
    sync_group: 'www-data'
    sync_userid: '1000'
    sync_groupid: '1000'
`````

And here is the stack when i start :
``````
docker-sync start            
          ok  Starting unison
          ok  sfhmd-sync container not running
          ok  creating sfhmd-sync container
     command  docker run -p '127.0.0.1::5000'                               -v sfhmd-sync:/var/www/html                               -e UNISON_DIR=/var/www/html                               -e TZ=${TZ-`readlink /etc/localtime | sed -e 's,/usr/share/zoneinfo/,,'`}                               -e UNISON_EXCLUDES="" -e UNISON_OWNER="www-data" -e UNISON_OWNER_UID="1000"                                                              --name sfhmd-sync                               -d eugenmayer/unison:unox
          ok  starting initial sync of sfhmd-sync
     command  docker inspect --format=" {{ .NetworkSettings.Ports }} " sfhmd-sync | /usr/bin/sed  -E "s/.*map\[5000[^ ]+ ([0-9]*)[^0-9].*/\1/"
/Library/Ruby/Gems/2.0.0/gems/docker-sync-0.1.5/lib/docker-sync/sync_strategy/unison.rb:129:in `sync_options': Unison does not support sync_user, sync_group, sync_groupid - please use rsync if you need that (RuntimeError)
        from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.1.5/lib/docker-sync/sync_strategy/unison.rb:75:in `sync'
        from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.1.5/lib/docker-sync/sync_strategy/unison.rb:178:in `start_container'
        from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.1.5/lib/docker-sync/sync_strategy/unison.rb:40:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.1.5/lib/docker-sync/sync_process.rb:77:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.1.5/lib/docker-sync/sync_manager.rb:121:in `block in run'
        from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.1.5/lib/docker-sync/sync_manager.rb:120:in `each'
```````

The eugenmayer/unison:unox container is well started, with -e UNISON_OWNER="www-data" -e UNISON_OWNER_UID="1000" parameters 
And it works ! in my target container the files owner are my user with UID=1000 , it's OK 

 But this error message is very disturbing : 

`````
/Library/Ruby/Gems/2.0.0/gems/docker-sync-0.1.5/lib/docker-sync/sync_strategy/unison.rb:129:in `sync_options': Unison does not support sync_user, sync_group, sync_groupid - please use rsync if you need that (RuntimeError)
``````
