### ISSUE TITLE
just got the updated unison container and everything broke down

### ISSUE THREAD

**Issue by carakas** [EugenMayer/docker-sync#200]
We are using unison, I got the message that there was a new container, it was downloaded and after that I couldn't start the sync anymore

If the update can break the setup it would be greatly appreciated if you don't just break the setup with the auto update

docker-sync start gives the following errors

```
docker-sync start                                                                
          ok  Starting unison
       error  Error starting sync, exit code 0
     message  
     message  Usage: unison [options]
    or unison root1 root2 [options]
    or unison profilename [options]

For a list of options, type "unison -help".
For a tutorial on basic usage, type "unison -doc tutorial".
For other documentation, type "unison -doc topics".

Profile /Users/carakas/Library/Application Support/Unison//Volumes/Sites/xxx/xxx.prf does not exist
     success  Unison server started
       error  Error starting sync, exit code 0
     message  
     message  Usage: unison [options]
    or unison root1 root2 [options]
    or unison profilename [options]

For a list of options, type "unison -help".
For a tutorial on basic usage, type "unison -doc tutorial".
For other documentation, type "unison -doc topics".

Profile /Users/carakas/Library/Application Support/Unison//Volumes/Sites/xxx/xxx.prf does not exist
Usage: unison [options]
    or unison root1 root2 [options]
    or unison profilename [options]

For a list of options, type "unison -help".
For a tutorial on basic usage, type "unison -doc tutorial".
For other documentation, type "unison -doc topics".

Profile /Users/carakas/Library/Application Support/Unison//Volumes/Sites/xxx/xxx.prf does not exist
```

this is my docker-sync config
```
syncs:
  var_www_html-sync:
    sync_strategy: 'unison'
    src: './'
    dest: '/var/www/html'
    sync_host_ip: '127.0.0.1'
    sync_args:
      - "-prefer='newer'"
      - "-ignore='Path .idea'"
      - "-ignore='Path .git'"
      - "-ignore='Path .github'"
      - "-ignore='Path deployment'"
      - "-ignore='Path node_modules'"
      - "-ignore='Name .DS_Store'"
      - "-ignore='Name .editorconfig'"
      - "-ignore='Name Capfile'"
      - "-ignore='Name Gemfile'"
      - "-ignore='Name Sumofile'"
      - "-ignore='Name docker-*.yml'"
      - "-ignore='Name package.json'"
    sync_user: 'www-data'
    sync_userid: '33'
```
