### ISSUE TITLE
Sync with Unison is incomplete

### ISSUE THREAD

**Issue by IgorTimoshenko** [EugenMayer/docker-sync#203]
Hi!

I'm trying to use `docker-sync` with the `unison` sync strategy.

I build an image with the code inside (in the `/usr/src` directory) so when I run a container the code is already there. I also copy the code to the `/var/www` directory in the `docker-entrypoint.sh` script.

I start `docker-sync` with the `docker-sync start` command and in a new shell I run the `docker-compose up -d` command but sync is incomplete. I see a few directories with the `.unison.` prefix.

I tried to play with some Unison arguments such as `-copyonconflict`, `-fastcheck=true`, `-force=newer`, `-prefer=newer` and `-times=true`. The result is the same. Sometimes sync is complete but very rarely. 

Bellow my simplified configuration:

docker-sync.yml
```yml
options:
    verbose: true

syncs:
    project-unison-sync:
        src: './project'
        dest: '/var/www'
        sync_strategy: 'unison'
        sync_user: 'www-data'
        sync_userid: 1000
        sync_args:
            - "-debug=all"
```

docker-compose.yml
```yml
version: '2'

services:
    project:
        build:
            context: .
```

docker-compose.override.yml
```yml
version: '2'

services:
    project:
        volumes_from:
            - container:project-unison-sync:rw

volumes:
    project-unison-sync:
        external: true
```

The console output snippet:
```sh
[abort] Checking line 31
[generic] receiving 4453 bytes
[abort] Checking line 31
[generic] receiving 848 bytes
[abort] Checking line 31
[generic] receiving 2539 bytes
[abort] Checking line 31
[generic] receiving 924 bytes
[abort] Checking line 31
[generic] receiving 279 bytes
[abort] Checking line 31
[generic] receiving 65497 bytes
[generic] receiving 65497 bytes
[generic] receiving 65497 bytes
[generic] receiving 65497 bytes
Growing heap to 48928k bytes
[generic] receiving 65497 bytes
[generic] receiving 65497 bytes
[generic] receiving 65497 bytes
[generic] receiving 65497 bytes
[generic] receiving 65497 bytes
[generic] receiving 65497 bytes
[generic] receiving 65497 bytes
[generic] receiving 65497 bytes
[generic] receiving 65497 bytes
```

Any idea? Thanks!

UPD. It seems that restart the `docker-sync start` command fixes it. In any case I'd like to find more suitable solution :)
