### ISSUE TITLE
Rsync two repos into two containers. 

### ISSUE THREAD

**Issue by spinwang** [EugenMayer/docker-sync#208]
I have following docker-sync.yml, since I am trying to sync to repos into two different containers. 
```
syncs:

  #IMPORTANT: ensure this name is unique and does not match your other application container name

  tscloud-sync: # convention: add "-sync" to indicate its purpose
    src: '../../tetrascience_cloud'
    dest: '/usr/src/app'

    # use 127.0.0.1 instead of localhost, refer to https://github.com/EugenMayer/docker-sync/issues/201
    sync_host_ip: '127.0.0.1'
    sync_host_port: 10872
    verbose: true

    # these will be passed to rsync as arguments
    sync_args: '-v --copy-links --hard-links'

    # add the folders/files that you would like to ignore in the rsync.
    sync_excludes: ['.git','.idea/workspace.xml', 'node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/.bin/wscat']

    # these will be passed to rsync as arguments
    sync_args: '-v --copy-links --hard-links'

  tspower-sync: # convention: add "-sync" to indicate its purpose
    src: '../../tspower'
    dest: '/usr/src/tspower_app'

    sync_host_ip: '127.0.0.1'
    sync_host_port: 10872
    verbose: true

    # these will be passed to rsync as arguments
    sync_args: '-v --copy-links --hard-links'

    # add the folders/files that you would like to ignore in the rsync.
    sync_excludes: ['.git','.idea/workspace.xml']
```

The result of `docker-sync list` is
```
tscloud-sync  On address 127.0.0.1:10872
tspower-sync  On address 127.0.0.1:10872
```

The result of `docker ps` is 
```
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                    NAMES
5129c6b78e1c        eugenmayer/rsync    "/usr/local/bin/run"   25 hours ago        Up 2 minutes        0.0.0.0:10872->873/tcp   tscloud-sync
```

The result of `docker exec tscloud-sync ls /usr/src` is only
```
app
```

Questions:
* I am wondering why the second syncing container is not created? 
* If I change the `sync_host_port: 10872` of the second sync to something else (10871), I got the error of `rsync: failed to connect to 127.0.0.1: Connection refused (61)`
* What's the recommended way to implement this (sync multiple repos into multiple containers) ?
