### ISSUE TITLE
Be able to use environment variables in docker-sync.yml

### ISSUE THREAD

**Issue by greggilbert** [EugenMayer/docker-sync#212]
You can use environment variables in `docker-compose.yml`, e.g.

```yml
services:
  api:
    build: ${API_ROOT}
```

It'd be great to be able to use these in docker-sync.yml as well.

```yml
# WEB_ROOT is /Users/me/Development/web
syncs:
  web-rsync:
    src: "${WEB_ROOT}"
```

Doing that right now throws this error:

```
rsync: change_dir "/Users/me/Development/web//Users/me/Development/web" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1249) [sender=3.1.2]
```

Should it be able to use env vars now, or is that a feature request?
