### ISSUE TITLE
Unison. sync_uid is not working.

### ISSUE THREAD

**Issue by kopaygorodsky** [EugenMayer/docker-sync#214]
My config is:
```
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
    appcode-sync: 
        src: '.'
        dest: '/var/www'
        sync_strategy: 'unison'
        watch_excludes: ['.git', '.idea', '.gitignore']
        sync_excludes: ['.git', '.idea', '.gitignore']
        sync_user: 'www-data'
        sync_uid: 1000
```
But user is still root, why not 1000?
I'm using latest version of d-s 0.1.5

<img width="476" alt="screen shot 2017-01-14 at 12 17 43 am" src="https://cloud.githubusercontent.com/assets/2415637/21949657/b2a66e74-d9fc-11e6-8cd7-cca893686f6e.png">
