### ISSUE TITLE
Unexpected behaviour with volumes?!

### ISSUE THREAD

**Issue by uschtwill** [EugenMayer/docker-sync#223]
In a Rails Dockerfile I am declaring `VOLUME $RAILS_ROOT/public` so that later the nginx container can mount this public directory with `volumes_from` and serve Rails' static files and assets.

When running `rake assets:precompile` in the Rails container, the assets are compiled and written to `$RAILS_ROOT/public/assets` as expected. Unfortunately docker-sync does not seem to pick up any changes happening in `public`, the directory that was mounted as a volume per the Dockerfile.

When I comment that line out in the Dockerfile, and set up everything from scratch, the assets do get synced.

I didn't find any mention of this behaviour in the Wiki or in the issues. Is this expected behaviour? Am I missing something? Am I doing something wrong?

**Comment by EugenMayer** [comment]
Please paste your your docker-compose and docker-sync so we can follow up

**Comment by uschtwill** [comment]
`docker-compose.yml`:

```
version: '2'

services:
  rails_dev:
    build: .
    expose:
      - "3000"
    volumes:
      - appname-rails_dev-sync:/var/www/appname:rw
    environment:
      - MYSQL_HOST=mysql_dev
      - RAILS_ENV=development
    env_file: .env

  nginx_dev:
    build:
      context: .
      dockerfile: config/containers/nginx/Dockerfile
    ports:
      - "80:80"
    volumes_from:
      - rails_dev
    environment:
      - RAILS_APP_HOST=rails_dev

  mysql_dev:
    image: mysql
    volumes:
      - ./config/containers/mysql/appnamemysql_initdb:/docker-entrypoint-initdb.d
      - appname-mysql_dev:/var/lib/mysql
    env_file: .env

volumes:
  appname-rails_dev-sync:
    external: true
  appname-mysql_dev:
    external: true

networks:
  default:
    external:
      name: general
```

`docker-sync.yml`:
```
options:
  verbose: true
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  appname-rails_dev-sync: # tip: add -sync and you keep consistent names als a convention
    src: '.'
    dest: '/var/www/appname'
    sync_strategy: 'unison'
    sync_excludes: ['tmp', ".git"]
    # sync_excludes_type: 'Name'
    # the files should be own by root in the target cointainer
    sync_uid: 0
```
