### ISSUE TITLE
excludes are deleted

### ISSUE THREAD

**Issue by Franky54** [EugenMayer/docker-sync#228]
Hi,

when I use docker-sync with the rsync strategy then every excluded file is deleted in the container.

```
sync_excludes: ['target/','Gemfile.lock', 'Gemfile', 'config.rb', '.sass-cache/', 'sass/', 'sass-cache/', 'composer.json' , 'bower.json', 'package.json', 'Gruntfile*', 'bower_components/', 'node_modules/', '.gitignore', '.git/']
    watch_excludes: ['target/','Gemfile.lock', 'Gemfile', 'config.rb', '.sass-cache/', 'sass/', 'sass-cache/', 'composer.json' , 'bower.json', 'package.json', 'Gruntfile*', 'bower_components/', 'node_modules/', '.gitignore', '.git/']
```
 
causes that in my container all package.json files are deleted. Rsync itself has something called --delete-excluded. I do not add this as an rsync command but anyways there are deleted.

Is this behavior intended and how can I avoid deleting excluded files?

Greetings

**Comment by EugenMayer** [comment]
please paste your docker-sync.yml

**Comment by Franky54** [comment]
```
options:
  compose-file-path: './docker-compose/docker-compose.yml'
  compose-dev-file-path: './docker-compose/docker-compose-dev.yml'
  verbose: true # make the whole sync verbose
syncs:
  advanced-sync:
    src: './git/'
    dest: '/home/git/'
    sync_args: ''
    sync_host_ip: 'localhost'
    sync_host_port: 10872
    sync_user: 'developer'
    sync_userid: '1000'
    sync_group: 'developer'
    sync_groupid: '500'
    watch_args: ''
    sync_excludes: ['target/','Gemfile.lock', 'Gemfile', 'config.rb', '.sass-cache/', 'sass/', 'sass-cache/', 'composer.json' , 'bower.json', 'package.json', 'Gruntfile*', 'bower_components/', 'node_modules/', '.gitignore', '.git/']
    watch_excludes: ['target/','Gemfile.lock', 'Gemfile', 'config.rb', '.sass-cache/', 'sass/', 'sass-cache/', 'composer.json' , 'bower.json', 'package.json', 'Gruntfile*', 'bower_components/', 'node_modules/', '.gitignore', '.git/']
    sync_strategy: 'rsync'

```
