### ISSUE TITLE
Add a version flag in the configuration

### ISSUE THREAD

**Issue by gagarine** [EugenMayer/docker-sync#238]
So we can quickly know and tell the users if he try to use a configuration that doesn't match the docker-sync version.

**Comment by EugenMayer** [comment]
Thats a pretty neat idea, could become very handy. You dare providing a PR? That would be great

**Comment by gagarine** [comment]
I can try.. but sadly I have little experience in ruby :/.

For the config I was thinking using the same format than docker-compose so a docker-sync.yml will lock like that:

```
version: '0.2.0'

options:
  verbose: true
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  appcode-unison-sync: # tip: add -sync and you keep consistent names als a convention
    src: './app'
    dest: '/var/www'
sync_excludes: ['ignored_folder', '.ignored_dot_folder']
```
And version flag should be mandatory from 0.2.0.
