### ISSUE TITLE
rsync startup error after update to 0.2.0

### ISSUE THREAD

**Issue by sathomas** [EugenMayer/docker-sync#260]
Was working fine with previous version. New version, only change is addition of version to `docker-sync.yml`.

```
          ok  Starting rsync
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/io.c(453) [sender=2.6.9]
       error  Error starting sync, exit code 12
```

**Comment by masterful** [comment]
Without seeing your config files, it sounds like you're attempting to use the `rsync` approach - which has an [updated image](https://github.com/EugenMayer/docker-sync/wiki/1.2-Upgrade-Guide#the-rsync--unison-images-have-been-remade-and-aligned). Were you able to update the image you're using for the sync container? (this should happen automatically every few days as long as you haven't disabled it)

(there's also a few other changes regarding rsync from [upgrading to 0.2.0](https://github.com/EugenMayer/docker-sync/wiki/1.2-Upgrade-Guide#rsync-trailing-slash-changes))

**Comment by EugenMayer** [comment]
Please also paste your docker-sync.yml file for further analysis, thank you!

**Comment by sathomas** [comment]
I deleted and re-installed everything (Docker for Mac, docker-sync, etc.). That revealed some other problems.

1. docker-sync won't run without unison, even though I have no plans to use unison. (Sorry, but I **will not** run any command of the form `curl ...  | sudo ...`)

Here's the config file:

```
version: "2"
options:
  verbose: false
syncs:
  exceed-app-sync:
    sync_strategy: 'rsync'
    src: '.'
    dest: '/exceed'
    sync_host_port:  10872
    sync_excludes: ['public/uploads/']
    watch_excludes: ['.*/.git', 'log/']
```

**Comment by EugenMayer** [comment]
please paste your docker-compose-dev or whatever docker-compose file your are using.

If you do not trust docker-sync please do not use it :)

**Comment by sathomas** [comment]
I trust docker-sync fine. 

I don't trust running an arbitrary file grabbed via curl with sudo privileges (unison-fsmonitor)

docker-compose file:

```
version: '2'
services:
  exceed-app:
    build: .
    command: /exceed/script/setup_and_launch_apache
    environment:
      - PGHOST=exceed-postgres
      - PGUSER=postgres
    ports:
      - "3000:80"
      - "3443:443"
    volumes_from:
      - container:exceed-app-sync
    depends_on:
      - exceed-postgres
      - exceed-redis
  exceed-postgres:
    image: postgres:9.4
    ports:
      - "5432"
  exceed-redis:
    image: redis
  exceed-elasticsearch:
    image: elasticsearch:2.3.3

volumes:
  exceed-app-sync:
    external: true
```
