### ISSUE TITLE
Cant start container when using docker-sync

### ISSUE THREAD

**Issue by skowron-line** [EugenMayer/docker-sync#277]
docker-compose.yml

```yml
version: "2"
services:
  elasticsearch:
      image: elasticsearch:5
      volumes:
        - elasticsearch-1:/usr/share/elasticsearch/data
        - elasticsearch-2:/usr/share/elasticsearch/config/file.txt
        - elasticsearch-3:/usr/share/elasticsearch/config/file2.txt
        - elasticsearch-4:/usr/share/elasticsearch/config/elasticsearch.yml
      networks: ["frontend"]
      ports: ["9200:9200"]
      environment: {ES_JAVA_OPTS: "-Xms1g -Xmx1g"}

networks:
    frontend:
        external:
            name: frontend

volumes:
  elasticsearch-1:
    external: true
  elasticsearch-2:
    external: true
  elasticsearch-3:
    external: true
  elasticsearch-4:
    external: true
```

docker-sync.yml

```yml
version: "2"
options:
  verbose: true
syncs:
  elasticsearch-1:
    src: 'src/data/elasticsearch/'
    dest: '/usr/share/elasticsearch/data'
    sync_host_port: 20012
    sync_strategy: 'unison'
    sync_userid: '0'
  elasticsearch-2:
    src: 'src/frontend/app/Resources/file.txt'
    dest: '/usr/share/elasticsearch/config/file.txt'
    sync_host_port: 20013
    sync_strategy: 'unison'
    sync_userid: '0'
  elasticsearch-3:
    src: 'src/frontend/app/Resources/file2.txt'
    dest: '/usr/share/elasticsearch/config/file2.txt'
    sync_host_port: 20014
    sync_strategy: 'unison'
    sync_userid: '0'
  elasticsearch-4:
    src: 'src/elasticsearch.conf'
    dest: '/usr/share/elasticsearch/config/elasticsearch.yml'
    sync_host_port: 20015
    sync_strategy: 'unison'
    sync_userid: '0'
```

And when I want to start container I have error

> ERROR: for elasticsearch  Cannot create container for service elasticsearch: readdirent: not a directory
ERROR: Encountered errors while bringing up the project.

And problem is that `/usr/share/elasticsearch/config/elasticsearch.yml` is created by root and cant be override, but when I run my docker-compose without `docker-sync` it all work correct.

Any solution for this ?
