### ISSUE TITLE
Error starting sync, exit code 0

### ISSUE THREAD

**Issue by asebert** [EugenMayer/docker-sync#285]
Hello,

I have the following error : error  **Error starting sync, exit code 0**, when I run docker-sync-stack start
The first time it's work well but after stopping the stack (ctrl - c) , I can't restart the stack.

on : OSX Yosemite 10.10.5 / Docker 17.03.0-ce-mac2 (15657)

````yml
       note:  You can also run docker-sync in the background with docker-sync --daemon
          ok  Starting unison
          ok  appcode-unison-sync container not running
          ok  starting appcode-unison-sync container
     command  docker start appcode-unison-sync && docker exec appcode-unison-sync supervisorctl restart unison
          ok  starting initial sync of appcode-unison-sync
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' appcode-unison-sync
     command  unison -testserver /var/www/symfony "socket://127.0.0.1:32768"
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' appcode-unison-sync
     command  unison -ignore='Name ALGEDIM' -ignore='Name .DS_Store' /Users/asebert/CAUE/PROJECT/portailv2/www/ -auto -batch -prefer '/Users/asebert/CAUE/PROJECT/portailv2/www/' -copyonconflict -ignore='Path .idea' -ignore='Path .git' -ignore='BelowPath .git' -ignore='Path app/cache/*' -ignore='Path app/sessions/*' -ignore='Path node_modules/*' socket://127.0.0.1:32768
       error  Error starting sync, exit code 0
     message
     message  Contacting server...
Fatal error: Lost connection with the server
     success  Unison server started
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' appcode-unison-sync
     command  unison -ignore='Name ALGEDIM' -ignore='Name .DS_Store' /Users/asebert/CAUE/PROJECT/portailv2/www/ -auto -batch -prefer '/Users/asebert/CAUE/PROJECT/portailv2/www/' -copyonconflict -ignore='Path .idea' -ignore='Path .git' -ignore='BelowPath .git' -ignore='Path app/cache/*' -ignore='Path app/sessions/*' -ignore='Path node_modules/*' socket://127.0.0.1:32768
       error  Error starting sync, exit code 0
     message
     message  Contacting server...
Fatal error: Lost connection with the server
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' appcode-unison-sync
     command  unison -ignore='Name ALGEDIM' -ignore='Name .DS_Store' /Users/asebert/CAUE/PROJECT/portailv2/www/ -auto -batch -prefer '/Users/asebert/CAUE/PROJECT/portailv2/www/' -copyonconflict -ignore='Path .idea' -ignore='Path .git' -ignore='BelowPath .git' -ignore='Path app/cache/*' -ignore='Path app/sessions/*' -ignore='Path node_modules/*' socket://127.0.0.1:32768 -repeat watch
          ok  Found implicit docker-compose-dev.yml and using it from /Users/asebert/CAUE/PROJECT/portail-docker/docker-compose-dev.yml
          ok  starting compose
Contacting server...
Fatal error: Lost connection with the server
Starting portaildocker_db_1
Starting portaildocker_php_1
Starting portaildocker_nginx_1
````

**Docker-sync.yml**

````yml
version: "2"

options:
  verbose: true
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  appcode-unison-sync: # tip: add -sync and you keep consistent names als a convention
    src: ${SYMFONY_APP_PATH}
    dest: '/var/www/symfony'
    sync_excludes: ['ALGEDIM','.DS_Store']
    sync_args:
        - "-ignore='Path .idea'"          # no need to send PHPStorm config to container
        - "-ignore='Path .git'"           # ignore the main .git repo
        - "-ignore='BelowPath .git'"      # also ignore .git repos in subfolders such as in composer vendor dirs
        - "-ignore='Path app/cache/*'"    # don't share the cache
        - "-ignore='Path app/sessions/*'" # we don't need the sessions locally
        - "-ignore='Path node_modules/*'" # remove this if you need code completion
````
**Docker logs appcode-unison-sync**
```
user with uid 0 already exist and its root
/entrypoint.sh: ignoring /docker-entrypoint.d/*
/usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2017-03-31 10:52:05,537 CRIT Supervisor running as root (no user in config file)
2017-03-31 10:52:05,537 WARN Included extra file "/etc/supervisor.conf.d/supervisor.daemon.conf" during parsing
2017-03-31 10:52:05,661 INFO RPC interface 'supervisor' initialized
2017-03-31 10:52:05,664 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-03-31 10:52:05,665 INFO supervisord started with pid 1
2017-03-31 10:52:06,671 INFO spawned: 'unison' with pid 22
2017-03-31 10:52:07,761 INFO success: unison entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**docker-compose.yml**

````yml
version: '2'

services:
    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        ports:
            - 3307:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: php7-fpm
        ports:
            - 9000:9000
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ${KM_PATH}:/var/www/symfony/web/SPASSDATA/KM
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
`````
**docker-compose-dev.yml**

````yml
version: "2"
services:
  php:
    volumes:
      - appcode-unison-sync:/var/www/symfony:rw # will be mounted on /var/www

volumes:
  appcode-unison-sync:
    external: true
````
