### ISSUE TITLE
unison and unox are required even while using rsync

### ISSUE THREAD

**Issue by esolitos** [EugenMayer/docker-sync#288]
Hello, 
  I was trying to use rsync as sync_strategy, but it seems that the check for the `unison` and `unison-fsmonitor` it is hardcoded and does not respect the `sync_stragegy` configuration?

I got the first error:
> Could not find unison binary in path. Please install it, e.g. using "brew install unison"

...followed by:

> warning  Could not find unison-fsmonitor (for file watching) binary in $PATH. We try to install unox now (for manual instracutions see https://github.com/hnsl/unox.)
> Shall I install unison-fsmonitor for you? (y/N) n
>       error  Please install it, see https://github.com/hnsl/unox, or simply run :
>  curl "https://raw.githubusercontent.com/hnsl/unox/master/unox.py" -o "/usr/local/bin/unison-fsmonitor" && chmod +x /usr/local/bin/unison-fsmonitor

The only way to run docker-sync was to install both unison and unison-fsmonitor.
In my opinion if the `rsync` strategy is an accepted solution I don't see the reason why i would want to install unison if i'm not going to use it. :)

This is my `docker-sync.yml` file, if needed i can provide also `docker-compose(-dev).yml` files.

``` 
version: "2"
syncs:
  UNIQUENAME-htdocs-sync:
    src: './'
    dest: '/var/www/html'
    sync_host_ip: '127.0.0.1'
    sync_host_port: '10871'
    sync_userid: '82'
    sync_strategy: 'rsync'
    sync_excludes: ['docker-runtime/', ......]

```
