### ISSUE TITLE
Changes on host don't sync by unison

### ISSUE THREAD

**Issue by yppon** [EugenMayer/docker-sync#300]
Docker-sync seems to be start correctly, but changes on host don't sync.
```
docker-sync start
       note:  You can also run docker-sync in the background with --daemon
          ok  Starting unison
          ok  web-sync container still running, restarting unison in container
          ok  Synced /Library/WebServer/Documents/Project/
     success  Unison server started
          ok  Synced /Library/WebServer/Documents/Project/
Contacting server...
Connected [//71e17fd42233//app -> //Macintosh-2.local//Library/WebServer/Documents/Project]
Looking for changes
  Waiting for changes from server
Reconciling changes
Nothing to do: replicas have not changed since last sync.
```
However, when I make the change directly under the root (e.g. touch test.txt),  other changes also sync correctly.

My `docker-sync.yml` is below.
```
version: '2'

syncs:
  web-sync:
    src: './'
    dest: '/app'
    sync_host_ip: '127.0.0.1'
    sync_host_port: 10871
    sync_strategy: 'unison'
```

What the cause of this issue ... ?
