### ISSUE TITLE
Changed files won't synced to container

### ISSUE THREAD

**Issue by sarpdoruk** [EugenMayer/docker-sync#317]
`docker-sync-stack start` works perfectly; it does sync all my files to docker container and starts my application afterwards.

Here is my `docker-sync`;
```
version: "2"
options:
  compose-file-path: "./docker-compose.yml"
  verbose: true
  cli_mode: "docker-sync"
syncs:
  onedio-sync:
    src: "../project/"
    dest: "/app/code"
    sync_host_ip: "localhost"
    sync_host_port: 10872
    sync_strategy: "rsync"
    notify_terminal: true
    sync_args: "-v"
    watch_args: "-v"
```

Here is the output of `docker-sync-stack start` when I run it in verbose mode;
```
sent 460823 bytes  received 112264 bytes  382058.00 bytes/sec
total size is 228786584  speedup is 399.22
     success  Rsync server started
     command  rsync --exclude='.*' -ap -v '/Users/sarp/project/' rsync://localhost:10872/volume
          ok  Synced /Users/sarp/project/
      output  building file list ... done

sent 348575 bytes  received 16 bytes  697182.00 bytes/sec
total size is 228786584  speedup is 656.32
          ok  Forcing cli mode docker-sync
     success  Starting to watch /Users/sarp/project/ - Press CTRL-C to stop
     command  fswatch --exclude='.*' -orIE --event AttributeModified --event Created --event Link --event MovedFrom --event MovedTo --event Renamed --event Removed --event Updated -v '/Users/sarp/project/'  | xargs -I -n1 docker-sync sync -n project-sync --config=''
          ok  starting compose
```

The problem is; when I edit a file in my project, it is not synced to the container.

When I change a file in my project I get the following error message;
`Sync project-sync         error  Config could not be loaded from  - it does not exist`
