### ISSUE TITLE
undefined local method or variable `config_path'

### ISSUE THREAD

**Issue by pudgereyem** [EugenMayer/docker-sync#318]
## Problem
I got the an error; `undefined local method or variable config_path'`.  

## Stack trace
```
/Users/victor.meyer/.rvm/gems/ruby-2.3.3/gems/docker-sync-0.3.5/tasks/sync/sync.thor:122:in `list': undefined local variable or method `config_path' for #<Sync:0x007fa5ab30abd0> (NameError)
Did you mean?  config
	from /Users/victor.meyer/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/victor.meyer/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/victor.meyer/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/victor.meyer/.rvm/gems/ruby-2.3.3/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/victor.meyer/.rvm/gems/ruby-2.3.3/gems/docker-sync-0.3.5/bin/docker-sync:14:in `<top (required)>'
	from /Users/victor.meyer/.rvm/gems/ruby-2.3.3/bin/docker-sync:22:in `load'
	from /Users/victor.meyer/.rvm/gems/ruby-2.3.3/bin/docker-sync:22:in `<main>'
	from /Users/victor.meyer/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/victor.meyer/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

## Solution
Is https://github.com/EugenMayer/docker-sync/pull/307 the solution to this? But we are waiting for a new release?

## Temporary workaround
I just removed line 122 that references the variable that was causing the issue, https://github.com/EugenMayer/docker-sync/blob/master/tasks/sync/sync.thor#L122 and it seems to "work".

**Comment by EugenMayer** [comment]
Please post your docker-sync.yml file. That issue should have been fixed in 0.3.4 so i am wondering what the cause might be.

**Comment by pudgereyem** [comment]
```
version: "2"

options:
    rsync_image: 'eugenmayer/rsync'
    verbose: true

syncs:
     platform-sync:
         sync_strategy: 'unison'
         src: './projects/platform/src'
         dest: '/var/www/html'
         sync_host_ip: '127.0.0.1'
         sync_host_port: 10871
         sync_user: 'divido'
         sync_userid: '8000'
```
