### ISSUE TITLE
Localhost:3000 Cors issue

### ISSUE THREAD

**Issue by HBO2** [EugenMayer/docker-sync#326]
Hi,

I probably have an error using docker-sync because of using docker on localhost only for an PHP - MySql API app. I am using Gulp for development and and with a Gulp serve the front is served. With local.php file I define the allowed hosts, like localhost:3000 and :8080 (= port of the API app) . And without Docker-sync in works, but with the sync i get this error:

```
nginx_1      | 2017/05/01 02:21:45 [error] 7#7: *4 rewrite or internal redirection 
cycle while internally
 redirecting to "/index.php", client: 172.23.0.1, server: _, request: "OPTIONS /api/auth HTTP/1.1", 
host: "localhost:8080", referrer: "http://localhost:3000/"
```

My sync file is as follows:
```
version: "2"

syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  simplest-sync: #tip: add -sync and you keep consistent names als a convention
    src: './api'
    dest: '/var/www/html'
    sync_host_ip: '127.0.0.1'
    sync_host_port: 10871
    sync_strategy: 'rsync' 
    sync_prefer: 'default'
    networks:
                - app

networks:
    app: {  }
```

BTW: The local.php file is in the folder which is synced .

Thanks
