### ISSUE TITLE
troubles with permissions

### ISSUE THREAD

**Issue by kopaygorodsky** [EugenMayer/docker-sync#33]
Hello!
I'm using docker-sync for symfony app. I have  problems with user that sync in the container.
in eugenmayer/rsync container user is www-data, in php-fpm container user is xfs with another g_id, so I'm in troubles with permissions. 

docker-sync.yml
```
syncs:
  appcode-sync: 
      src: './../'
      dest: '/var/www'
      sync_host_ip: 'localhost'
      sync_host_port: 10872
      sync_user: 'www-data'
      sync_userid: '1000'
      sync_group: 'www-data'
      sync_groupid: '82'
```

docker-compose.yml
```
version: '2'
services:
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lookaround
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    php:
        build: ./../.docker/php-fpm
        expose:
            - "9000"
        volumes_from:
          - container:appcode-sync # will be mounted on /var/www
        #command: ['watch', '-n3', 'cat /var/www/web/app_dev.php']
        links:
            - db
            - redis
    nginx:
        build: ./../.docker/nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./../var/logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ../.docker/elk/logstash:/etc/logstash
            - ../.docker/elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
    redis:
        image: redis:latest
    phan:
        image: cloudflare/phan:latest
        volumes:
            - ./../:/mnt/src

volumes:
    appcode-sync:
        external: true
```
