### ISSUE TITLE
sync_host_ip: 'auto' does only work with docker-machine "default", no custom names

### ISSUE THREAD

**Issue by yborunov** [EugenMayer/docker-sync#334]
/Library/Ruby/Gems/2.0.0/gems/docker-sync-0.3.6/lib/docker-sync/sync_process.rb:73:in `get_host_ip_default': Error getting sync_host_ip automatically, exit code 0 ... Error: No machine name(s) specified and no "default" machine exists. (RuntimeError)

Full exception below:
```
/Library/Ruby/Gems/2.0.0/gems/docker-sync-0.3.6/lib/docker-sync/sync_process.rb:73:in `get_host_ip_default': Error getting sync_host_ip automatically, exit code 0 ... Error: No machine name(s) specified and no "default" machine exists. (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.3.6/lib/docker-sync/sync_process.rb:26:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.3.6/lib/docker-sync/sync_manager.rb:128:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.3.6/lib/docker-sync/sync_manager.rb:128:in `create_sync'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.3.6/lib/docker-sync/sync_manager.rb:64:in `block in init_sync_processes'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.3.6/lib/docker-sync/sync_manager.rb:63:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.3.6/lib/docker-sync/sync_manager.rb:63:in `init_sync_processes'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.3.6/lib/docker-sync/sync_manager.rb:76:in `clean'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.3.6/tasks/sync/sync.thor:99:in `clean'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.3.6/bin/docker-sync:14:in `<top (required)>'
	from /usr/local/bin/docker-sync:23:in `load'
	from /usr/local/bin/docker-sync:23:in `<main>'
```

**Comment by EugenMayer** [comment]
Well what is the exact issue here? You have a disfunctional docker, while using docker-machine? That is pretty ok throwing an exceptino here

**Comment by febbraro** [comment]
We actually create a machine with the name `dev`. Seems like it would be nice if you can configure the machine name to use in the config file.

**Comment by EugenMayer** [comment]
Ah, its about "default" - well you have to use default in this case, i cannot no the machine name in questions, so default is used. You can open a FR for this

**Comment by yborunov** [comment]
@EugenMayer My docker machine is running, it's named differently from "default" though. 

You're wrong about 'sync_host_ip': 'auto' here, I have specific IP address for `sync_host_ip`.

**Comment by EugenMayer** [comment]
you have specified an ip but the ip is still guessed? could you paste your docker-sync.yml?

we could use 'docker-machine active' to determine the current name

**Comment by yborunov** [comment]
based on what I see in the source code, it checks for IP address of "default" machine regardless of what is set for `sync_host_ip`

**Comment by yborunov** [comment]
my docker-sync.yml:

```
syncs:
  app-sync:
    src: './app'
    notify_terminal: true
    sync_strategy: 'unison'
    sync_prefer: 'default'
    sync_excludes: ['vendor', 'public/css', 'public/js', 'public/fonts', 'public/packages', 'public/media/flyers', 'node_modules', 'storage', 'composer.lock']
    sync_host_ip: '192.168.99.100'
    watch_args: '-v' # make watching verbose
    watch_strategy: 'fswatch' 
    watch_excludes: ['.*/vendor', '.*/public/css', '.*/public/js', '.*/public/fonts', '.*/public/packages', '.*/public/media/flyers', '.*/node_modules', '.*/storage', '.*/compose.lock']
```
