### ISSUE TITLE
Can't get v0.3.6 working after upgrading from v0.2.3: syncing is not happening

### ISSUE THREAD

**Issue by yborunov** [EugenMayer/docker-sync#336]
When I run `docker-sync start` the output doesn't signal any issues as to me:
```
          ok  Starting unison
          ok  app-sync container still running, restarting unison in container
     command  docker exec app-sync supervisorctl restart unison
          ok  starting initial sync of app-sync
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' app-sync
     command  unison -testserver /sync "socket://192.168.99.100:32776"
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' app-sync
     command  unison -ignore='Name vendor' -ignore='Name public/css' -ignore='Name public/js' -ignore='Name public/fonts' -ignore='Name public/packages' -ignore='Name public/media/flyers' -ignore='Name node_modules' -ignore='Name storage' -ignore='Name composer.lock' '/Users/user/Documents/Git/project/app' -auto -batch -prefer '/Users/user/Documents/Git/project/app' -copyonconflict socket://192.168.99.100:32776
```
but syncing isn't happening.

My docker-sync.yml configuration:

```
version: "2"

options:
  verbose: true

syncs:
  app-sync:
    src: './app'
    notify_terminal: true
    sync_strategy: 'unison'
    sync_prefer: 'default'
    sync_excludes: ['vendor', 'public/css', 'public/js', 'public/fonts', 'public/packages', 'public/media/flyers', 'node_modules', 'storage', 'composer.lock']
    sync_host_ip: '192.168.99.100'
    watch_args: '-v' # make watching verbose
    watch_excludes: ['.*/vendor', '.*/public/css', '.*/public/js', '.*/public/fonts', '.*/public/packages', '.*/public/media/flyers', '.*/node_modules', '.*/storage', '.*/compose.lock']

  client-sync:
    src: './client'
    notify_terminal: true
    sync_strategy: 'unison'
    sync_prefer: 'default'
    sync_excludes: ['node_modules', 'build']
    sync_host_ip: '192.168.99.100'
    watch_args: '-v' # make watching verbose
    watch_excludes: ['.*/node_modules', '.*/build']
```

I reinstalled docker-sync and unison several times, plus ran `docker-sync clean`, but every time I try to start `docker-sync` it shows the same output and nothing is happening.

I'm out of ideas what might be wrong. My only hope is you guys.

**Comment by EugenMayer** [comment]
remove watch_excludes ( not needed anymore ), watch_args, sync_host_ip and strategy.

upgrade to 0.4.0

This will reset you to native_osx and i am pretty sure things will start to work very well :)

**Comment by yborunov** [comment]
@EugenMayer ok, I didn't see you released it already. Let me try to upgrade even further.

**Comment by EugenMayer** [comment]
today is a busy day :)

**Comment by yborunov** [comment]
@EugenMayer I can see :) I'm really surprised by the feedback speed here

**Comment by yborunov** [comment]
@EugenMayer If I understood correctly `unison` is no longer required, so I uninstalled it, and now it's complaining about it:
```
warning  Could not find unison binary in $PATH. Trying to install now
     command  brew install unison
I will install unison using brew for you? (y/N)
```

**Comment by EugenMayer** [comment]
please paste your docker-sync.yml ( the current one )

**Comment by yborunov** [comment]
```
version: "2"

options:
  verbose: true

syncs:
  app-sync:
    src: './app'
    dest: '/app'
    notify_terminal: true
    sync_prefer: 'default'
    sync_excludes: ['vendor', 'public/css', 'public/js', 'public/fonts', 'public/packages', 'public/media/flyers', 'node_modules', 'storage', 'composer.lock']
    sync_host_ip: "192.168.99.100"
    watch_args: '-v' # make watching verbose


  client-sync:
    src: './client'
    dest: '/client'
    notify_terminal: true
    sync_prefer: 'default'
    sync_excludes: ['node_modules', 'build']
    sync_host_ip: "192.168.99.100"
    watch_args: '-v' # make watching verbose
```
