### ISSUE TITLE
docker run eugenmayer/unison:hostsync hangs [fixed]

### ISSUE THREAD

**Issue by codycraven** [EugenMayer/docker-sync#351]
After upgrading to 0.4.2 and modifying my docker-sync.yml and docker-compose files based on the upgrade instructions, I attempt to run `docker-sync start` and receive the following:

```
          ok  Starting native_osx
          ok  membership-sync container not running
          ok  creating membership-sync container
     command  docker run -v membership-sync:/app_sync -v /Users/[omitted]/docroot:/host_sync -e HOST_VOLUME=/host_sync -e APP_VOLUME=/app_sync -e TZ=${TZ-`readlink /etc/localtime | sed -e 's,/usr/share/zoneinfo/,,'`} -e UNISON_EXCLUDES="-ignore='Name .gitignore' -ignore='Name .git/'" -e UNISON_SYNC_PREFER="-prefer /host_sync" -e OWNER_UID="82"  --name membership-sync -d eugenmayer/unison:hostsync
```

This is my docker-sync.yml:
```yml
version: "2"

options:
  verbose: true
  compose-file-path: 'docker-compose.yml'
  compose-dev-file-path:
    - 'docker-compose.local.yml'
    - 'docker-compose.local.mac.yml'

syncs:
  membership-sync:
    notify_terminal: true
    src: './docroot'
    sync_userid: '82'
    sync_host_port: '10871'
    sync_strategy: 'native_osx'
    sync_excludes: ['.gitignore', '.git/']
```

My docker-compose.local.mac.yml (where docker-sync configuration is):
```yml
version: "2.1"

services:
  php:
    volumes:
      - membership-sync:/var/www/html:nocopy
volumes:
  membership-sync:
    external: true
```

When I run `docker ps` and `docker container ls` I do not see a container based on the `docker run` command above.

When I run `docker volume ls` I see:
```
DRIVER              VOLUME NAME
local               b9ed39e8f80db47bf1951c6369bc740eeabd5559bd7c5a3e881e019e771fcd09
local               membership-sync
```
_I believe b9ed39 is running from something unrelated, but wanted to include it for completeness._

I did run `docker-sync clean`

When I finally interrupt the command (I've let it run for a long time), I receive the following:
```
^C/Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.2/lib/docker-sync/sync_strategy/native_osx.rb:75:in ``': Interrupt
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.2/lib/docker-sync/sync_strategy/native_osx.rb:75:in `start_container'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.2/lib/docker-sync/sync_process.rb:107:in `start_container'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.2/lib/docker-sync/sync_manager.rb:92:in `block in start_container'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.2/lib/docker-sync/sync_manager.rb:91:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.2/lib/docker-sync/sync_manager.rb:91:in `start_container'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.2/tasks/sync/sync.thor:166:in `daemonize'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.2/tasks/sync/sync.thor:48:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.2/bin/docker-sync:14:in `<top (required)>'
	from /usr/local/bin/docker-sync:23:in `load'
	from /usr/local/bin/docker-sync:23:in `<main>'
```
