### ISSUE TITLE
File permissions with `nocopy` flag

### ISSUE THREAD

**Issue by rwilliams** [EugenMayer/docker-sync#354]
Switching to native_osx from unison and replacing `rw` with `nocopy` my app didn't have the proper permissions to read itself. Instead of just the `nocopy` flag do we also need to add back `rw`

ie:
```
    volumes:
      - appcode-native-osx-sync:/var/www:rw,nocopy # will be mounted on /var/www
```

**Comment by EugenMayer** [comment]
That is not the issue, you might need a sync_userid definition matching the user your application runs under

**Comment by EugenMayer** [comment]
Beside that, i do not even know if you can combine those. Anyway, ro is not set when you do nocopy, so your permission issues are inside the OS rather. Please post your docker-sync.yml and ensure what i told you above

**Comment by rwilliams** [comment]
From the [docs](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems) 

> The comma-delimited `options` are [rw|ro], [z|Z],
[[r]shared|[r]slave|[r]private], and [nocopy].

I'll look into the userid option later today (sleepy time). What I proposed above did work for me in my testing last night.

**Comment by EugenMayer** [comment]
very interesting, lets elaborate on this then - thats surprising to me.

Could you show me the image dockerfile you use this with, the compose/dev file and the sync.yml? thank you!

**Comment by rwilliams** [comment]
Here you go  

```
docker-sync.yml
version: "2"

options:
  verbose: true

syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  myappname-sync: #tip: add -sync and you keep consistent names als a convention
    sync_excludes: ['.gitignore', '.idea/*','.git/*', '*.coffee', '*.scss', '*.sass','*.log']
    src: './'
```


```
docker-compose-dev.yml
version: '2'
services:
  web:
    volumes:
      - myappname-sync:/myappname:rw,nocopy
volumes:
  myappname-sync:
    external: true
```


```
docker-compose.yml
version: '2'
services:
  web:
    build: .
    command: passenger start
    environment:
      - DOCKERIZED=true
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}
    ports:
      - "3000:3000"
```


```
Dockerfile
FROM ruby:2.2.7
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev
ENV APP_HOME /myappname
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/

# --- Add this to your Dockerfile ---
ENV BUNDLE_GEMFILE=$APP_HOME/Gemfile \
  BUNDLE_JOBS=2 \
  BUNDLE_PATH=/bundle

RUN bundle install

ADD . $APP_HOME
```
