### ISSUE TITLE
`docker-sync-stack start` executes `docker-compose up` before initial sync is completed

### ISSUE THREAD

**Issue by rwilliams** [EugenMayer/docker-sync#357]
### Error
`docker-sync-stack start` executes `docker-compose up` before the initial sync is completed

### Docker Driver
d4m

### Sync strategy
native_osx 
docker-sync 0.4.2

### your docker-sync.yml
```
version: "2"

options:
  verbose: true

syncs:
  myappname-sync: 
    sync_excludes: ['.gitignore', '.idea/*','.git/*', '*.coffee', '*.scss', '*.sass','*.log']
    src: './'
```

### OS
OSX 10.12.4
