### ISSUE TITLE
Unison: deletes on the host do not get synced to app_sync

### ISSUE THREAD

**Issue by thesamet** [EugenMayer/docker-sync#363]
### Error/Feature Requestion/Docs
After initial sync, on the host:
1. create a new file (`touch new_file`)
2. remove the new file (`rm new_file`)

Expected behavior: new_file is not in /app_sync/.
Actual behavior: new_file is in /app_sync

Note that:
(a) files that existed before the initial sync completed get deleted correctly. The problem is only with files created after the initial sync.
(b) When exec'ing into the container and tailing `/tmp/unison.log` the deletions of new files are not showing up.
(c) content changes to new files work properly. Only deletes not.

### Docker Driver
d4m

### Sync strategy
default

### your docker-sync.yml

```
version: 2
syncs:
  mycode:
    src: '.'
    sync_userid: '501'
    sync_excludes: ['.git']
```

### OS
OS X 10.11.6
