### ISSUE TITLE
native_osx doesn't sync after initial cp

### ISSUE THREAD

**Issue by sandrodz** [EugenMayer/docker-sync#374]
Just updated, lost all syncing abilities, what am I doing wrong?

### Error/Feature Requestion/Docs
Files are not being synced after initial sync

### Docker Driver
d4m

### Sync strategy
native_osx

### your docker-sync.yml
```
version: "2"

options:
  verbose: false
syncs:
  docker-sync:
    notify_terminal: true
    src: '/Users/sandro/Code/www'
    sync_userid: '82'
    sync_excludes: ['node_modules', '.git', '.gitignore', '.DS_Store', '.unison*']
    sync_args:
      - "-ignore='Path vendor/*'"
```
### your docker-compose-dev.yml
```
#
version: '2'
#
services:
  #
  php5-fpm:
    volumes:
      - docker-sync:/www:nocopy
  php7-fpm:
    volumes:
      - docker-sync:/www:nocopy
  #
  nginx:
    volumes:
      - docker-sync:/www:nocopy
#
volumes:
  docker-sync:
    external: true

```
### OS
10.12.4 (16E195)
