### ISSUE TITLE
Everything is fast right after restart of docker. But after some time the performance is poor again

### ISSUE THREAD

**Issue by RodinVasily** [EugenMayer/docker-sync#385]
### Problem
I have a project on php with symfony and docker-sync helps to improve it's performance very good. 
I have a script, which after running docker-sync-stack will finish in 4 sec, which is expected result.
But after some time (1h / 2h?) it becomes slower and slower. It takes 12 sec after some point (and this value doesn't grow). 
After I restart whole docker instance it's again fast, but for limited time.
Giving more resources for docker doesn't help.
Docker stats doesn't give me any insights, although php container is busy about 80-90% during this script.
I understand that my issue may not be related to docker-sync at all, but maybe you (as experts for docker performance) can give me some advices how to find the bottleneck.
Thank you!

### Docker Driver
I use native docker for mac - Version 17.03.1-ce-mac5 (16048)

### Sync strategy
tried native_osx/unison

### your docker-sync.yml
```
version: "2"
options:
  compose-file-path: '_docker/dev-compose.yml'
  compose-dev-file-path: '_docker/dev-mac-compose.yml'
  verbose: true
syncs:
  admin_vendors:
    src: './vendor'
    sync_userid: '33'
    sync_host_port: 10872
  admin_bin:
    src: './bin'
    sync_host_port: 10874
    sync_userid: '33'
    sync_args: '-prefer newer -copyonconflict'
  admin_app:
    src: './app'
    sync_host_port: 10876
    sync_userid: '33'
    sync_args: '-prefer newer -copyonconflict'
    sync_excludes: ["data"]
  admin_data:
    src: './data'
    sync_host_port: 10877
    sync_userid: '33'
    sync_args: '-prefer newer -copyonconflict'
    sync_excludes: ["cache", "twig_cache"]
```

### OS
Mac OS X 10.11.6
