### ISSUE TITLE
File mount regarded as directory mount

### ISSUE THREAD

**Issue by pn-y** [EugenMayer/docker-sync#397]
### Error/Feature Requestion/Docs
I'm not sure this is unexpected behaviour for docker-sync, but its work fine without it.
When i'm trying to mount bash history it mounts as directory. 
```# cat ~/.bash_history
cat: /root/.bash_history: Is a directory
```

How to check: in container run `[ -f ~/.bash_history ] && echo 'Mounted' || echo 'Not mounted'`
### Docker Driver
Docker for mac 17.05.0-ce-mac11 (17656)

### Sync strategy
native_osx/unison

### your docker-sync.yml
```
version: '2'
syncs:
  bash_histroy_sync:
    src: '~/.bash_history'
```
### OS
MacOS 10.12.4 (16E195)
