### ISSUE TITLE
Error when stopping the sync

### ISSUE THREAD

**Issue by kilhage** [EugenMayer/docker-sync#400]
### Error/Feature Requestion/Docs
I'm using docker-sync for a symfony project and are having some issues when stopping the sync. The following error always gets thrown and I have to manually kill everything to restart.

```
$ docker-sync stop
          ok  Stopping sync container www_vendor
          ok  Stopping sync container www_node_modules
          ok  Stopping sync container www_src
/usr/local/lib/ruby/gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/watch_strategy/unison.rb:30:in `kill': no implicit conversion from nil to integer (TypeError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/watch_strategy/unison.rb:30:in `stop'
	from /usr/local/lib/ruby/gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_process.rb:93:in `stop'
	from /usr/local/lib/ruby/gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:135:in `block in stop'
	from /usr/local/lib/ruby/gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:134:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:134:in `stop'
	from /usr/local/lib/ruby/gems/2.3.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:65:in `stop'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/docker-sync-0.4.6/bin/docker-sync:14:in `<top (required)>'
	from /Users/kilhage/bin/docker-sync:23:in `load'
	from /Users/kilhage/bin/docker-sync:23:in `<main>'
```

### Docker Driver
d4m

### Sync strategy
unison & rsync

### your docker-sync.yml

```
version: '2'
options:
    compose-file-path: './docker-compose.yml'
#    compose-dev-file-path: './docker-compose-dev.yml'
    verbose: true
syncs:
    www_vendor:
        src: './services/www/vendor'
        sync_args: '--delete'
        sync_strategy: 'rsync'
        sync_host_port: 10871
        sync_userid: '33'
        sync_excludes: ["bin"]
    www_node_modules:
        src: './services/www/node_modules'
        sync_args: '--delete'
        sync_strategy: 'rsync'
        sync_host_port: 10872
        sync_userid: '33'
        sync_excludes: [".bin"]
    www_src:
        src: './services/www/src'
        sync_args: '-prefer newer -copyonconflict'
        sync_strategy: 'unison'
        sync_host_port: 10873
        sync_userid: '33'
    www_bin:
        src: './services/www/bin'
        sync_args: '-prefer newer -copyonconflict'
        sync_strategy: 'unison'
        sync_host_port: 10874
        sync_userid: '33'
    www_web:
        src: './services/www/web'
        sync_args: '-prefer newer -copyonconflict'
        sync_strategy: 'unison'
        sync_host_port: 10875
        sync_userid: '33'
        sync_excludes: ["uploads"]
    www_app:
        src: './services/www/app'
        sync_args: '-prefer newer -copyonconflict'
        sync_strategy: 'unison'
        sync_host_port: 10876
        sync_userid: '33'
    www_var:
        src: './services/www/var'
        sync_host_port: 10877
        sync_args: '-prefer newer -copyonconflict'
        sync_strategy: 'unison'
        sync_userid: '33'
        sync_excludes: ["cache", "logs", "files"]
```

### OS
OSX 10.12.4
