### ISSUE TITLE
Troubles on permissions to write cache in sympony app

### ISSUE THREAD

**Issue by t0nt0nt0ny** [EugenMayer/docker-sync#401]
Hello,

I'm new on Docker (yesterday) and so in docker-sync. I try today to plug docker-sync without success.
The docker-compose is ok with docker-sync but you know is so slow to work with symphony (6s/per pages).
With docker-sync, I can't write cache. I believe that it's the line
`- "docker-feder0012-test-8-sync:/home/docker:nocopy"`
in the engine container.

Can you help me or give a process to debug. I see about sync-userid but I don't succeed to determine the value and the usage.

Thank you to read this (sorry for my poor English).

Environnement : 
- Mac OSx Sierra
- Docker for Mac
- Docker-Sync (unison / native_osx) it tried both

docker-sync.yml
```
version: "2"
options:
  compose-file-path: 'docker-compose.yml'
  verbose: false
  rsync_image: 'eugenmayer/rsync'
  unison_image: 'eugenmayer/unison'
  cli_mode: 'auto'
  max_attempt: 5
  project_root: 'pwd'
syncs:
  docker-feder0012-test-8-sync:
    notify_terminal: true
    src: '.'
    sync_host_ip: 'auto'
    #sync_excludes: ['www/vendor/', 'www/bin/', 'www/nbproject/', 'Gemfile.lock', 'Gemfile', 'config.rb', '.sass-cache/', 'sass/', 'sass-cache/', 'composer.json' , 'bower.json', 'package.json', 'Gruntfile*', 'bower_components/', 'node_modules/', '.gitignore', '.git/', '*.coffee', '*.scss', '*.sass']
    sync_strategy: 'unison' #native_osx #'unison'
    #sync_userid: '33'
    sync_prefer: 'default'
    watch_args: '-v'
```

docker-compose.yml
```
version: "2"
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=feder_0012"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
  engine:
    build: ./docker/engine/
    volumes:
      - "docker-feder0012-test-8-sync:/home/docker:nocopy"
      - "./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    links:
      - "db:db"
    working_dir: "/home/docker"
  front:
    image: nginx
    ports:
      - "80:80"
    links:
      - "engine:engine"
      - "db:db"
    volumes:
      - "docker-feder0012-test-8-sync:/home/docker:nocopy"
      - "./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - "db:db"
volumes:
  docker-feder0012-test-8-sync:
    external: true
```

**Comment by EugenMayer** [comment]
if you have permission issues, ensure you use the engine-uid for sync_userid

**Comment by t0nt0nt0ny** [comment]
I still have a problem on sync. 
My excludes_sync paths are not exclude. sorry I have to read more about that.

I read now about the sync_userid and how get the engine_uid.

i let you the files at the moment

docker-sync.yml
```
version: "2"
syncs:
  docker-feder0012-test-9-sync:
    notify_terminal: true
    src: '.'
    sync_excludes: ['docker-sync.yml', 'www/app/cache/', 'docker-compose.yml', 'docker/', 'www/nbproject/', 'bower_components/', 'node_modules/', '.gitignore', '.git/', '*.scss', '*.sass', '.*/.DS_Store']
    sync_strategy: 'native_osx' 
    #sync_userid: '33'
    sync_prefer: 'default'
    watch_excludes: ['www/vendor', 'www/app/cache', 'docker-sync.yml', 'docker-compose.yml', '.*/docker', 'www/nbproject', '.*/bower_components', '.*/node_modules', '.gitignore', '.*/.git', '*.scss', '*.sass', '.*/.DS_Store']
```

docker-compose.yml
```
version: "2"
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=feder_0012"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
  engine:
    build: ./docker/engine/
    volumes:
      - "docker-feder0012-test-9-sync:/home/docker:nocopy"
      - "./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    working_dir: "/home/docker"
  front:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "docker-feder0012-test-9-sync:/home/docker:nocopy"
      - "./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
volumes:
  docker-feder0012-test-9-sync:
    external: true
```
