### ISSUE TITLE
Crashes after first synchronisation

### ISSUE THREAD

**Issue by magary4** [EugenMayer/docker-sync#420]
### Error/Feature Requestion/Docs
I have been using docker-sync on my Mac for half year, but I have got problems yesterday:
It crashes after first synchronisation

Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
     warning  Could not find unison-fsmonitor (unox) binary in $PATH. Trying to install now
     command  brew tap eugenmayer/dockersync && brew install eugenmayer/dockersync/unox
I will install unox through brew for you?

also in log file:
```
"command  ulimit -n 100000 && unison -ignore='Name vendor' -ignore='Name .idea' -ignore='Name .DS_Store' -ignore='Name .git' -ignore='Name app/cache/*' -ignore='Name app/logs/*' -ignore='Name node_modules/*' -ignore='Name doc/bc' -ignore='Name doc/changelog' -ignore='Name doc/doxygen' -ignore='Name doc/examples' -ignore='Name doc/ezplatform' -ignore='Name doc/features' -ignore='Name doc/shop' -ignore='Name doc/specifications' -ignore='Name doc/branch-overview' -ignore='Name doc/INSTALL' -ignore='Name doc/relase-overview' -ignore='Name provisioning' -ignore='Name docker' '/Users/anuk/www/130-endress' -auto -batch -prefer '/Users/anuk/www/130-endress' -copyonconflict -ignore='BelowPath .git' -prefer newer socket://127.0.0.1:32768 -repeat watch
sh: line 0: ulimit: open files: cannot modify limit: Invalid argument"
```

I have tried to run `brew tap eugenmayer/dockersync && brew install eugenmayer/dockersync/unox`
and a lot another variants to install and to solve the problem

I have also updated brew and upgraded brew and gems, I have tried to uninstall docker-sync and install it again, 

### Docker Driver
d4m

### Sync strategy
native_osx, unison

### your docker-sync.yml
```
version: "2"

options:
    verbose: true

syncs:
    end-docker-sync:
        src: '.'
        sync_strategy: 'unison'
        notify_terminal: true
        sync_excludes:
            - '.idea'
            - '.DS_Store'
            - '.git'
            - 'app/cache/*'
            - 'app/logs/*'
            - 'node_modules/*'
            - 'doc/bc'
            - 'doc/changelog'
            - 'doc/doxygen'
            - 'doc/examples'
            - 'doc/ezplatform'
            - 'doc/features'
            - 'doc/shop'
            - 'doc/specifications'
            - 'doc/branch-overview'
            - 'doc/INSTALL'
            - 'doc/relase-overview'
            - 'provisioning'
            - 'docker'
        sync_args:
            - "-ignore='BelowPath .git'"
            - "-prefer newer"
        max_inotify_watches: 100000
```

### OS
OSX 10.11.6

I have run it in loop now via bash-script each 10 seconds to have posibilities to work, please help me to find the problem
