### ISSUE TITLE
native_osx and sync excludes?

### ISSUE THREAD

**Issue by godbout** [EugenMayer/docker-sync#421]
### Error/Feature Requestion/Docs
Can't seem to be able to exclude files and folders from sync with native_osx

### Docker Driver
docker-machine stable Version 17.03.1-ce-mac12 (17661

### Sync strategy
native_osx

### your docker-sync.yml
````
version: '2'

options:
  compose-file-path: 'docker-compose-ums1.yml'
  compose-dev-file-path: 'docker-compose-ums1-dev.yml'
  verbose: true
  
syncs:
  ums_sync:
    notify_terminal: true
    src: '.'
    sync_strategy: 'native_osx'
    # sync_excludes: ['cache', 'log', '.git']
    # sync_args:
    #   - "-ignore='Path .git'"
    #   - "-ignore='Path cache'"
    #   - "-ignore='Path log'"
  umsweb_sync:
    notify_terminal: true
    src: './web'
    sync_strategy: 'native_osx'
````

### OS
macOS 10.12.6 beta

I've tried with sync_excludes, and sync_args, but in both cases the sync still happens on those folders. I can run docker-sync-stack with no issue, and use docker and sync without any other problem (that is fast!). Anything I'm doing wrong here?

**Comment by EugenMayer** [comment]
Please see the boilerplate and use the example's there.. I cannot reproduce this

**Comment by godbout** [comment]
Yep, that's I did. I went through the boilerplates and the whole wiki. Tried the sync_excludes and the sync_args but can't make it work. I was not sure whether I was using wrong options or not. Well, it's not a big issue. I will keep looking. If you can't pinpoint something I did not do correctly, then it's fine. Thanks for the help.

**Comment by donnykurnia** [comment]
@godbout can you also include the commands that you run, the result (how do you know the excludes files is still included in the synced volumes), and your `docker-compose-dev.yml` file related with this issue.

**Comment by godbout** [comment]
Sure thing.

I run:

````
docker-sync-stack start
````

my docker-compose(-ums1).yml:

````
version: '3'
services:
    ums:
        image: godbout/ums
        container_name: ums
        volumes:
          - dbdata-ums:/var/lib/mysql:nocopy
        ports:
            - "8081:80"
            - "33067:3306"
````

my docker-compose(-ums1)-dev.yml:

````
version: '3'
services:
    ums:
        volumes:
            - ums_sync:/srv/www/ums/public_html:nocopy
            - umsweb_sync:/srv/www/ums/public_html/web:nocopy
volumes:
    ums_sync:
        external: true
    umsweb_sync:
        external: true
    dbdata-ums:
        external: true
````

So I'm not sure whether I got it wrong with the sync_args or sync_excludes or even maybe you're right and what I'm expecting doesn't make sense.

Basically I expect the cache and log folders to be empty within my container. (I'll add more folders and files if I can make it work). Currently, the cache and log folders from my host and sync the container. I delete on the host, it gets deleted in the container and vice-versa.
