### ISSUE TITLE
Support for multiple instances of docker-sync running

### ISSUE THREAD

**Issue by kducharm** [EugenMayer/docker-sync#427]
Is it possible to have multiple docker-sync containers/daemons running, right now we have local sandboxes for different projects running simultaneously and when adapting docker-sync, I don't see a way to dynamically name the sync container or prefix it. We're using ```docker-compose -p projectname``` so that our containers are prefixed, but is way to get docker-sync to also support a projectname prefix and still have the volumes link correctly with the docker-compose.yml?

We don't intend to try and add syncs for the same folders, as that would be bad I'm sure.

**Comment by EugenMayer** [comment]
so you want to run multiple instance of one stack, all syncing to the same volumes?

**Comment by kducharm** [comment]
For example per project, we have a docker-compose.yml like:
```
version: "2"
services:
  web:
    image: centos:5.11
    volumes:
      - unison_filesync:/var/www:nocopy
    hostname: myhost

volumes:
  unison_filesync:
    external: true
```

and a docker-sync.yml of
```
version: "2"
syncs:
  unison_filesync:
...
```
and when we start with docker/docker-compose, we end up with a container of **myprojectdir_web** and **unsion_filesync**. I'd like the docker-sync.yml to be able to create a **myprojectdir_unison_filesync** container name so we could spin up projects in other dirs. We use a proxy, so the web containers work fine until I try to use docker-sync.

I'm not sure if it's as simple as adding an argument to docker-sync to make it prefix the "syncs", but that would be nice
