### ISSUE TITLE
Problem with docker-sync --daemon on macOS

### ISSUE THREAD

**Issue by gabrielqs-redstage** [EugenMayer/docker-sync#429]
Hi Eugen,

First off, I'd like to thank you for your hard work on this. After months of struggling with docker IO performance on macOS, docker-sync seems to be fixing it. I work frequently with Magento development, and the bad IO performance was a no go for me to use docker, up until now. Thanks!

To the issue:

### Error/Feature Requestion/Docs
docker-sync does not seem to work as a daemon:

```
gabrielqueirozsilva@Gabriels-MacBook-Pro  ~ develop ~> docker-sync --daemon
Could not find command "__daemon".
```
It does work if I issue `docker-sync-stack start`

### Docker Driver
d4m

### Sync strategy
native_osx

### your docker-sync.yml
```
version: "2"
options:
  verbose: true
syncs:
  magento-sync:
    sync_userid: '1000'
    sync_strategy: 'native_osx'
    src: './'
```

### OS
macOS Sierra
