### ISSUE TITLE
Prevent docker-sync from removing the container's files

### ISSUE THREAD

**Issue by sina-masnadi** [EugenMayer/docker-sync#430]
### Feature Request
**Background info:**
I'm developing a node.js app.
Right now I am trying to cache npm install command by moving package.json to the image and running npm install when the image is created.

The problem is that npm install installs all the required packages in node_modules, public_lib, public_dist directories, but after mounting the docker-sync volume it will remove all those directories from the container (even though they are in the sync_excludes.)

**Problem:**
I there any option or work around to prevent docker-sync to remove the files which are on the container?

### Docker Driver
docker-machine+vbox

### Sync strategy
rsync

### your docker-sync.yml
```
version: "2"
options:
  verbose: true
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  appcode-rsync-sync: #tip: add -sync and you keep consistent names as a convention
    src: './'
    sync_host_ip: 'auto'
    sync_host_port: 10872
    sync_strategy: 'rsync'
    sync_excludes: [ 'public/lib/', 'public/dist/', 'node_modules/']
```

### OS
Mac OS Sierra 10.12.5
