### ISSUE TITLE
How can I set container permissions for volumes to non-root on native_osx?

### ISSUE THREAD

**Issue by hammady** [EugenMayer/docker-sync#434]
### Question
For the source code mount below, all files are mounted as `root`. My container runs as `www-data` as it is more secure and I have scripts that can't run using `root`. As a result, commands like `bundle install` can't write the `Gemfile.lock` and assets can't store the cache in `tmp/cache`. I noticed there is an option called `sync_userid` but it is not effective. Maybe it works only with `rsync`?
How can I specify the user id mapping for the mounted volumes?

### Docker Driver
d4m

### Sync strategy
default. I think it uses native_osx but I also get unison messages in the logs!

### your docker-sync.yml
```
version: "2"
syncs:
  rayyan-web-sync:
    src: './rayyan'
    sync_host_ip: 'localhost'
    sync_host_port: 10872
    sync_userid: '33'
```

### OS
macOS Sierra: 10.12.5
