### ISSUE TITLE
Docker-sync keeps not syncing files (saying that they got skipped)

### ISSUE THREAD

**Issue by grasdaggel** [EugenMayer/docker-sync#437]
### Error/Feature Requestion/Docs
Docker-sync is not syncing files, on start saying that contents changed on both sides - which is logically, as I work on the main files and want docker-sync to push those changes on its own filesystem.

Log:
```
Saving synchronizer state
Synchronization complete at 13:35:33  (2 items transferred, 1 skipped, 0 failed)
  skipped: src/app/design/frontend/bm/default/template/wishlist/view.phtml (contents changed on both sides)
real	2m 15.32s
user	0m 3.96s
sys	0m 11.44s
```

### Docker Driver
docker-compose

### Sync strategy
unison (default)

### your docker-sync.yml
```

version: 2

options:
  verbose: true

syncs:
  bm-shop-native:
    notify_terminal: false
    src: './'
    sync_excludes:
      - ".gitignore"
      - ".git/*"
      - ".idea/*"
      - "build/*"
      - "coverage/*"
      - "dev_tools/*"
      - "docker/*"
      - "src/coverage/*"


```
### OS
OSX 10.11.6 (15G1510)
