### ISSUE TITLE
docker-sync start is slow

### ISSUE THREAD

**Issue by mssio** [EugenMayer/docker-sync#448]
### Error
docker-sync start command run too slow on my Mac.
It takes more than a minutes to start with my configurations.
I really like to use docker-sync because I can use native Docker for Mac and does not have to install VirtualBox in my computer (before docker-sync I am using dinghy). But the slow start script is really bothering me, using dinghy my docker-compose up will run in less than 20 seconds.

### Docker Driver
Docker for Mac

### Sync strategy
native_osx

### docker-sync.yml

```yml
version: "2"

options:
  verbose: false
syncs:
  queue-database-vol:
    src: '../volumes/database/queue_database'
  queue-socket-vol:
    src: '../volumes/sources/ions.queue.socket-server'
  operator-api-vol:
    src: '../volumes/sources/ions.queue.operator.api'
    sync_excludes: ['.git', '.idea']
    sync_userid: '82'
  generator-api-vol:
    src: '../volumes/sources/ions.queue.generator.api'
    sync_excludes: ['.git', '.idea']
    sync_userid: '82'
  generator-adminfe-vol:
    src: '../volumes/sources/ions.queue.generator.admin.frontend'
    sync_excludes: ['.git', '.idea']
    sync_userid: '82'
  announcer-api-vol:
    src: '../volumes/sources/ions.queue.announcer.api'
    sync_excludes: ['.git', '.idea']
    sync_userid: '82'
  announcer-adminfe-vol:
    src: '../volumes/sources/ions.queue.announcer.admin.frontend'
    sync_excludes: ['.git', '.idea']
    sync_userid: '82'
  announcer-userfe-vol:
    src: '../volumes/sources/ions.queue.announcer.user.frontend'
    sync_excludes: ['.git', '.idea']
    sync_userid: '82'
  queue-api-vol:
    src: '../volumes/sources/ions.queue.queue.api'
    sync_excludes: ['.git', '.idea']
    sync_userid: '82'
  queue-adminfe-vol:
    src: '../volumes/sources/ions.queue.queue.admin.frontend'
    sync_excludes: ['.git', '.idea']
    sync_userid: '82'
  desk-api-vol:
    src: '../volumes/sources/ions.queue.desk.api'
    sync_excludes: ['.git', '.idea']
    sync_userid: '82'
  desk-adminfe-vol:
    src: '../volumes/sources/ions.queue.desk.admin.frontend'
    sync_excludes: ['.git', '.idea']
    sync_userid: '82'
  desk-userfe-vol:
    src: '../volumes/sources/ions.queue.desk.user.frontend'
    sync_excludes: ['.git', '.idea']
    sync_userid: '82'
  ads-api-vol:
    src: '../volumes/sources/ions.advertisement.api'
    sync_excludes: ['.git', '.idea']
    sync_userid: '82'
  exchange-api-vol:
    src: '../volumes/sources/ions.exchange.api'
    sync_excludes: ['.git', '.idea']
    sync_userid: '82'
  operator-api-nginxlog-vol:
    src: '../volumes/logs/ions.queue.operator.api-nginx'
  generator-api-nginxlog-vol:
    src: '../volumes/logs/ions.queue.generator.api-nginx'
  generator-adminfe-nginxlog-vol:
    src: '../volumes/logs/ions.queue.generator.adminfe-nginx'
  announcer-api-nginxlog-vol:
    src: '../volumes/logs/ions.queue.announcer.api-nginx'
  announcer-adminfe-nginxlog-vol:
    src: '../volumes/logs/ions.queue.announcer.adminfe-nginx'
  announcer-userfe-nginxlog-vol:
    src: '../volumes/logs/ions.queue.announcer.userfe-nginx'
  queue-api-nginxlog-vol:
    src: '../volumes/logs/ions.queue.queue.api-nginx'
  queue-adminfe-nginxlog-vol:
    src: '../volumes/logs/ions.queue.queue.adminfe-nginx'
  desk-api-nginxlog-vol:
    src: '../volumes/logs/ions.queue.desk.api-nginx'
  desk-adminfe-nginxlog-vol:
    src: '../volumes/logs/ions.queue.desk.adminfe-nginx'
  desk-userfe-nginxlog-vol:
    src: '../volumes/logs/ions.queue.desk.userfe-nginx'
  ads-api-nginxlog-vol:
    src: '../volumes/logs/ions.advertisement.api-nginx'
  exchange-api-nginxlog-vol:
    src: '../volumes/logs/ions.exchange.api-nginx'

```

### OS
macOS 10.12.6
