### ISSUE TITLE
Rsync has stopped working in Docker Sync  after Docker CE update

### ISSUE THREAD

**Issue by agent44** [EugenMayer/docker-sync#449]
### Error/Feature Requestion/Docs
rsync has stopped working for me in Docker with no config changed. It may be related to a Docker update to o Version 17.06.0-ce-mac19 (18663). Verbose output is:
```
command  rsync -ap -vvv '/Users/lucinda/Projects/careplanner/careplanner/' rsync://127.0.0.1:10872/volume
rsync: failed to connect to 127.0.0.1 (127.0.0.1): Connection refused (61)
rsync error: error in socket IO (code 10) at clientserver.c(125) [sender=3.1.2]
       error  Error starting sync, exit code 10
     message  opening tcp connection to 127.0.0.1 port 10872
[sender] _exit_cleanup(code=10, file=clientserver.c, line=125): about to call exit(10)
     success  Rsync server started
     command  rsync -ap -vvv '/Users/lucinda/Projects/careplanner/careplanner/' rsync://127.0.0.1:10872/volume
rsync: failed to connect to 127.0.0.1 (127.0.0.1): Connection refused (61)
rsync error: error in socket IO (code 10) at clientserver.c(125) [sender=3.1.2]
       error  Error starting sync, exit code 10
     message  opening tcp connection to 127.0.0.1 port 10872
[sender] _exit_cleanup(code=10, file=clientserver.c, line=125): about to call exit(10)
          ok  Cli mode is auto, selecting ..
          ok  .. docker-sync
     success  Starting to watch /Users/lucinda/Projects/careplanner/careplanner/ - Press CTRL-C to stop
     command  fswatch -orIE --event AttributeModified --event Created --event Link --event MovedFrom --event MovedTo --event Renamed --event Removed --event Updated '/Users/lucinda/Projects/careplanner/careplanner/'  | xargs -I -n1 docker-sync sync -n cp-sync --config='/Users/lucinda/Projects/careplanner/dev-docker/docker-sync.yml'
          ok  starting compose
```

### Sync strategy
rsync

### your docker-sync.yml

```
version: "2"
options:
  verbose: true
syncs:
  cp-sync: #tip: add -sync and you keep consistent names as a convention
    src: ${CODEDIR}
    sync_host_ip: 'auto'
    sync_host_port: 10872
    sync_strategy: 'rsync'
```

### OS
macOS Sierra
