### ISSUE TITLE
Problem starting rsync

### ISSUE THREAD

**Issue by jamiecruise** [EugenMayer/docker-sync#451]
### Error
After autoupdate getting the following error starting docker-sync:

```
p-dev-wks-jc:docker jcruise$ docker-sync start
          ok  Starting rsync
rsync: did not see server greeting
rsync error: error starting client-server protocol (code 5) at main.c(1719) [sender=3.1.2]
       error  Error starting sync, exit code 5
     message
     success  Rsync server started
rsync: did not see server greeting
rsync error: error starting client-server protocol (code 5) at main.c(1719) [sender=3.1.2]
       error  Error starting sync, exit code 5
```

### Docker Driver
docker for mac Version 17.07.0-ce-rc2-mac22 (18909)

### Sync strategy
rsync

### your docker-sync.yml
```
version: "2"

globals:
  update-check: false

syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  app-rsync-sync: #tip: add -sync and you keep consistent names als a convention
    src: '~/server/default/deploy/myapp.ear/'
    dest: '/usr/local/EnterprisePlatform-5.2.0/jboss-eap-5.2/jboss-as/server/default/deploy/myapp.ear/'
    sync_host_ip: 'localhost'
    sync_host_port: 10872
```

### OS
OSX 10.2.6 Sierra
