### ISSUE TITLE
app_sync mysteriously gets owned by userid 82

### ISSUE THREAD

**Issue by tomfriedhof** [EugenMayer/docker-sync#453]
I'm running into permissions issues with Unison.  The `app_sync` directory mysteriously gets owned by user `82`.  Not sure what is triggering that. 

Here is my docker-sync.yml:
```
syncs:
  docker-sync: # tip: add -sync and you keep consistent names as a convention
    src: './'
    sync_host_ip: 'auto'
    sync_userid: 33
    sync_groupid: '33'
    sync_strategy: 'native_osx'
```
I can fix the unison permissions issue by manually logging into the sync container and chown back to the `xfs` user.
