### ISSUE TITLE
depends_on not respected

### ISSUE THREAD

**Issue by ain** [EugenMayer/docker-sync#455]
### Error/Feature Requestion/Docs
Whenever using `docker-sync-stack start` it behaves differently from `docker-compose up -d` in the way it treats the order to start up services. 

### Docker Driver
d4m

### Sync strategy
native_osx

### your docker-sync.yml
```yaml
version: '2'
options:
  verbose: true
syncs:
  app-source:
    src: '.'
    #sync_strategy: 'unison'
    notify_terminal: true
    sync_excludes: ['log/', 'tmp/cache']
    sync_args:
      - "-prefer newer"
      - "-ignore='Path .git'"
      - "-ignore='BelowPath .git'"
```

### OS
macOS
