### ISSUE TITLE
undefined method `check_all_preconditions' for nil:NilClass on Windows 10 with Unison

### ISSUE THREAD

**Issue by ctessier** [EugenMayer/docker-sync#456]
Hi,

I am encountering the following error while running `docker-sync start` for the first time.

```bash
$ docker-sync start
Le chemin d’accès spécifié est introuvable.
       error  undefined method `check_all_preconditions' for nil:NilClass
Did you mean?  check_signedness
```

### Docker Driver
I am on Windows 10, using Docker Toolbox with Virtualbox.

### Sync strategy
I have Unison on Windows (version 2.48.4)

### your docker-sync.yml

```yml
version: "2"

options:
  verbose: true
  max-attempt: 30
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  app-unison-sync: # tip: add -sync and you keep consistent names as a convention
    src: './'
    sync_strategy: 'unison'
    sync_excludes: ['.idea/*', '.git/*']
```

### OS
Windows 10
