### ISSUE TITLE
Running 2 containers with docker-sync ends up projects erasing each other

### ISSUE THREAD

**Issue by godbout** [EugenMayer/docker-sync#457]
### Error/Feature Requestion/Docs
When I was running one container it worked well. Now I have another project running in a container. For whatever reason, the first container is pushing the source code of the project into the folder of my second project.

I've tried after erasing all the containers (app and sync), but the output is still the same.

Maybe I'm missing something? I haven't found a way to configure the app_sync and host_sync names if this is the issue?

It might just be something that I don't understand in how docker-sync works. If it is just let me know and I'll search more.

### Docker Driver
docker machine Version 17.06.1-ce-mac24 (18950)

### Sync strategy
native_osx

#### vb project

docker-compose
````
version: '3'

services:
  vb:
    image: godbout/redhead
    container_name: vb
    ports:
      - "8082:80"
      - "33062:3306"
    volumes:
      - ~/Dropbox/Development/vocabulary-builder/source:/srv/www/vb/public_html
      - dbdata-redhead:/var/lib/mysql

volumes:
  dbdata-redhead:
    external: true
````

docker-compose-dev
````
version: '3'

services:
  vb:
    volumes:
      - vb_sync:/srv/www/vb/public_html:nocopy
volumes:
    vb_sync:
        external: true
    dbdata-ums:
        external: true

````

docker-sync
````
version: '2'

options:
  compose-file-path: 'docker-compose.yml'
  compose-dev-file-path: 'docker-compose-dev.yml'
  verbose: true

syncs:
  vb_sync:
    notify_terminal: true
    src: '~/Dropbox/Development/vocabulary-builder/source'
    sync_strategy: 'native_osx'
    sync_excludes: ['.git']
    sync_userid: '1000'
````

#### hq project

docker-compose
````
version: '3'

services:
  hq:
    image: godbout/redhead
    container_name: hq
    ports:
      - "8081:80"
      - "33061:3306"
    volumes:
      - ~/Dropbox/Development/Sleeplessmind\ Ltd./hq:/srv/www/hq/public_html
      - dbdata-redhead:/var/lib/mysql

volumes:
  dbdata-redhead:
    external: true
````

docker-compose-dev
````
version: '3'
services:
    hq:
        volumes:
            - hq_sync:/srv/www/hq/public_html:nocopy
volumes:
    hq_sync:
        external: true
    dbdata-ums:
        external: true
````

docker-sync
````
version: '2'

options:
  compose-file-path: 'docker-compose.yml'
  compose-dev-file-path: 'docker-compose-dev.yml'
  verbose: true

syncs:
  hq_sync:
    notify_terminal: true
    src: '~/Dropbox/Development/Sleeplessmind\ Ltd./hq'
    sync_strategy: 'native_osx'
    sync_excludes: ['.git']
    sync_userid: '1000'
````

### OS
OSX 10.12.6 (16G29)
