### ISSUE TITLE
When deprecated `sync-user` param is defined, native_osx strategy raises exception

### ISSUE THREAD

**Issue by Siprah** [EugenMayer/docker-sync#460]
### Error/Feature Requestion/Docs

```shell
--- myproject/docker ‹master* M› » docker-sync start
          ok  Starting native_osx for sync web-sync
/Users/siper/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/native_osx.rb:49:in `raise': exception class/object expected (TypeError)
	from /Users/siper/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/native_osx.rb:49:in `start_container'
	from /Users/siper/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_process.rb:107:in `start_container'
	from /Users/siper/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:92:in `block in start_container'
	from /Users/siper/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:91:in `each'
	from /Users/siper/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:91:in `start_container'
	from /Users/siper/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:166:in `daemonize'
	from /Users/siper/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:48:in `start'
	from /Users/siper/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/siper/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/siper/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/siper/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/siper/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/docker-sync-0.4.6/bin/docker-sync:14:in `<top (required)>'
	from /Users/siper/.rbenv/versions/2.4.0/bin/docker-sync:22:in `load'
	from /Users/siper/.rbenv/versions/2.4.0/bin/docker-sync:22:in `<main>'
```

### Docker Driver
d4m

### Sync strategy
native_osx

### OS
macOS Sierra

### Details
```yaml
version: "2"

options:
  verbose: true
syncs:
  web-sync:
    src: '../web'
    sync_strategy: 'native_osx'
    sync_host_port: 10875
    sync_user: 'www-data'
    sync_userid: '33'
    sync_args: '-prefer newer -copyonconflict'
    sync_excludes:
      - .docker
      - .git
      - .gitignore
```
I found very weird bug, when I have defined `sync_user` key in my config, the exception is raised by native_osx strategy. After I delete it (it's deprecated, I know), everything works fine. It happens only on `native_osx` strategy.

In my opinion, it should:
- Show more human-like error, without code looking to check what's going on.
OR
- Ignore a problem, with warning about deprecated key.
