### ISSUE TITLE
Files not sync in containers created using `docker-compose run`

### ISSUE THREAD

**Issue by zedtux** [EugenMayer/docker-sync#466]
### Error/Feature Requestion/Docs
I have my entire set of applications working, with the file synchronisation working too.
I'm now trying to run a command using `docker-compose run --rm <container-name> <command>` but in this case I'm missing files while with `docker-compose exec <container-name> <command>` it's working fine.

I don't remember having read anything in the documentation about this case so that why I'm opening this issue.

### Docker Driver
d4m

### Sync strategy
default

### your docker-sync.yml

```yaml
# Find the documentation at https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration
version: "2"

options:
  # optional, activate this if you need to debug something, default is false
  # IMPORTANT: do not run stable with this, it creates a memory leak, turn off verbose when you are done testing
  verbose: false

syncs:
  app-sync:
    src: './my-application'
    sync_excludes: ['.git']
```

### OS

macOS 10.12.6
