### ISSUE TITLE
Sync Excludes Issues

### ISSUE THREAD

**Issue by hillmandj** [EugenMayer/docker-sync#468]
### Error/Feature Requestion/Docs

I've seen numerous issues commenting on inconsistent behavior with respect to `sync_excludes`. I've looked at the boilerplate, ran docker-sync clean, completely destroyed my sync volumes and recreated them again, basically tried everything under the sun to try to stop docker-sync from syncing files I don't intend it to. 

If I'm doing something blatantly wrong I apologize, but as you can see it is still syncing my *.swp files:

```
          ok  Starting native_osx for sync casper-code-sync
Contacting server...
Looking for changes
Reconciling changes
Propagating updates
UNISON 2.48.4 started propagating changes at 14:06:00.79 on 04 Oct 2017
[CONFLICT] Skipping .docker-sync/daemon.log
  contents changed on both sides
[CONFLICT] Skipping log/development.log
  contents changed on both sides
[CONFLICT] Skipping log/newrelic_agent.log
  contents changed on both sides
[BGN] Copying .docker-sync/daemon.pid from /app_sync to /host_sync
[END] Copying .docker-sync/daemon.pid
[BGN] Copying .env.swp from /app_sync to /host_sync
[END] Copying .env.swp
[BGN] Copying .gitignore.swp from /app_sync to /host_sync
[END] Copying .gitignore.swp
[BGN] Copying db/migrate/.20170918172312_create_recycling_fee_product.rb.swp from /app_sync to /host_sync
[END] Copying db/migrate/.20170918172312_create_recycling_fee_product.rb.swp
```

### Docker Driver
Docker for Mac

### Sync strategy
native_osx

### your docker-sync.yml
```
options:
  verbose: false
  compose-file-path: ./docker-compose.yml
  compose-dev-file-path: ./docker-compose.yml
  max_attempts: 5

syncs:
  casper-code-sync:
    src: .
    sync_excludes: ['.git', '*.swp', '.gitignore', 'tmp']
    watch_args: '-v'
```
### OS
OSX Sierra 10.12.6
