### ISSUE TITLE
Prefer parameter on unison strategy does not work

### ISSUE THREAD

**Issue by jerome-arzel** [EugenMayer/docker-sync#476]
### Error
Prefer parameter on unison strategy does not work with 'dest' value.

### Sync strategy
unison

### your docker-sync.yml
```
version: '2'
options:
  verbose: false
syncs:
  project-sync:
    src: '../project'
    sync_strategy: 'unison'
    sync_prefer: 'dest'
    watch_strategy: 'dummy'

```

### OS
OSX Sierra 10.12.6

### Pull Request

#475
