### ISSUE TITLE
Docker-Sync not working?

### ISSUE THREAD

**Issue by qweluke** [EugenMayer/docker-sync#479]
I am using MacOS 10.13 and native_osx with:

```
-> % docker-sync --version && docker-compose --version && docker --version
0.4.6
docker-compose version 1.16.1, build 6d1ac21
Docker version 17.09.0-ce, build afdb6d4
```
The problem is that the peage loads very very long, about 10seconds so I suppose sync is not working.. Can you tell me why? Maybe i've messed a configuration files?
Of course before I start my docker, I have executed
`docker-sync clean && docker-sync start` to clear the cache container and start it again.
Right after it, i am running `docker-sync-stack start`

```
#docker-compose.yml
version: '2'
services:
    db:
        image: mysql:5.7
        container_name: ${APP_NAME}_mysql
        ports:
            - 3300:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: php7-fpm
        container_name: ${APP_NAME}_php
        links:
            - db:mysqldb
        volumes:
            - "./php7-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
    nginx:
        build: nginx
        container_name: ${APP_NAME}_nginx
        ports:
            - 86:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
```

```
#docker-sync.yml
version: "2"
options:
  verbose: true
syncs:
  supersync-sync:
    src: ${SYMFONY_APP_PATH}
    sync_excludes: ['var/cache', 'var/logs', '.idea', 'var/sessions']
    sync_strategy: 'native_osx' #for macos
    sync_excludes_type: 'Path'
```
```

#docker-compose-dev.yml
version: '2'
services:
    php:
        volumes:
            - supersync-sync:/var/www/symfony:nocopy

volumes:
  supersync-sync:
    external: true

```

and the `.env` file

```
# Symfony application's path (absolute or relative)
SYMFONY_APP_PATH=./project

# MySQL
MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=greif
MYSQL_USER=root
MYSQL_PASSWORD=root

# Timezone
TIMEZONE=Europe/Paris
APP_NAME=supersync

```
