### ISSUE TITLE
No implicit conversion of String into Integer

### ISSUE THREAD

**Issue by tripox** [EugenMayer/docker-sync#482]
### Error

Getting the following error after installing 0.5.0-beta1:

```sh
error  no implicit conversion of String into Integer
```

This error appears on `docker-sync start` and `docker-sync stop`.

### Docker Driver
Docker for Mac

### Sync strategy
native_osx / default

### docker-sync.yml
```yml
version: "2"

options:
  verbose: true

syncs:
  bbs-webroot-sync:
    src: './web'
  bbs-vendor-sync:
    src: './vendor'
```

### OS
MacOS High Sierra 10.13 (17A405)
