### ISSUE TITLE
Incorrect username and password error

### ISSUE THREAD

**Issue by albertski** [EugenMayer/docker-sync#483]
### Error/Feature Requestion/Docs
When I run `docker-sync-stack start` I get the following response:

```
       note:  You can also run docker-sync in the background with docker-sync --daemon
Error response from daemon: Get https://registry-1.docker.io/v2/eugenmayer/unison/manifests/hostsync_0.2: unauthorized: incorrect username or password
Error response from daemon: Get https://registry-1.docker.io/v2/eugenmayer/unison/manifests/hostsync_0.2: unauthorized: incorrect username or password
```

### your docker-sync.yml
```
version: "2"

options:
  verbose: true
syncs:
  mysite-sync: # tip: add -sync and you keep consistent names as a convention
    src: '.'
    sync_userid: '82'
    # sync_strategy: 'native_osx' # not needed, this is the default now
    sync_excludes: ['.gitignore', '.git/', '.idea/']
```

### OS
OSX Sierra

**Comment by tripox** [comment]
Hey @albertski. 

There's currently a bug in 0.4.6 which results in docker-sync choosing the unison sync strategy even if you're running Docker for Mac (on the edge channel), please see #477. 

The unison strategy seems to be broken too.

There's several ways to fix this:
- Install Docker for Mac stable
- Set `native_osx` as the sync strategy in your `docker-sync.yml` file
- Clone `git@github.com:EugenMayer/docker-sync.git`, checkout `03cfce5a3059d4eef119c61e7c01ca7ba25bff76` and run the script `deploy_locally.sh`

**Comment by albertski** [comment]
Trying the set `native_osx` route but it didn't work.

```
version: "2"

options:
  verbose: true
syncs:
  mysite-sync: # tip: add -sync and you keep consistent names as a convention
    src: '.'
    sync_strategy: 'native_osx'
    sync_userid: '82'
    sync_uid: '82'
    sync_excludes: ['.gitignore', '.git/', '.idea/']
```
