### ISSUE TITLE
Services not able to access files within sync'd directory

### ISSUE THREAD

**Issue by tenpaiyomi** [EugenMayer/docker-sync#489]
### Error
When using docker-sync (0.4.6) and starting my containers, it appears as if services cannot access information within the synced folder.  For instance, using the below configuration for an nginx/rails based container, nginx will fail to start with the error:

```
web_1    | App 39 stderr: Rails Error: Unable to access log file. Please ensure that /signage/log/development.log exists and is chmod 0666. The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
```

Looking at the folder in the container, I note that everything is owned by 999:999.  If I set a sync_userid of 999, the result is the same.  Going back to my standard volume mount of `- ./app:/signage` results in everything working as expected.

### Docker Driver
d4m

### Sync strategy
default

### your docker-sync.yml
```
version: "2"

options:
  verbose: true
syncs:
  signage-sync:
    src: './app'
```

### applicable docker-compose.yml snippet
```
volumes:
  bundle-data:
  signage-sync:
      external: true

...

    volumes:
      - signage-sync:/signage:nocopy
      - ./app/config/env/.env.${APP_ENV}:/signage/.env
      - ./stack/ec2/signage/nginx/${APP_ENV}.nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - bundle-data:/bundle
```

### OS
macOS 10.12.6
