### ISSUE TITLE
Sync Deletes Previous Folder Contents doesnt use sync_excludes

### ISSUE THREAD

**Issue by b1alpha** [EugenMayer/docker-sync#498]
### Error
Initial state of /var/www is not respected. The folder node_modules and all other files are deleted and only the local folder to be synced with the container exist now in the container

#### Desired
The /var/www folder has the node_modules originally from the docker image

#### Actual
Every file in /var/www is deleted, then only the localhost files are in /var/www

#### More Info
* If I start with docker compose is see node_modules, vendor ect
* If I start with docker-sync I see nothing but what is in my ./ 
* If I specify excludes, they do not seem to effect the total overwrite of /var/www
* If I set the sync `src: '.'`  then the folder is put into /var/www/folder and still /var/www every file is gone

Is this behavior intended and how can I avoid deleting excluded files?

### Docker Driver
d4m 

### Sync strategy
rsync

### your docker-sync.yml
```
version: "2"
options:
  verbose: true
syncs:
  appcode-rsync-sync:
    src: './'
    sync_host_ip: 'auto'
    sync_host_port: 10874
    sync_strategy: 'rsync'
    sync_excludes: [ 'vendor/', 'node_modules/', 'public/js/bower_components/']
```
### OS
OSX 10.13.1
