### ISSUE TITLE
Generated files from gulp (node-sass) will be not synced.

### ISSUE THREAD

**Issue by beardcoder** [EugenMayer/docker-sync#503]
### Error
Generated files from gulp will be not synced.
The files will be created from the node-sass implementation. See https://github.com/beardcoder/frontend-kickstart

### Docker Driver
Docker: Docker for Mac Version 17.11.0-ce-rc4-mac39 (20423)

### Sync strategy
Unison

### your docker-sync.yml

```
version: "2"
options:
  compose-file-path: 'docker-compose.yaml'

syncs:
  #IMPORTANT: ensure this name is unique and does not match your other container names
  ${APP_HOST}-sync:
    src: './app'
    sync_excludes: ['.git', 'Temporary', 'Logs', '.idea']
    sync_userid: '1000'
    sync_strategy: 'unison'
```

### OS
MacOS 10.13
