### ISSUE TITLE
random files not syncing 

### ISSUE THREAD

**Issue by b1alpha** [EugenMayer/docker-sync#506]
### Error
Some files sync, others do not. No errors in the sync log. Files just not syncing right off the bat, then not picking up changes on host. 

Tried `docker-sync sync` no change

### Docker Driver
d4m 

### Sync strategy
native_osx

### your docker-sync.yml
```
--- 
options: 
  verbose: true
syncs: 
  appcode-native-sync: 
    src: ./
    sync_excludes: 
      - public/js/bower_components
      - node_modules
      - vendor
    sync_host_ip: auto
    sync_host_port: 10872
    sync_strategy: native_osx
version: "2"
```

### OS
OSX Version 10.13.1
