### ISSUE TITLE
Docker Compose 1.17 fixed volumes override

### ISSUE THREAD

**Issue by michaelbaudino** [EugenMayer/docker-sync#507]
I would like to notify everyone here that Docker Compose [just fixed](https://github.com/docker/compose/pull/5223) a bug where [we could not override volumes with different modes](https://github.com/docker/compose/issues/5203). The fixed was released as part of version `1.17`.

It's particularly useful to us (DockerSync users) because it will let us properly use the default (DockerSync-free) configuration in `docker-compose.yml`:

```yaml
services:
  your_app:
    volumes:
      - .:/app
```

And just put the DockerSync-specific stuff in another Docker Compose file (_e.g._ `docker-compose.override.yml` because it's automatically used when it exists):

```yaml
volumes:
  - your_app-sync: { external: true }

services:
  your_app:
    volumes:
      - your_app-sync:/app:nocopy
```

To be explicit: this configuration was failing prior to the above bugfix because of the `:nocopy` mode which was preventing a proper override.

It means that DockerSync users can have their DockerSync configuration isolated (_e.g._ in afile ignored by git), and thus stop messing with the project configuration that could have been used by non-DockerSync users too.

DockerSync and not-DockerSync users shall now leave at peace again ❤️ 🕊 (even when working on the same project 🙏).

PS : should we document this somewhere? It looks to me that it should be a best practice (and probably even the default way to configure DockerSync).

PS2: TL;DR DockerCompose upgrade command: 

```shell
curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```
