### ISSUE TITLE
`<class:GlobalConfig>': uninitialized constant DockerSync::GlobalConfig::DateTime (NameError)

### ISSUE THREAD

**Issue by facine** [EugenMayer/docker-sync#509]
I get this error trying to use docker-sync.

### Error/Feature Requestion/Docs

```
$docker-sync-stack start
/Users/facine/.rvm/gems/ruby-2.4.2/gems/docker-sync-0.5.1/lib/docker-sync/config/global_config.rb:15:in `<class:GlobalConfig>': uninitialized constant DockerSync::GlobalConfig::DateTime (NameError)
	from /Users/facine/.rvm/gems/ruby-2.4.2/gems/docker-sync-0.5.1/lib/docker-sync/config/global_config.rb:8:in `<module:DockerSync>'
	from /Users/facine/.rvm/gems/ruby-2.4.2/gems/docker-sync-0.5.1/lib/docker-sync/config/global_config.rb:7:in `<top (required)>'
	from /Users/facine/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/facine/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/facine/.rvm/gems/ruby-2.4.2/gems/docker-sync-0.5.1/lib/docker-sync/update_check.rb:3:in `<top (required)>'
	from /Users/facine/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/facine/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/facine/.rvm/gems/ruby-2.4.2/gems/docker-sync-0.5.1/bin/docker-sync-stack:7:in `<top (required)>'
	from /Users/facine/.rvm/gems/ruby-2.4.2/bin/docker-sync-stack:23:in `load'
	from /Users/facine/.rvm/gems/ruby-2.4.2/bin/docker-sync-stack:23:in `<main>'
	from /Users/facine/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/facine/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

### Docker Driver
docker-machine

### Sync strategy
native_osx

### your docker-sync.yml
```
version: 2
options:
  compose-file-path: docker-compose.yml
syncs:
  docker-project-html-sync:
    src: ../
    sync_userid: 3000
    sync_host_port: 10872
    sync_excludes: ['docker', '.idea', '.DS_Store']
```

### OS
macOS High Sierra (10.13.1)
