### ISSUE TITLE
Troubleshooting docker sync on high sierra

### ISSUE THREAD

**Issue by rodrigoaguilera** [EugenMayer/docker-sync#515]
### Error
After around 10-20 simple edits of files in the host docker sync stops syncing from the host to the container. If I edit files inside the container the sync works.
It seems that somehow it stops listening.
I tried text editors and command line utils to change files.

### Docker Driver
d4m Docker Community Edition 17.12.0-ce-rc3-mac43 2017-12-15 (Edge)

### Sync strategy
native_osx

### your docker-sync.yml
```
version: "2"

syncs:
  # IMPORTANT: this name must be unique and should NOT match your real application container name!
  myapp-sync:
    src: './'
    sync_userid: '33'
```
### OS
OSX 10.13.1 (updating now to 10.13.2)

### More info

docker-sync 0.5.2

We have 3 mac systems using docker-sync successfully with the exact same app even on edge.
The difference is that this one uses High Sierra with APFS.

I look at the unison logs and it seems like no notifications for filesystem changes are happening
I am just looking for a way to troublehoot this further. Any hints?

PD: we use edge because of this one:
https://github.com/docker/for-mac/issues/668#issuecomment-351002066

**Comment by EugenMayer** [comment]
does it work better with stable? or the other way around, is this a AFPS issue or an edge to issue

**Comment by nickdani** [comment]
I'm facing the same problem after update to `0.5.2`. Before the update, it had been working perfectly, after update to `0.5.2` the sync stopped working at all


**Docker**
Docker version 17.06.0-ce, build 02c1d87

**Docker compose**
docker-compose version 1.14.0, build c7bdf9e

**Docker sync**
0.5.2

**Mac os**
Sierra 10.12.4

**Sync strategy**
native_osx

any suggestions?

**Comment by rodrigoaguilera** [comment]
@nickdani I am using your versions exactly and I didn't experience any problems.

Can you confirm that the sync works for some modifications after you run docker-sync-stack start and then it stops in only one of the directions (edits on host are not reflected). Just to know if we are talking about the same issues.

In your case I would try a complete docker-compose rm && docker-sync clean (in my case it didn't help)

@EugenMayer I will only have access to that laptop with high sierra after the 10th of January

**Comment by nickdani** [comment]
@rodrigoaguilera 

> In your case I would try a complete docker-compose rm && docker-sync clean (in my case it didn't help)

didn't help

actually in my case sync does not work at all :(

**Comment by hectorsabina** [comment]
I'm experiencing the same issue. I always run docker-sync with the `--foreground` flag, and it stops loging any sync task after some time. It does work for a few syncs but then it stops working.

**Docker**
Docker version 17.12.0-ce-rc3 (edge)

**Docker compose**
docker-compose version 1.18.0-rc2

**Docker sync version**
0.5.2

**Mac OS**
Sierra 10.12.6

**Sync strategy**
native_osx

**docker-sync.yml**
```
version: '2'

options:
  verbose: true

syncs:
  webapp-sync:
    src: './'
    # native_osx as the sync strategy
    sync_strategy: 'native_osx'
    # this will assign ownership and group of the synced files to 'www-data' in webapp container
    sync_userid: '33'
    sync_groupid: '33'
    # this should exclude some files from being synced at all, increasing perfomance
    sync_args:
      - "-ignore='Path .idea'"              # no need to send PHPStorm config to container
      - "-ignore='Path .git'"               # ignore the main .git repo control files
      - "-ignore='BelowPath .git'"          # also ignore .git repos in subfolders such as in composer vendor dirs
      - "-ignore='BelowPath app/cache/*'"   # don't sync cache
      - "-ignore='BelowPath app/logs/*'"    # don't sync logs
      - "-ignore='Path .docker-sync'"       # don't sync this
      - "-ignore='Name .gitignore'"
      - "-ignore='Name .DS_Store'"
```
