### ISSUE TITLE
Sync strategy on MacOS

### ISSUE THREAD

**Issue by mnabialek** [EugenMayer/docker-sync#516]
I'm using High Sierra.

my docker-sync.yaml looks like this:

```
version: "2"

options:
    compose-dev-file-path: 'docker-compose.yml'	

syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  test-sync: #tip: add -sync and you keep consistent names as a convention
    src: './html'
    sync_strategy: 'native_osx'
```

When started in console I'm getting:

> [2017-12-28 20:46:20 +0100] Sync Log:  UNISON 2.48.4 started propagating changes at 19:46:22.82 on 28 Dec 2017
> [2017-12-28 20:46:20 +0100] Sync Log:  [BGN] Updating file .git/index from /host_sync to /app_sync
> [2017-12-28 20:46:20 +0100] Sync Log:  [END] Updating file .git/index

My question is - is docker-sync using here `native_osx` strategy or maybe it somehow ignores it because in log there is `UNISON`?
