### ISSUE TITLE
Docker-sync slow load speed after deep sleep modus Mac

### ISSUE THREAD

**Issue by DirkWolthuis** [EugenMayer/docker-sync#524]
### **Error**/Feature Requestion/Docs
Error

So, we are developing a Laravel app, and without docker-sync I have a high boot time: 1 to 2 seconds. With docker-sync I have a boot time of 300 - 500 ms. So yeah! But here is the problem: after I leave my Mac in sleep modus for the night the boottime goes up to 800ms - 1s. Restart docker-sync and/or the containers does not help. I need to restart the docker deamon to get my 300ms boot time back. Is this a docker-sync problem or a docker problem and does anyone know how to fix this? The same project works flawless on my colleagues linux system. 

### Docker Driver
D4M

### Sync strategy
Native_osx (although it looks like Unison containers are created when running docker-sync, I think this is okay?)

### your docker-sync.yml
```
version: '3'
services:
  port_nginx:
    expose:
      - 9001
    build:
      context: ./
      dockerfile: deploy/port_nginx.docker
    volumes:
      - port_nginx-sync:/var/www:nocopy 
    ports:
      - "80:80"
    depends_on:
      - mailhog
      - portal
      - openerp
    links:
      - openerp
      - jts
    environment:
      - XDEBUG_CONFIG="remote_host=xxx"
      - PHP_IDE_CONFIG="serverName=xxx"
    networks:
      mynet:
        ipv4_address: xxx
  portal:
    build:
      context: ./
      dockerfile: deploy/portal.docker
    volumes:
      - port_nginx-sync:/var/www:nocopy 
    depends_on:
      - port_mysql
      - cache
      - openerp
    links:
      - postgres
      - openerp
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=port_mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=cache"
    networks:
      mynet:
        ipv4_address: xxx
  jts:
    build:
      context: ./
      dockerfile: deploy/jts.docker
    depends_on:
      - openerp
    links:
      - postgres
      - openerp
    volumes:
      - ./src/jts:/var/www/html
    ports:
      - "81:80"
    environment:
      - XDEBUG_CONFIG="remote_host=xxx"
      - PHP_IDE_CONFIG="serverName=xxx"
    networks:
      mynet:
        ipv4_address: xxx
  postgres:
    image: postgres:9.5
    volumes:
      - postgres-sync:/var/lib/postgresql/data/db-files:nocopy
    environment:
      POSTGRES_PASSWORD: xxx
      POSTGRES_USER: xxx
      POSTGRES_DB: xxx
      PGDATA: xxx
    ports:
      - "8084:5432"
    networks:
      mynet:
        ipv4_address: xxx
  openerp:
    build:
      context: ./
      dockerfile: deploy/openerp5.docker
    ports:
      - "8069:8069"
      - "8070:8070"
    depends_on:
      - postgres
    networks:
      mynet:
        ipv4_address: xxx
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    depends_on:
      - port_mysql
    ports:
      - "8082:80"
    volumes:
      - /sessions
    networks:
      mynet:
        ipv4_address: xxx
  port_mysql:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=x"
      - "MYSQL_DATABASE=x"
      - "MYSQL_USER=x"
      - "MYSQL_PASSWORD=x"
    volumes:
      - mysql-sync:/var/lib/mysql:nocopy
    ports:
      - "33061:3306"
    networks:
      mynet:
        ipv4_address: xxx
  cache:
    image: redis:3.0
    ports:
      - "8086:6379"
    networks:
      mynet:
        ipv4_address: xxx
  mailhog:
    image: mailhog/mailhog:latest
    container_name: adc-portal-mailhog
    ports:
      - "8083:8025"
    networks:
      mynet:
        ipv4_address: xxx

volumes:
  port_nginx-sync:
    external: true
  postgres-sync:
    external: true
  mysql-sync:
    external: true

networks:
  mynet:
    driver: bridge
    ipam:
      config:
      - subnet: xxx
```
### docker-sync.yml

```
version: "2"

options:
  verbose: true
syncs:
  port_nginx-sync:
    sync_userid: '33'
    sync_groupid: '33'
    src: './src'
  postgres-sync:
    src: './data/pgsql'
    sync_userid: '999'
    sync_groupid: '999'
  mysql-sync:
    src: './data/mysql'
    sync_userid: '999'
    sync_groupid: '999'
```
### OS
OSX 10.13.2
