### ISSUE TITLE
Does native_oxs support sync_excludes and watch_excludes?

### ISSUE THREAD

**Issue by Redsandro** [EugenMayer/docker-sync#528]
### Error/Feature Requestion/Docs

I'm a Linux user, but I'm trying to make a `docker-compose` config that works for my OSX colleagues for a big Symfony project that runs approximately at native speed on Linux, but is about 100005.25 times slower on OSX. The internet recommends `docker-sync`.

However, it's syncing caches and other stuff I want to keep out of the bottleneck all the time. I'm using the exclusion keys as found in the [configuration reference](https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration#this-is-a-configuration-reference---do-not-use-all-options-at-once---they-do-not-make-sense-or-copy-them-as-your-starting-point-rather-use-the-docker-sync-boilerplate-and-then-cherry-pick-the-options-you-need) but everything seems to be synced anyway, according to `docker-sync logs`.

### Docker Driver

d4m

### Sync strategy

`native_osx`

### your docker-sync.yml

```
version: '2'
options:
    compose-file-path: docker-compose-sync.yml
    verbose: true
syncs:
    mastershare:
        src: './src'
        sync_strategy: native_osx
        notify_terminal: true
        sync_host_port: 10871
        sync_userid: 1000
        sync_excludes:
            - node_modules
            - vendor
            - cache
            - var/cache
        watch_excludes:
            - .*/node_modules
            - .*/vendor
            - .*/cache
            - .*/var/cache
            - .*/.git
```

### OS

OSX High Sierra

**Comment by EugenMayer** [comment]
sync_excludes is supported
watch_excludes is not supported by native_osx .. i created a hint the on the configuration page of native_osx .

read http://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html#ignore to understand how excludes work

**Comment by Redsandro** [comment]
@EugenMayer does that mean that in case of e.g.

```
sync_excludes:
            - cache
```

the local `cache` __will not__ be initially synced to the `guest`, but once it's created on the `guest` it __will__ be synced to the `host`? Because unless the above configuration is wrong, that is the behavior I'm observing.

Would mounting a volume over a subdirectory from `docker-sync` prevent it from being synced?

```
volumes:
    - docker_sync:/data
    - type: tmpfs
      target: /data/vendor
```
