### ISSUE TITLE
Some files are not synced on restart of docker-sync

### ISSUE THREAD

**Issue by virtser** [EugenMayer/docker-sync#529]
### Error/Feature Requestion/Docs
On the second run of docker-sync `docker-sync-stack start` a changed Gemfile won't be copied, as a result new gems won't be installed and the rails server will fail to load.

### Docker Driver
Docker mac - Version 17.12.0-ce-mac49 (21995)

### Sync strategy
default -> native_osx/unison

```
> docker-sync-stack start

       note:  You can also run docker-sync in the background with docker-sync start
          ok  Starting native_osx for sync app-sync
doing initial sync with cp
Contacting server...
Looking for changes
Reconciling changes
Propagating updates
UNISON 2.48.4 started propagating changes at 15:42:12.51 on 07 Feb 2018
```

### your docker-sync.yml

```
# http://docker-sync.io/
# https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration
version: "2"

options:
  verbose: false
  # compose-force-build: true

syncs:
  app-sync:
    src: './'
    notify_terminal: true
    sync_excludes: ['docker-*.yml', 'npm-debug*.log', 'node_modules', '.gitignore', '.git', '.semaphore-cache', 'log', 'tmp', '.ruby-gemset', '*.sql', 'coverage', '.bundle', 'bundle', 'vendor/bundle', 'data']
    watch_excludes: ['.*/.git', '.*/node_modules', '.gitignore']
    watch_args: '-v' # make watching verbose
    monit_enabled: true
    monit_interval: 5
```
### OS
macOS High Sierra
