### ISSUE TITLE
First sync worked, subsequent not working

### ISSUE THREAD

**Issue by aledalgrande** [EugenMayer/docker-sync#530]
### Error

First sync worked, subsequent changes not propagating. I can see it running and logging:
```
UNISON 2.48.4 started propagating changes at 10:32:23.36 on 09 Feb 2018
[BGN] Updating file .docker-sync/daemon.log from /Users/xxx to //7971c1b47859//app_sync
Failed: The source file /Users/xxx/.docker-sync/daemon.log
has been modified during synchronization.  Transfer aborted.
UNISON 2.48.4 finished propagating changes at 10:32:23.37 on 09 Feb 2018
Saving synchronizer state
Synchronization incomplete at 10:32:23  (0 items transferred, 0 skipped, 1 failed)
  failed: .docker-sync/daemon.log
Looking for changes
  Waiting for changes from server
Reconciling changes
Nothing to do: replicas have not changed since last sync.
```

### Docker Driver

d4m 17.12.0-ce-mac49 (21995)

### Sync strategy

unison

### your docker-sync.yml

```yaml
version: '2'
syncs:
  project_volume_sync:
    src: '.'
    sync_excludes: ['node_modules/**/*', 'bower_components/**/*', '*.log', 'tmp/*', '.git']
    sync_strategy: 'unison'
    watch_excludes: ['node_modules/**/*', 'bower_components/**/*', '*.log', 'tmp/*', '.git']
```

### OS

OS X 10.13 (17A365)
