### ISSUE TITLE
Max attempts not respected in 0.5.7

### ISSUE THREAD

**Issue by Johnzzon** [EugenMayer/docker-sync#537]
### Error
After upgrading to 0.5.3 the `start` command fails after 5 seconds even though my config is set to 30. (have tried `clean` as well)
`Failed to start unison container in time, try to increase max_attempt (currently 5)`
Downgrading back to 0.5.2 solves the issue.

### Docker Driver
d4m

### Sync strategy
unison

### your docker-sync.yml
```
version: '2'

options:
  verbose: true
  max-attempts: 30

syncs:
  docker-sync:
    src: './src'
    sync_args: '-prefer newer'
    sync_userid: '33'
    sync_strategy: 'unison'
```

### OS
macOS High Sierra 10.13.3

**Comment by EugenMayer** [comment]
must be related to the new unison image i suppose, thanks for reporting

**Comment by pajon** [comment]
There is problem with ENV variables, missing **UNISON_** prefix

**Comment by EugenMayer** [comment]
that was the actual cause https://github.com/EugenMayer/docker-sync/pull/475 breaking unison completely..

i was bearing with the PR for so many months, taken it in finally and blew it up like my gut feeling was already telling me. I will revert it and release 0.5.4 ASAP

**Comment by EugenMayer** [comment]
released 0.5.4 , fixes this issue

**Comment by thisisablock** [comment]
@EugenMayer its back on 0.5.7 and mac OSX 10.13.4

## Error
Updated clean to 0.5.7. Removed all versions locally.
Docker Version ist mac42. 

## Docker Driver
d4m

## Sync strategy
unison

## docker-sync.yml
````
version: "2"

options:
  max_attempt: 10
syncs:
  docker-sync:
    src: './'
    sync_strategy: 'unison'
    sync_excludes: ['.gitignore', '.git/', '.idea/']
```
### OS
macOS High Sierra 10.13.3
