### ISSUE TITLE
Failed to start unison container in time

### ISSUE THREAD

**Issue by adam-paterson** [EugenMayer/docker-sync#538]
### Error
After updating from `0.5.2` to `0.5.3` `docker-sync start` fails with the following:

```
ok  Starting unison for sync project-magento
          ok  project-magento container not running
          ok  starting project-magento container
     command  docker start project-magento && docker exec project-magento supervisorctl restart unison
          ok  starting initial sync of project-magento
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' project-magento
     command  unison -testserver /app_sync "socket://192.168.64.5:32774"
/Users/adampaterson/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.3/lib/docker-sync/sync_strategy/unison.rb:193:in `block in start_container': Failed to start unison container in time, try to increase max_attempt (currently 30) in your configuration. See https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration for more informations (RuntimeError)
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.3/lib/docker-sync/sync_strategy/unison.rb:188:in `loop'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.3/lib/docker-sync/sync_strategy/unison.rb:188:in `start_container'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.3/lib/docker-sync/sync_process.rb:105:in `start_container'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.3/lib/docker-sync/sync_manager.rb:99:in `block in start_container'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.3/lib/docker-sync/sync_manager.rb:98:in `each'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.3/lib/docker-sync/sync_manager.rb:98:in `start_container'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.3/tasks/sync/sync.thor:163:in `daemonize'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.3/tasks/sync/sync.thor:47:in `start'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648@global/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648@global/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648@global/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648@global/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648/gems/docker-sync-0.5.3/bin/docker-sync:14:in `<top (required)>'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648/bin/docker-sync:23:in `load'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648/bin/docker-sync:23:in `<main>'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /Users/adampaterson/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
```

### Docker Driver
- xhyve (https://github.com/zchee/docker-machine-driver-xhyve)

### Sync strategy
- Unison

### your docker-sync.yml
```
version: "2"

options:
  compose-file-path:
    - docker-compose-common.yml
    - docker-compose-dev.yml
  verbose: true
  max_attempt: 30

syncs:
  project-magento:
    notify_terminal: true
    src: '../../'
    sync_userid: 33
    sync_excludes:
      - .idea
      - .git
      - var/generation
      - var/composer_home
      - var/session
      - var/view_preprocessed
      - pub/static
      - var/.setup_cronjob_status
      - var/di
      - build/

  project-composer-cache:
    src: '~/.composer/cache'
    sync_userid: 33
```

### OS
- OSX 10.13.2
