### ISSUE TITLE
Infinite loop on checking for newer unison image

### ISSUE THREAD

**Issue by hyviquel** [EugenMayer/docker-sync#552]
### Error

I just updated docker-sync and now it's looping indefinitely on checking for newer unison image.
I removed my Docker.qcow2 and restarted docker just to be sure it wasn't because of old containers but I still have the same problem.

```
➜ ✗ docker-sync clean
          ok  Checking if a newer unison image is available
          ok  No newer image found - current image is up to date.
          ok  Checking if a newer unison image is available
          ok  No newer image found - current image is up to date.
          ok  Checking if a newer unison image is available
          ok  No newer image found - current image is up to date.
          ok  Checking if a newer unison image is available
          ok  No newer image found - current image is up to date.
          ok  Checking if a newer unison image is available
```

### Docker Driver
d4m Version 17.12.0-ce-mac55 (23011)

### Sync strategy
default

### your docker-sync.yml
```
version: "2"

options:
  verbose: true
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  llvm-sync: #tip: add -sync and you keep consistent names als a convention
    src: '~/Workspace/repos/llvm'
    sync_excludes: ['.DS_Store', '._*', '.git*', 'build', 'Inputs', '.arcconfig']
    sync_uid: 0 # the files should be own by root in the target cointainer
```

### OS
MacOS 10.13.3
