### ISSUE TITLE
Docker Sync not syncing my files in the backgroud

### ISSUE THREAD

**Issue by budby** [EugenMayer/docker-sync#556]
Mac OS X 10.13.3

I am running the commands: `docker-compose up --build -d`, `docker-sync start`. Entered edits in my source code, saved data. But data is not applied. If I run `docker-sync start again`, data will update.

What I am doing wrong?

docker-sync.yml
```
version: '2'

options:
    compose-file-path: docker-compose.yml
    verbose: true

syncs:
    php-fpm-web-sync:
        src: ${SYMFONY_WEB_PATH}
        sync_strategy: 'unison'
        sync_excludes: ['app/cache/', 'sass/.sass-cache/', 'sass/node_modules/', '.gitignore', '.git/', '.idea/']
    php-fpm-api-sync:
        src: ${SYMFONY_API_PATH}
        sync_strategy: 'unison'
        sync_excludes: ['.gitignore', '.git/', '.idea/']
```

docker-compose.yml
```
version: '2'

services:
...

    php-fpm-web:
        build:
            context: ./php-fpm-web
            dockerfile: Dockerfile
        volumes:
            - php-fpm-web-sync:/var/www/web:nocopy
            - ./php-fpm-web/php-conf.d:/usr/local/etc/php/conf.d
            - ${XDEBUG_LOGS_PATH}:/var/www/xdebug/log
        ports:
            - ${FORWARDED_PORT_WS}:9912
        environment:
            XDEBUG_REMOTE_PORT: ${XDEBUG_REMOTE_PORT_WEB}
            XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
            XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
        networks:
            default:
                ipv4_address: ${CONTAINER_IP_WEB}
        extra_hosts:
            - ${CONTAINER_DOMAIN_API}:${CONTAINER_IP_NGINX}

    php-fpm-api:
        build:
            context: ./php-fpm-api
            dockerfile: Dockerfile
        volumes:
            - php-fpm-api-sync:/var/www/api:nocopy
            - ./php-fpm-api/php-conf.d:/usr/local/etc/php/conf.d
            - ${XDEBUG_LOGS_PATH}:/var/www/xdebug/log
        environment:
            XDEBUG_REMOTE_PORT: ${XDEBUG_REMOTE_PORT_API}
            XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
            XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
        networks:
            default:
                ipv4_address: ${CONTAINER_IP_API}
        extra_hosts:
            - ${CONTAINER_DOMAIN_WEB}:${CONTAINER_IP_NGINX}

...

volumes:
    postgresql-volume:
        external: true
    mongo-volume:
        external: true
    php-fpm-web-sync:
        external: true
    php-fpm-api-sync:
        external: true

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: ${CONTAINERS_SUBNET}
```
