### ISSUE TITLE
Error in sending command to filesystem watcher

### ISSUE THREAD

**Issue by argent-smith** [EugenMayer/docker-sync#557]
### Error/Feature Requestion/Docs
After some time since the start the syncer crashes with this error:
```
UNISON 2.51.2 (OCAML 4.06.1) finished propagating changes at 18:41:44.79 on 22 Mar 2018
Saving synchronizer state
Synchronization complete at 18:41:45  (4 items transferred, 0 skipped, 0 failed)
Fatal error: Server: Error in sending command to filesystem watcher:
Broken pipe [write()]
```

### Docker Driver
docker machine with the host on the net

### Sync strategy
unison

### your docker-sync.yml
```yaml
version: "2"

options:
  compose-file-path: './docker-compose.yml'
  compose-dev-file-path: './docker-compose-dev.yml'
  verbose: true # make the whole sync verbose
  max_attempt: 1000000
syncs:
  appcode-sync: #tip: add -sync and you keep consistent names als a convention
    sync_strategy: 'unison'
    src: '/Users/paul/Development/Evrone/authentica'
    sync_host_ip: '192.168.47.91'
    sync_excludes: [".git", "tmp", "log", ".#*", ".DS_Store"]
    watch_args: '-v' # make watching verbose
    max_inotify_watches: 100000
```

### OS
OSX High Sierra
