### ISSUE TITLE
Manifest for not found: Error when running docker-sync stop

### ISSUE THREAD

**Issue by zacknewcomb** [EugenMayer/docker-sync#560]
Included in my makefile is a command to run docker-sync stop, which had recently stopped working. 
```
stop-sync:
	bundle exec docker-sync stop
	bundle exec docker-sync clean
```
This will return an error to me when running docker-sync stop, and produce the following error message. 
### Error/Feature Requestion/Docs
`Error response from daemon: manifest for eugenmayer/unison:hostsync_0.2 not found`

It also gives the message 
```
error  no such process 
error  Check your PIDFILE and process with such PID exists
```

### Docker Driver
Docker machine- overlay2

### Sync strategy
native_osx

### your docker-sync.yml
```
version: 2

options:
  verbose: true

syncs:
  flask-sync:
    src: './web'
    sync_host_ip: 'auto'
    sync_strategy: 'native_osx'
    sync_userid: '1000'
```
### OS
Ubuntu 16.04
