### ISSUE TITLE
Unable to find image 'eugenmayer/unison:2.51.2.1' locally

### ISSUE THREAD

**Issue by jasonellington** [EugenMayer/docker-sync#569]
### Error
Ever since I upgrade to high-sierra, i have been unable to get docker-sync to work properly. I had to reinstall Ruby 2.0 and now I am receiving the above error. I saw a similar post, but the suggestion seemed to be to use the boilerplate docker-sync.yml, which I am currently already doing.

### docker-sync.yml
```
version: "2"

syncs:
  docker-sync:
    src: './'
    sync_userid: '1000'
    sync_excludes: ['.gitignore', '.git/', '.idea/']
```
