### ISSUE TITLE
Failed in Renaming /app_sync to /.unison.app_sync

### ISSUE THREAD

**Issue by furan917** [EugenMayer/docker-sync#579]
Hey! I am currently trying to use the native_osx sync strategy but I keep getting the error shown below once the files have all been copied over for my http folder. I can get rsync to run with the same setup just slight changes in the docker sync but no luck with native. 

Have you error seen this issue? I cannot find any information about it anywhere and Im not really sure what is going on. I ran a docker-sync-stack clean/start. I purged all of container, then images then used docker system purge, even restarted my machine, but no luck in figuring out what the issue is. 

Im not sure if its maybe the size of the folder or something. It is about 5gb in size. But we do need 2 way syncing for our development so I cant switch it to rsync sadly. 

### Error/Feature Requestion/Docs
Error

### Docker Driver
d4m

### Sync strategy
native_osx

### your docker-sync.yml
```
version: "2"

syncs:
  http-sync:
    src: './http/'
    sync_userid: 0
  composer-sync:
    src: './composer.json'
    sync_userid: 0
  varnish-sync:
    src: './build/varnish/varnish.vcl'
    sync_host_ip: 'auto'
  mysql-sync:
    src: './db-dump'
    sync_userid: 0
  vendor-sync:
    src: './vendor'
    sync_userid: 0
  nginx-host-sync:
    src: './build/nginx/vhost/'
    sync_userid: 0
  nginx-ssl-sync:
    src: './build/nginx/ssl/'
    sync_userid: 0
```

### OS
OSX 10.13.4

### Log 
```
UNISON 2.51.2 (OCAML 4.06.1) started propagating changes at 17:28:37.31 on 01 Jun 2018
[BGN] Copying  from /host_sync to /app_sync
Failed: Error in renaming /app_sync to /.unison.app_sync..001..74c857c1a7d019a3df5b549ee91429fe.unison.tmp:
Resource busy [rename(/app_sync)]
UNISON 2.51.2 (OCAML 4.06.1) finished propagating changes at 17:28:37.31 on 01 Jun 2018
Saving synchronizer state
Synchronization incomplete at 17:28:37  (0 items transferred, 0 skipped, 1 failed)
  failed:
real	0m 0.08s
user	0m 0.04s
sys	0m 0.01s
chown ing file to uid 0
```
