### ISSUE TITLE
Docker-sync stops syncing with error "Fatal error: Server: No file monitoring helper program found"

### ISSUE THREAD

**Issue by Ian410** [EugenMayer/docker-sync#581]
### Error/Feature Requestion/Docs
At some point after a variable amount of time sync stops working.  Sometimes it is 10 minutes sometimes it is a few hours but it always stops eventually.  Today when it stopped I noticed in time and saw the error "Fatal error: Server: No file monitoring helper program found" in the log file, once that popped up it no longer synced.

### Docker Driver
Docker for Windows, docker-sync-0.5.7

### Sync strategy
unison, v2.51.2

### your docker-sync.yml
```
version: "2"

options:
  verbose: true
syncs:
  qj-sync: # tip: add -sync and you keep consistent names as a convention
    src: '/p/projects/qj/src'
    sync_args: ['-perms=0'] #required for two way sync ie generators, etc
    sync_strategy: 'unison'
    sync_excludes: ['.gitignore', '.idea/*','.git/*', '*.coffee', '*.scss', '*.sass', 'var/*']
    sync_host_ip: '127.0.0.1' #host ip isn't properly inferred
    max_attempt: 10
    project_root: '/var/www/html'
```

### OS
Windows 10 Pro Version 1803
