### ISSUE TITLE
error you shouldn't be here

### ISSUE THREAD

**Issue by kabamgamer** [EugenMayer/docker-sync#584]
This is my first time using dokcer-sync. It does sounds great, but it doesn't work yet for me.

At first: My OS is Windows 10.

When I run a docker-sync or docker-sync-stack command like start or clean, the only response I get is:
"error  Unsupported operating system. Are you sure you need DockerSync?".

When I uncomment my line sync_strategy: 'unison' I get an error aswell: 
"error  you shouldn't be here"

I don't know what te problem is, but hopefully you can help me.

Here is my docker-sync.yml:
```
version: "2"

options:
  compose-file-path: 'docker-compose.yml'
  compose-dev-file-path: 'docker-compose-dev.yml'

syncs:
  full-sync:
    notify_terminal: true
    src: './code/html/'
    dest: '/var/www/html/'
    sync_strategy: 'unison'  #uncomment this line to get other error
    sync_prefer: 'default'
```

This is my docker-compose-dev.yml:
```
version: '2'
services:
  web:
    container_name: dev_local
    build: .
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env
    volumes:
      - full-sync:/var/www/html/:nocopy
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
volumes:
  full-sync:
    external: true
  db-data:
```

I am very gratefully if someone could help me with this.
