### ISSUE TITLE
unison sync suddenly stops when app-sync writes many files

### ISSUE THREAD

**Issue by talya** [EugenMayer/docker-sync#585]
### Question
Is native-osx the correct strategy for a use case of heavy writes inside the container?
My use case here is trying to run my compilation inside the container, and have mounts of the src code and of the outputs (testlogs, binaries etc) on my mac host.

I manage to run at full speed with all files being synchronized well for a while, and then seem to hit some limit where the sync from /app-sync to /host-sync just stop.

I've tried adding max_inotify_watches which helped (I was getting the `Fatal error: Server: Filesystem watcher error: cannot add a watcher: system limit reached` before this).
Also tried adding `sync_prefer: 'dest'`, doesn't seem to change much.

/tmp/unison.log shows something like this and then just freezes (no more output is appended). full log [here](https://hastebin.com/owazimijop.sql) - `Synchronization incomplete at 17:10:04  (1920 items transferred, 0 skipped, 7 failed)
  failed: 1d9d166c4b830ead6c08bb15e682d862/ac.........`
sometimes it seems to go back to syncing (with ~8min delay), sometimes it doesn't (or perhaps I didn't wait long enough).
even when it goes back to syncing the files in the failed list are not synced anymore. 
I compare this by looking at the file in my sync container and just comparing the file in /app-sync (generated by my compiler run) with the file in /host-sync. content differs and also last modified time shows the one on /host-sync is stale.

Adding `sync_args: "-copyonconflict -debug verbose"` as the debug guide says also doesn't seem to change the behaviour I see. There are no files named 'conflict', but I do see lines like this when running diff -q : `Only in /host_sync/1d9d166c4b830ead6c08bb15e682d862/: .unison.java.log.453a7d4c54ba01191a971c0b0584509c.unison.tmp`

This sounds like it's similar to #410 but not exactly the same as the sync here stops from inside the container towards the host instead of the opposite, and also since maybe running the compiler inside the container is a very different use case than testing the compiled application inside the docker, which seems to be the canonical use case in documentation and debug instructions.

Any guidance/suggestion/documentation I've missed you may be able to point me to?

Also, It sounds like maybe using rsync for a 1 way sync of the outputs may be a good solution for my case if it will make performance/stability much better? The problem is I can't figure out if there is a way to make the 1way be from inside the container to the outside instead of the default way host--> container (I tried lookin at [rsync.rb](https://github.com/EugenMayer/docker-sync/blob/b430475bc8e432e465f5fcc39c66f074c139c9c8/lib/docker-sync/sync_strategy/rsync.rb) but couldn't find the relevant parts)

### Docker Driver
d4m - mac67 (assigned 6 out of my 8 cores, 12GB ram out of 16)

### Sync strategy
native_osx

### your docker-sync.yml

```
version: "2"

options:
  verbose: true
syncs:
  wix-fw-osx-srccode-sync: # tip: add -sync and you keep consistent names as a convention
    src: '.'
    # sync_strategy: 'native_osx' # not needed, this is the default now
    host_disk_mount_mode: 'cached'
  wix-fw-osx-outputs-sync:
    src: '/Users/talyas/dev/fw-bazel-outputs-from-docker'
    max_inotify_watches: 524288
    sync_excludes: ['1d9d166c4b830ead6c08bb15e682d862/sandbox']
    sync_prefer: 'dest'
    monit_enable: true
    sync_args: "-copyonconflict -debug verbose"
```

### OS
High Sierra 10.13.5
