### ISSUE TITLE
error:  Stopping failed

### ISSUE THREAD

**Issue by MrUpsidown** [EugenMayer/docker-sync#586]
Please accept my apologies if this is a duplicate of an existing issue but I didn't find a similar question already posted.

### Error/Feature Requestion/Docs
Error

### Docker Driver
d4m

### Sync strategy
default

### docker-sync.yml
```
version: "2"

options:
  verbose: true
syncs:
  web-sync: # tip: add -sync and you keep consistent names as a convention
    src: './app/site'
    # sync_strategy: 'native_osx' # not needed, this is the default now
    sync_excludes: ['.git', 'var']
```

### OS
macOS High Sierra 10.13.5

-----
What happens is that I can work on my project (edit files on my host machine, they get synced) for a while, then the sync fails (silently). I couldn't see any indication that it fails to sync my files but somehow after a while, I can see that files I edited on my host machine are not synced anymore.

When this happens, if I hit Ctrl+C to stop the containers, I get:
```
Killing app_web_1      ... done
Killing app_db_1       ... done
Killing app_mailhog_1  ... done
       error  Stopping failed of web-sync:
'up' failed with status 'pid 60522 exit 2': Attaching to app_db_1, app_mailhog_1, app_web_1
```

I then run `docker-sync-stack clean`, and `docker-sync-stack start` and I can work again. I feel this happens more and more frequently (few times a day).

Any idea? Let me know if I need to share anything else. Thanks!
