### ISSUE TITLE
Random issues with "permission denied"

### ISSUE THREAD

**Issue by SebTM** [EugenMayer/docker-sync#593]
I often get random issue that sync stops working regarding "Permission denied" and requires at least a restart of docker-sync sometimes a clean & new start.

> UNISON 2.51.2 (OCAML 4.06.1) finished propagating changes at 11:14:00.81 on 28 Jul 2018
> Saving synchronizer state
> Synchronization incomplete at 11:14:00  (0 items transferred, 0 skipped, 1 failed)
>   failed: vendor/rpkamp/mailhog-client/src/Message/MessageFactory.php
> Looking for changes
>   Waiting for changes from server
> Reconciling changes
> Propagating updates
> UNISON 2.51.2 (OCAML 4.06.1) started propagating changes at 11:14:06.87 on 28 Jul 2018
> [BGN] Copying vendor/rpkamp/mailhog-client/src/Message/MessageFactory.php from /Users/user/Projects/project1 to //14ce7687b8d2//app_sync
> Failed: Error in processing a transfer instruction:
> Permission denied [open(/app_sync/vendor/rpkamp/mailhog-client/src/Message/.unison.MessageFactory.php.9afdd5be39e1451e27f8858d044b4e2a.unison.tmp)]
> UNISON 2.51.2 (OCAML 4.06.1) finished propagating changes at 11:14:06.93 on 28 Jul 2018
> Saving synchronizer state
> Synchronization incomplete at 11:14:06  (0 items transferred, 0 skipped, 1 failed)
>   failed: vendor/rpkamp/mailhog-client/src/Message/MessageFactory.php
> Looking for changes
>   Waiting for changes from server
> Reconciling changes
> Nothing to do: replicas have not changed since last sync.
> Looking for changes
>   Waiting for changes from server
> Reconciling changes
> Propagating updates
> UNISON 2.51.2 (OCAML 4.06.1) started propagating changes at 11:14:19.02 on 28 Jul 2018
> [BGN] Deleting vendor/rpkamp/mailhog-client/src/Message/MessageFactory.php from /Users/user/Projects/project1
> Failed: Destination updated during synchronization
> The contents of file vendor/rpkamp/mailhog-client/src/Message/MessageFactory.php have been modified

### Docker Driver
Docker 18.06.0-ce-mac70 (26399) 

### Sync strategy
unison

### your docker-sync.yml
```
version: "2"

options:
  compose-file-path: 'docker-compose-dev.yml'

syncs:
  project-sync:
    src: ./
    monit_enable: true
    sync_excludes: ['.idea', '.git']
    sync_userid: 1000
    sync_strategy: unison
    watch_args: ''
```

### OS
macOS High Sierra 10.13.6 (17G65)
