### ISSUE TITLE
manifest for eugenmayer/unison:hostsync_0.2 not found.

### ISSUE THREAD

**Issue by Steinschnueffler** [EugenMayer/docker-sync#595]
Hello,

I have an error with docker-sync start. Whatever i do, i get the error shown below. This also occures 
with native_osx as sync_strategie. As the output mentioned, i tried to increase max_attempt, but it just needed longer to fail.

In unison.log i have a lot of that:
`Fatal error: ill-formed root specification socket://127.0.0.1:`

### Error/Feature Requestion/Docs

````
Unable to find image 'eugenmayer/unison:latest' locally
docker: Error response from daemon: manifest for eugenmayer/unison:latest not found.
See 'docker run --help'.
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' tinto-docker-sync
       error  Error getting mapped port, exit code 125
     message  Error: No such object: tinto-docker-sync
Traceback (most recent call last):
	15: from /usr/local/bin/docker-sync:23:in `<main>'
	14: from /usr/local/bin/docker-sync:23:in `load'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/docker-sync-0.5.2/bin/docker-sync:14:in `<top (required)>'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/docker-sync-0.5.2/tasks/sync/sync.thor:47:in `start'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/docker-sync-0.5.2/tasks/sync/sync.thor:163:in `daemonize'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/docker-sync-0.5.2/lib/docker-sync/sync_manager.rb:98:in `start_container'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/docker-sync-0.5.2/lib/docker-sync/sync_manager.rb:98:in `each'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/docker-sync-0.5.2/lib/docker-sync/sync_manager.rb:99:in `block in start_container'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/docker-sync-0.5.2/lib/docker-sync/sync_process.rb:105:in `start_container'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/docker-sync-0.5.2/lib/docker-sync/sync_strategy/unison.rb:187:in `start_container'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/docker-sync-0.5.2/lib/docker-sync/sync_strategy/unison.rb:187:in `loop'
/usr/local/lib/ruby/gems/2.5.0/gems/docker-sync-0.5.2/lib/docker-sync/sync_strategy/unison.rb:192:in `block in start_container': Failed to start unison container in time, try to increase max_attempt (currently 5) in your configuration. See https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration for more informations (RuntimeError)
`````
### Docker Driver
docker for mac

### Sync strategy
tested with unison and native_osx

### your docker-sync.yml

````
version: "2"

options:
  unison_image: 'eugenmayer/unison:2.51.2.1'
  max_attempt: 5

syncs:
    tinto-docker-sync:
        src: '.'
        sync_strategy: 'native_osx'
        notify_terminal: true
        sync_excludes:
            - '.idea'
            - '.DS_Store'
            - '.git'
            - 'app/cache/*'
            - 'app/logs/*'
            - 'node_modules/*'
            - 'provisioning'
            - 'ci'
            - 'modofu'
            - 'rancher'
            - 'ezpublish_legacy/ezdemo_site/cache/*'
            - 'ezpublish_legacy/ezdemo_site/log/*'
            - 'ezpublish_legacy/var/cache/*'
            - 'ezpublish_legacy/var/log/*'
        sync_args:
            - "-ignore='BelowPath .git'"
            - "-prefer newer"
        max_inotify_watches: 100000
````

### OS
OSX
