### ISSUE TITLE
[question] Would it be possible to describe the DockerSync container in a docker-compose.override.yml?

### ISSUE THREAD

**Issue by alsuren** [EugenMayer/docker-sync#598]
I keep forgetting to `docker-sync start` after a docker reboot, and wondering why my dockers are running old code. I would quite like for `docker-compose up -d` to be the only thing I need to do for a performant synced filesystem.

Looking at https://github.com/EugenMayer/docker-sync/wiki/How-does-native_osx-work-with-OSXFS-and-is-still-native-speed-fast%3F it seems like docker-compose should be able to set up the osxfs bind-mount, and start the my_app-sync container. Naively, I'd expect that the only thing left is getting docker-sync.yml communicated into the container.

How much scaffolding would I need to add to my docker-compose.override.yml in order to get the DockerSync container up and running without invoking the docker-sync utility on my laptop?

### snippet from docker-compose.yml
```
version: '2'

  gunicorn:
    hostname: gunicorn
    working_dir: /srv/monolithic-repo/src
    command: ["python", "manage.py" "runserver" "0.0.0.0:8000"]
    volumes:
      - .:/srv/monolithic-repo/
```

### snippet from current docker-compose.override.yml
```
version: '2'

services:
  gunicorn:
    volumes:
      # # Speed up osxfs by replacing it with synced volumes where needed.
      - src-sync:/srv/monolithic-repo/src:nocopy
      - frontend-sync:/srv/monolithic-repo/frontend:nocopy

  src-sync:
    external: true
  frontend-sync:
    external: true
```

### your docker-sync.yml
```
version: '2'

syncs:
  src-sync:
    src: './src'
    sync_excludes: ['*.pyc']
  frontend-sync:
    src: './frontend'
    sync_userid: 1000
    sync_excludes: ['node_modules']
```

### OS
osx 10.13.4
