### ISSUE TITLE
Docker-sync not work at first time i run it on ubuntu

### ISSUE THREAD

**Issue by TranQuocViet** [EugenMayer/docker-sync#599]
### Error/Feature Requestion/Docs
Error
### Docker Driver
i don't now how to definite docker driver on my computer, i use it on ubuntu is installed on my ssd, not use vitual marchine
### Sync strategy
unison
### your docker-sync.yml
```
version: "2"
options:
  verbose: true
syncs:
  binance_sync:
    notify_terminal: false
    src: './'
    sync_excludes: ['docker-compose.yml', '.gitignore', '.git', 'docker', '_build', 'deps', 'node_modules', '.mix', '.hex', '.elixir_ls', 'log']
    sync_excludes_type: 'Name'
    watch_excludes: ['.*/.git', '.*/node_modules', '.gitignore', 'docker', '_build', 'deps', '.elixir_ls', 'log']
```

### OS
Linux (Ubuntu 18.04)

First time i run my project on ubuntu and seem docker-sync not run, it show like bellow on terminal when i run `docker-sync start --foreground`

```
note:  Starting in foreground mode
     command  docker volume create --opt type=none --opt device="/home/viet911/Projects/binance/" --opt o=bind --name binance_sync
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
     success  Docker volume for binance_sync created
     success  Watcher disabled by configuration

```
and have no docker container is stated, when i run `docker ps -aq` it show empty. When i run my project without docker-syn, it run property, but not run when use docker-sync, help me please !
