### ISSUE TITLE
Undefined method "check_unison_image"

### ISSUE THREAD

**Issue by senechaux** [EugenMayer/docker-sync#607]
### Error
Undefined method "check_unison_image"
I got an error about an undefined method "check_unison_image" if the files:
https://github.com/EugenMayer/docker-sync/blob/master/lib/docker-sync/update_check.rb
https://github.com/EugenMayer/docker-sync/blob/master/lib/docker-sync/upgrade_check.rb

After checking the source code I saw this commit https://github.com/EugenMayer/docker-sync/commit/9ffd23b5a30c63cfe3f057d14a4e433ced6d420c where de function definition has been deleted.

I've been able to make it work commenting out the method calls to "check_unison_image" in the file upgrade_check.rb of the installed gem.

### Docker Driver
I'm using Mac OS High Sierra with standard installation of Docker

### Sync strategy
native_osx with unison

### your docker-sync.yml
```
version: "2"
options:
  compose-file-path: 'docker-compose.yml'
  compose-dev-file-path: 'docker-compose-dev.yml'
  unison_image: 'eugenmayer/unison:2.51.2.1'
syncs:
  km77com-sync:
    sync_strategy: 'native_osx'
    src: './'
    sync_host_ip: '127.0.0.1'
    sync_host_port: 10872
    sync_excludes: ['.git', '.gitignore', '.DS_Store', '.idea', '.ebextensions', '.sass-cache', '.vagrant', 'docker', 'docker-sync.yml', 'docker-compose.yml', 'docker-compose-dev.yml', 'var/logs/*', 'var/cache/*']
    sync_excludes_type: 'Name'
    notify_terminal: true
    monit_enable: true
    monit_interval: 5
    monit_high_cpu_cycles: 2
```

### OS
OSX
