### ISSUE TITLE
Consuming one volume with multiple containers with different user requirements

### ISSUE THREAD

**Issue by simensen** [EugenMayer/docker-sync#610]
### Error/Feature Requestion/Docs

I have two containers, one for PHP-FPM and one for assets. I want to share the project directory with both. However, the PHP-FPM user runs as `www-data` and needs to be able to write to the project directory. Likewise, the assets container runs as `node` and needs to be able to write to the project directory.

I thought I could fix this by defining two syncs with the same `src` directory and specify the correct `sync_userid` and `sync_groupid` for each instance.

This sorta works, to a point. It does let me write to each volume jut fine. The problem is that there is a 2-way sync with just one of them. It took me a long time to figure out what was actually going wrong.

In this case, my `my-project-for-fpm-sync` container gets setup with `/app_sync` correctly in the beginning (long sync). However, as I make changes locally on the host, or as the `assets` container creates/updates/deletes content, the contents of `/app_sync` do not get updated. I can, however, confirm the `/host_sync` is getting updated.

Is this to be expected? Is this a bug? Is there a better way for me to do this?

### Docker Driver

d4m

### Sync strategy

native_osx

### your docker-sync.yml

```yaml
version: "2"

options:
  verbose: true
syncs:
  my-project-for-fpm-sync:
    src: '.'
    notify_terminal: true
    sync_userid: '33'
    sync_groupid: '33'
  my-project-for-assets-sync:
    src: '.'
    notify_terminal: true
    sync_userid: '1000'
    sync_groupid: '1000'
```

### OS

macOS 10.13.6
