### ISSUE TITLE
Docker-sync fails to start the first time

### ISSUE THREAD

**Issue by derschatta** [EugenMayer/docker-sync#612]
### Error/Feature Requestion/Docs

The first time each day I start up docker-sync I get this error:
```
Traceback (most recent call last):
	9: from /Users/username/.rbenv/versions/2.5.0/bin/docker-sync:23:in `<main>'
	8: from /Users/username/.rbenv/versions/2.5.0/bin/docker-sync:23:in `load'
	7: from /Users/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/docker-sync-0.5.8/bin/docker-sync:14:in `<top (required)>'
	6: from /Users/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	5: from /Users/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	4: from /Users/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	3: from /Users/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	2: from /Users/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/docker-sync-0.5.8/tasks/sync/sync.thor:32:in `start'
	1: from /Users/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/docker-sync-0.5.8/lib/docker-sync/update_check.rb:38:in `run'
/Users/username/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/docker-sync-0.5.8/lib/docker-sync/update_check.rb:92:in `check_and_warn': undefined local variable or method `docker_sync_update_check7' for #<UpdateChecker:0x00007f9a300ac090> (NameError)
Did you mean?  docker_sync_update_check
```

After stopping docker-sync and starting it again everything runs normally. No error message.

### Docker Driver
d4m 2.0.0.0-beta1-mac75

### Sync strategy
default

### your docker-sync.yml
```
version: "2"

options:
  verbose: true
syncs:
  www-sync: # tip: add -sync and you keep consistent names as a convention
    src: ${LOCAL_SRC}
    notify_terminal: true
    sync_excludes: ['.idea', 'node_modules', '.gitignore', '.git', '.DS_Store']`
```

### OS
OSX Version 10.13.6 High Sierra
