### ISSUE TITLE
Anonymous volume created for eugenmayer/unison container

### ISSUE THREAD

**Issue by ynilu** [EugenMayer/docker-sync#613]
### Error/Feature Requestion/Docs
An anonymous volume mounted into `/unison` is created when using docker-sync.
The volumes is NOT deleted even when `docker-sync-stack clean` was called.

The directory `/unison` is empty in the sync container.
Does this work as expected?

### Docker Driver
d4m

### Sync strategy
unison

### your docker-sync.yml
```
version: '2'
options:
  max_attempt: 10
syncs:
  my-sync:
    src: '.'
    sync_strategy: 'unison'
    sync_host_ip: '127.0.0.1'
    sync_host_port: 10872
    sync_excludes: [ '.git', '.idea', 'tmp' ]
    sync_prefer: 'src'
```
### OS
macOS 10.14 (18A391)
