### ISSUE TITLE
docker-sync does not sync (again)

### ISSUE THREAD

**Issue by ohcibi** [EugenMayer/docker-sync#624]
### Error

Using the following configuration:

```yml
version: "2"

options:
  verbose: true # make the whole sync verbose
syncs:
  app-sync: #tip: add -sync and you keep consistent names as a convention
    src: 'app/'
    sync_host_ip: 'auto'
    sync_host_port: 10872
    sync_userid: '501'
    watch_args: '-v' # make watching verbose
    sync_exclude: ['build']
```

The initial sync with `docker-sync start` after a `docker-sync clean` works as expected but after this nothing is synced. Not even by explicitly calling `docker-sync sync`. Also the container uses constantly CPU. It also doesn't just works after a few minutes as former variants of this issue.

### Docker Driver
docker for mac

### Sync strategy
native_osx

### docker-sync.yml

```yml
version: "2"

options:
  verbose: true # make the whole sync verbose
syncs:
  app-sync: #tip: add -sync and you keep consistent names as a convention
    src: 'app/'
    sync_host_ip: 'auto'
    sync_host_port: 10872
    sync_userid: '501'
    watch_args: '-v' # make watching verbose
    sync_exclude: ['build']
```

### OS
macOS 10.14.1
