### ISSUE TITLE
native_osx: Many changes to excluded files causes >100% CPU of docker daemon

### ISSUE THREAD

**Issue by ypresto** [EugenMayer/docker-sync#626]
### Error/Feature Request/Docs

I sometimes run `yarn install` on host OS while docker-sync is running.
It causes files under node_modules are massively changed, so I'm ignoring them in docker-sync.yml.
But docker daemon to consume >100% of CPU (also osxfs process consumes more CPU than ordinal) on that.
My understanding is that osxfs notifies file changes under synced directory, even if they are excluded by docker-sync.yml (= excluded by unison).

### Docker Driver
d4m

### Sync strategy
default (native_osx)

### your docker-sync.yml

```
version: '2'

options:
  verbose: true

syncs:
  schooltakt-ds-rails:
    src: 'rails'
    sync_userid: 2000
    sync_groupid: 2000
    sync_excludes_type: 'Path'
    sync_excludes:
      - '{**/,}.DS_Store'
      - '{**/,}node_modules'
      - 'tmp'
      - 'vendor/bundle'
      - 'log'

  schooltakt-ds-node:
    src: 'node'
    sync_userid: 2000
    sync_groupid: 2000
    sync_excludes_type: 'Path'
    sync_excludes:
      - '{**/,}.DS_Store'
      - '{**/,}node_modules'
```

### OS
macOS 10.14.1
