### ISSUE TITLE
Not compatible with docker-compose version 3

### ISSUE THREAD

**Issue by jwg2s** [EugenMayer/docker-sync#627]
### Error/Feature Requestion/Docs
```
ERROR: for catchall  Cannot create container for service catchall: invalid volume specification: '/path/to/project:/srv/app:nocopy': invalid mount config for type "bind": field VolumeOptions must not be specified
```

### Docker Driver
Docker for Mac - Version 2.0.0.0-mac81 (29211)

### Sync strategy
native_osx

### your docker-sync.yml
```
version: '2'
options:
  verbose: true
syncs:
  web-sync: # tip: add -sync and you keep consistent names as a convention
    src: './app'
    sync_strategy: 'native_osx'
  catchall-sync:
    src: './app'
    sync_strategy: 'native_osx'
```

### OS
OS X 10.14.2 (18C54)
