### ISSUE TITLE
(<unknown>): did not find expected key while parsing a block mapping

### ISSUE THREAD

**Issue by igormorse** [EugenMayer/docker-sync#629]
### Error/Feature Requestion/Docs
**error  (<unknown>): did not find expected key while parsing a block mapping at line 7 column 9**

### Docker Driver
Docker for Windows :. Version 17.12.0-ce-win47 ( 15139 )

Channel: stable

### Sync strategy
unison

### docker-compose.yml

```
version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server
    volumes:
      - redis_store:/data
    ports:
      - "6379:6379"
    env_file:
      - './web.env'

  sidekiq:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
    container_name: sidekiq
    command: bundle exec sidekiq -q default -q mailers -q import_model
    depends_on:
      - redis
    volumes:
      - bundle:/usr/local/bundle
    links:
      - redis
    # stdin_open: true
    # tty: true
    env_file:
     - ./web.env

  web:
    privileged: true
    image: app/web
    container_name: web
    command: ../resources/start_rails.sh
    build: 
        context: .
        dockerfile: Dockerfile
        args:
          http_proxy: ${HTTP_PROXY}
          https_proxy: ${HTTPS_PROXY}
    volumes:
      - bundle:/usr/local/bundle
    ports:
      # Rails Server
      - "3000:3000"
      # Pry Remote Server
      - "9876:9876"
    links:
      - redis
    depends_on:
      - redis
    # tty: true
    # stdin_open: true
    env_file:
      - './web.env'

volumes:
  bundle:
    driver: local
  redis_store:
    driver: local
```

### docker-compose-dev.yml

```
version: '3'

volumes:
  app-unison-sync:
    external: true
  pgdata:
    driver: local
  ldap_db_store:
    driver: local
  ldap_config_store:
    driver: local

services:
  db:
    image: postgres
    container_name: db
    volumes:
      # Cannot mount in Host. Searching for a workaround
      #- ./tmp/db:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
     - ./db.env

  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    env_file:
      - './web.env'

  sidekiq:
    volumes:
      - app-unison-sync:/app:nocopy

  web:
    volumes:
       - app-unison-sync:/app:nocopy
    links:
      - redis
      - mailcatcher
      - db
    depends_on:
      - redis
      - mailcatcher
      - db
```

### docker-sync.yml

```
version: "2"
options:
    verbose: true
syncs:
    app-unison-sync: # tip: add -sync and you keep consistent names als a convention
        sync_args: ['-perms=0'] #required for two way sync ie generators, etc
        sync_strategy: 'unison' 
        sync_host_ip: '127.0.0.1' #host ip isn't properly inferred
         sync_excludes: ['tmp','.git','coverage', 'log']
        # sync_excludes: ['.gitignore', '.idea/*','.git/*', '*.coffee', '*.scss', '*.sass','*.log']
        src: './'
```

### OS
Windows

# Further Description

I followed the installation guide for Windows using WSL and when attempting to use **docker-sync-stack start** I get the followed error. What I doing wrong ?

Note that those containers had been previously in use without docker-sync as my goal was to improve the mount speed to decrease the load times for development.

I have a **docker-compose.override.yml** in the root folder besides those two and I dont know if this affect anything.
