### ISSUE TITLE
Does not sync after few stop ands starts

### ISSUE THREAD

**Issue by kamil-jakubowski** [EugenMayer/docker-sync#633]
@EugenMayer I think that the problem from #410 still exists. I have Docker Version 2.0.0.0-mac81 (29211), (docker sync 0.5.9), so I believe that it has changes from version that was "edge" in Jul 2018 (when you wrote last comment).

After few days, (and couple of stop and start containers and docker-sync) my syncing is stopping both directions on one of my sync-containers (randomly, sometimes both containers). Only cleaning and rebuilding it again corrects the problem, but it is very long operation. 

#### docker-sync.yml:
```
version: '2'
syncs:
    crm1-backend-sync:
        sync_strategy: native_osx
        src: './'
        sync_excludes_type: 'Path'
        sync_excludes:
            - 'app/cache'
            - 'app/logs'
            - 'emberapp/tmp'
            - 'shop/app/cache'
            - 'shop/app/logs'
            - 'docker'
            - '.idea'

    crm1-frontend-sync:
            sync_strategy: native_osx
            src: './emberapp/'
            sync_excludes_type: 'Path'
            sync_excludes:
                - 'tmp'
```
