### ISSUE TITLE
FileNotFoundError: docker-compose.yml not found

### ISSUE THREAD

**Issue by vteivans** [EugenMayer/docker-sync#641]
### Error/Feature Requestion/Docs
https://github.com/EugenMayer/docker-sync/issues/582

### OS
Windows 10

### Docker Driver
WSL + Docker for Windows (18.09.1, build 4c52b90), docker-sync-0.5.7, docker-compose 2

### Sync strategy
Unison

### Your docker-sync.yml
```yml
version: "2"

options:
  verbose: false
  max-attempt: 30
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  app-server-sync: # tip: add -sync and you keep consistent names as a convention
    src: './server'
    sync_args: ['-perms=0'] #required for two way sync ie generators, etc
    sync_strategy: 'unison'
    # sync_user: 'root'
    sync_excludes: [
      '.idea/*',
      '.git/*',
      '.gitignore',
      'node_modules',
      '*/node_modules',
      '*/.gitignore',
      'docker-*',
      'Dockerfile',
      'Dockerfile-dev',
      '*/*.log',
      '*.log']
    sync_host_ip: '127.0.0.1' #host ip isn't properly inferred
```

### OS
Windows 10 1803

### Hey!
I'm not sure if this is the correct way to do this. I wanted to add a comment on the given issue, but it's locked. I ran in to it just today and once before. And there are two ways I have worked around this:

1. Install Linux Docker on WSL. For me at least, this problem only appears if I symlink the Windows docker binaries.

2. Simply running `docker-sync start` and `docker-compose -f docker-compose.yml -f docker-compose-dev.yml up` separately. No need to run one in bash and the other in PowerShell (at least for me). Simply run:
    - `docker-sync start`
    - `docker-compose -f docker-compose.yml -f docker-compose-dev.yml up`

### P.S.
Huge thanks to you guys for having this available on Windows. Most syncing stuff usually isn't. If I have some time I'll check the ruby code, maybe get some idea why is this happening.
