### ISSUE TITLE
`check_and_warn': undefined method `check_unison_image' for #UpdateChecker

### ISSUE THREAD

**Issue by mferrier** [EugenMayer/docker-sync#642]
### Error/Feature Requestion/Docs
Further to #609 and #611, the issue seems to still exist for the latest `gem install --pre docker-sync` at the time of writing: `docker-sync-0.5.11.pre.beta2`.

```
$ docker-sync start
/Library/Ruby/Gems/2.3.0/gems/docker-sync-0.5.10/lib/docker-sync/upgrade_check.rb:59:in `check_and_warn': undefined method `check_unison_image' for #<UpdateChecker:0x00007fcf5897d860> (NoMethodError)
Did you mean?  check_rsync_image
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.5.10/lib/docker-sync/upgrade_check.rb:18:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.5.10/tasks/sync/sync.thor:33:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/docker-sync-0.5.10/bin/docker-sync:14:in `<top (required)>'
	from /usr/local/bin/docker-sync:22:in `load'
	from /usr/local/bin/docker-sync:22:in `<main>'
```

### Docker Driver
d4m

### Sync strategy
default (native_osx)

### your docker-sync.yml
```
version: '2'
options:
  compose-dev-file-path: 'docker-compose-mac.yml'
  verbose: false
syncs:
  web-sync:
    src: '.'
    sync_excludes:
      - .git
      - .docker-sync
```
### OS
```
$ uname -a
Darwin mikebook-pro-3.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin
```
