### ISSUE TITLE
docker-sync Unknown sync_strategy default

### ISSUE THREAD

**Issue by cytopia** [EugenMayer/docker-sync#647]
## docker-sync Unknown sync_strategy default

I have tried to set the sync strategy to 'default' as per your documentation: https://docker-sync.readthedocs.io/en/latest/getting-started/configuration.html

However it does not seem to be aware of this one:

### Error
```bash
cytopia> docker-sync start
Traceback (most recent call last):
        16: from /usr/local/bin/docker-sync:23:in `<main>'
        15: from /usr/local/bin/docker-sync:23:in `load'
        14: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/bin/docker-sync:14:in `<top (required)>'
        13: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        12: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        11: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        10: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         9: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/tasks/sync/sync.thor:47:in `start'
         8: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/tasks/sync/sync.thor:163:in `daemonize'
         7: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:101:in `start_container'
         6: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:74:in `init_sync_processes'
         5: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:74:in `each'
         4: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:75:in `block in init_sync_processes'
         3: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:139:in `create_sync'
         2: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_manager.rb:139:in `new'
         1: from /var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_process.rb:39:in `initialize'
/var/lib/gems/2.5.0/gems/docker-sync-0.5.11/lib/docker-sync/sync_process.rb:54:in `set_sync_strategy': Unknown sync_strategy default (RuntimeError)
```

Specifically:
```
`set_sync_strategy': Unknown sync_strategy default (RuntimeError)
```

### Docker Driver
Linux

### Sync strategy
default

### your docker-sync.yml
```yml
version: '2'

options:
  compose-file-path: 'docker-compose.yml'

  compose-dev-file-path: 'docker-compose-dev.yml'

syncs:
  devilbox-intranet-sync:
    src: '${DEVILBOX_PATH}/.devilbox/www/'
    sync_userid: '${NEW_UID}'
    sync_strategy: 'default'
    sync_excludes: ['.gitignore', '.git/', '.idea/', '.vscode/']

  devilbox-data-www-sync:
    src: '${HOST_PATH_HTTPD_DATADIR}/'
    sync_userid: '${NEW_UID}'
    sync_strategy: 'default'
    sync_excludes: ['.gitignore', '.git/', '.idea/', '.vscode/']
```

### OS
Linux
