### ISSUE TITLE
Documentation misleading about sync_strategy 'default'

### ISSUE THREAD

**Issue by cytopia** [EugenMayer/docker-sync#648]
### Docs

Documentation about `sync_strategy` is misleading, as it suggests an example to use `'default'`:

https://docker-sync.readthedocs.io/en/latest/getting-started/configuration.html

```yml
...
syncs:
  default-sync:
    # os aware sync strategy, default to native_osx under MacOS (except with docker-machine which use unison), and native docker volume under linux
    sync_strategy: 'default'
...
 ```
However, `'default'` itself seems to be invalid as a value and requires you to omit the whole `sync_strategy` block. If using `'default'`, the following error will be thrown:

`set_sync_strategy': Unknown sync_strategy default (RuntimeError)`

### Docker Driver
Linux

### Sync strategy
`'default'`

### your docker-sync.yml
```yml
...
syncs:
  default-sync:
    # os aware sync strategy, default to native_osx under MacOS (except with docker-machine which use unison), and native docker volume under linux
    sync_strategy: 'default'
...
 ```
### OS
Linux
