### ISSUE TITLE
Unique sync volume name

### ISSUE THREAD

**Issue by paveq** [EugenMayer/docker-sync#654]
### Feature Request

Generation of unique sync volume name based on eg. host path (path of docker-sync).

This would prevent issues like https://github.com/EugenMayer/docker-sync/issues/227 and allow to copy docker-sync configuration between different projects.

As example, it could look like:

```
syncs:
  code-sync:
    host_disk_mount_mode: 'cached'
    append_unique_identifier: true
    ...
```

This already sort of works, but is not very convenient or straightforward:

```
syncs:
  code-sync-`echo $PWD | md5`:
    host_disk_mount_mode: 'cached'
```
