### ISSUE TITLE
Docker-compose 3.4+ target is ignored

### ISSUE THREAD

**Issue by shoe-diamente** [EugenMayer/docker-sync#660]
### Error/Feature Requestion/Docs

When I run docker-sync file below (using `docker-sync-stack start`) it seems that when it starts the docker-compose file it ignores the `target:` setting specified for each one of the services. It starts the last target in a multi-stage build.

The `target:` is not ignored if started manually via `docker-compose -f docker-compose.yml -f docker-compose.development.yml up`.

### Docker Driver
Docker Desktop (for Mac) Version 2.0.0.3
Docker Engine: 18.09.2
Docker Compose: 1.23.2
Docker-Sync: 0.5.11

### Sync strategy
native_osx

### your docker-sync.yml
```
version: "2"

options:
  verbose: true
  compose-file-path: 'docker-compose.yml'
  compose-dev-file-path: 'docker-compose.development.yml'
syncs:
  server-source-sync:
    src: './server'
    sync_strategy: 'native_osx'
    sync_excludes: [...]
  client-source-sync:
    src: './client'
    sync_strategy: 'native_osx'
    sync_excludes: [...]
```

### your docker-compose.development.yml

```
version: '3.4'

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    ports:
      - "5050:80"
    volumes:
      - "server-source-sync:/source:nocopy"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:80"
    volumes:
      - "client-source-sync:/var/www/html:nocopy"

  client-watch:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development-watch
    volumes:
      - "client-source-sync:/source:nocopy"

volumes:
  server-source-sync:
    external: true
  client-source-sync:
    external: true
```

### OS
macOS High Sierra 10.13.6

**Comment by EugenMayer** [comment]
sorry but what does this has to do with docker-sync? Docker-sync was not designed to trigger a build while starting up and i guess the target flag is ignored by the `docker-compose` gem or similar - so until we did not remove that gem and run `docker-compose` on the shell, this is not doable.

Build before you start docker-sync - that should be the solution for now

**Comment by shoe-diamente** [comment]
`target` is not only about building. It's about what `ENTRYPOINT` to run.

I can have:

```
FROM php:5.6-apache AS one
ENTRYPOINT a

FROM node AS two
ENTRYPOINT b
```

and in my `docker-compose.yml` file have:

```
services:
    php:
        context: .
        dockerfile: Dockefile
        target: one
    node:
        context: .
        dockerfile: Dockefile
        target: two
```
