### ISSUE TITLE
Option sync_groupid does not work

### ISSUE THREAD

**Issue by shiftedreality** [EugenMayer/docker-sync#668]
### Error/Feature Requestion/Docs
Hello, I'm trying to set user and group permissions on volume:

```
sync_userid: '1000'
sync_groupid: '1000'
```

But it does not apply. User ID works well same time.

```
Synchronization complete at 13:52:20  (11 items transferred, 0 skipped, 0 failed)
real    0m 10.47s
user    0m 0.29s
sys     0m 1.08s
chown ing file to uid 1000
```

```
-rw-r--r--  1 www  root    572 Jul 23 18:44 php.ini
-rw-r--r--  1 www  root    804 Jul 23 18:44 php.ini.sample
drwxr-xr-x  2 www  root   4096 Jul 23 18:44 phpserver
drwxrwxr-x  6 www  root   4096 Jul 23 18:45 pub
-rw-r--r--  1 www  root   1939 Jul 23 18:45 scenario.bkf
```

### Docker Driver
d4m

### Sync strategy
Default

### your docker-sync.yml

```
version: 2
syncs:
  magento-sync:
    src: './'
    sync_excludes:
      - '.git'
      - '.idea'
      - '.magento'
      - '.docker'
      - '.github'
      - 'docker-compose.yml'
      - 'docker-sync.yml'
    sync_userid: '1000'
    sync_groupid: '1000'
  magento-var-sync:
    src: './var'
    sync_userid: '1000'
    sync_groupid: '1000'
```

### OS
Mac 10.14.5
