### ISSUE TITLE
sync_groupid for native_osx

### ISSUE THREAD

**Issue by barisione** [EugenMayer/docker-sync#674]
### Error/Feature Requestion/Docs
When using `native_osx` all files belong to group root.
This is known and documented, but it would be nice if it could be fixed.

Looking at the `unison` sync strategy code, it's not possible to set the group with `unison`.
I wonder if it's possible to do something with `native_osx` by having the right user and group on the sync container.

### Docker Driver
d4m

### Sync strategy
native_osx

### your docker-sync.yml
```
version: '2'
syncs:
  sync-test_sync:
    sync_strategy: 'native_osx'
    src: './mounted'
    sync_userid: 501
    sync_groupid: <XXX>
```

### OS
macOS Mojave 10.14.4
