### ISSUE TITLE
Sync seems to be not working correctly despite no errors

### ISSUE THREAD

**Issue by robertkabat** [EugenMayer/docker-sync#676]
### Error
According to docker-sync docs/website I think I should get much quicker response than I do now. It seems like no matter which sync strategy I use rsync/unison it takes no effect at all. I was under the impression that I can get experience close to native setup.

Example of the problem:

1. I have simplest Laravel blog api - one of my endpoints returns simple dummy blog post which contains only few lines of text, nothing magical is happening here. This is just to test docker-sync.
2. I make a request via postman to that endpoint and it takes from ~5-7 seconds
3. The same request, same code, same setup with or without docker-sync - the result is always the same which makes me think that somehow sync is not working for me as it should although I think it is syncing, I can't see any errors and nothing is crashing, I can load my website normally.
4. Exactly the same thing but on Ubuntu takes ~80ms so I Imagine that I could get at least 150ms using docker sync on Mac

This might be just me doing something horribly wrong but after going through tutorials/docs/boilerplates I don't know where else I can turn. 

Reading through different posts left me under the impression that some people got it working. 
I have even reached put to StackOverflow community [HERE](https://stackoverflow.com/questions/57582242/macos-docker-sync-laravel-5-8-postman-performance).

In my `docker-compose.yml` I am not using any `watch` command but I don't suppose that is the problem(it is always part of boilerplate examples).

Is it me, Mac or something else? Maybe I have misunderstood documentation? 

### Docker Driver
Docker for Mac

### Sync strategy
unison/rsync - tried both - both give me the same(no results)

### docker-sync.yml
```yml
version: "2"

options:
  verbose: true
syncs:
  macos-unison: # tip: add -sync and you keep consistent names as a convention
    src: '../'
    sync_host_port: 10872
    sync_strategy: 'unison'
    sync_excludes: ['vendor', 'node_modules', '.idea', '.git']
    notify_terminal: true
```
### docker-compose-dev.yml

```yml
version: '3.7'
services:
  webapp:
    volumes:
      - macos-unison:/srv/app:nocopy
  apache2:
    volumes:
      - macos-unison:/srv/app:nocopy

volumes:
  macos-unison:
    external: true

```

### OS
MACOS Mojave 10.14.6
