### ISSUE TITLE
Can't run docker-sync after upgrading to Xcode 11

### ISSUE THREAD

**Issue by DarrellBrogdon** [EugenMayer/docker-sync#679]
### Error/Feature Requestion/Docs
My Mac auto-upgraded Xcode to version 11 today and ever since then I'm unable to run docker sync.  Whenever I do I get the following error:

`mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h`

### Docker Driver
docker-machine+vbox  (I think?)

### Sync strategy
default

### your docker-sync.yml
```
version: "2"

syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  partnerbase-api: #tip: add -sync and you keep consistent names as a convention
    src: './'
    notify_terminal: true
    sync_userid: ${UID}
    sync_excludes: ['.git', 'local-m2']
    watch_args: '-v' # make watching verbose
    monit_enable: true
    monit_interval: 5
    monit_high_cpu_cycles: 2
```

### OS
OSX Mojave
