### ISSUE TITLE
docker-sync clean not remove it's volume

### ISSUE THREAD

**Issue by hieunguyentrung** [EugenMayer/docker-sync#691]
I use `docker-sync start` and it creates container + volume, but then I use `docker-sync clean` or `docker-sync-stack clean`  then I see `success  Finished cleanup. Removed stopped, removed sync container and removed their volumes`, but in reality only the container was deleted, the volume remains even though no other container exists to use it. If I delete it with `docker volume rm`, the delete is successful.

### Error/Feature Requestion/Docs
Error

### Docker Driver
? (d4m or docker-machine+vbox/fusion)

### Sync strategy
native_osx

### your docker-sync.yml
```
version: '2'

options:
  compose-file-path: 'docker-compose.yml'
  compose-dev-file-path: 'docker-compose-dev.yml'
  max_attempt: 30
syncs:
  test-sync:
    src: '.'
    sync_strategy: 'native_osx'
    sync_excludes_type: 'none'
```
### OS
macOS 10.14.6
<img width="740" alt="Screen Shot 2019-10-26 at 22 09 17" src="https://user-images.githubusercontent.com/10509903/67621764-45d82f00-f83d-11e9-8b2b-d49c96dc4f5c.png">
