### ISSUE TITLE
Better support multiple docker-compose files

### ISSUE THREAD

**Issue by ravishivt** [EugenMayer/docker-sync#697]
### Error/Feature Requestion/Docs
Feature Request

### Docker Driver
d4m

### Sync strategy
native_osx

### your docker-sync.yml

```yaml
version: "2" # Version of docker-sync, not docker-compose.
options:
  compose-file-path:
    - 'docker-compose.yml'
    - './config/docker/docker-compose-elasticsearch.yml'
    # - './config/docker/docker-compose-kibana.yml'
  compose-dev-file-path:
    - './config/docker/docker-compose-sync-backend.yml'
    - './config/docker/docker-compose-sync-frontend.yml'
```

Our project uses `compose-file-path` as a way for developers to optionally enable docker-compose configs.  In this above example, the developer has opted not to run kibana.  This works well for that purpose.

The problem is that `docker-compose` is now hampered as it cannot interact with the elasticsearch container.  Running `docker-compose ps` will not show the elasticsearch container as it's not contained in the default `docker-compose.yml`.  The workaround is to manually specify all compose files currently enabled, e.g. `docker-compose -f ./docker-compose.yml -f ./config/docker/docker-compose-elasticsearch.yml ps`.  This gets tedious and defeats the simplicity of using `compose-file-path`.

Possible solutions:
* Wrap docker-sync-stack as an indirect interface to docker-compose.  Running `docker-sync-stack ps` would be expanded to `docker-compose` with all `-f` files specified in `compose-file-path`.
* A simpler option would be offer a docker-sync-stack CLI option to print out all compose-file-path.  This approach would allow a bash alias to format the returned list and pass the options to docker-compose.  Then at least, the list is programmatically driven.
