### ISSUE TITLE
[WSL2] Not sync

### ISSUE THREAD

**Issue by chiqui3d** [EugenMayer/docker-sync#704]
### Error/Feature Requestion/Docs
It does not synchronize, only sometimes and when it does it usually takes more than a minute to discover the change.

### Note

I have followed all the steps detailed in this section https://docker-sync.readthedocs.io/en/latest/getting-started/installation.html#let-s-go

### Version
0.5.14

### Sync strategy + version
unison version 2.51.2 (ocaml 4.08.1)

### OS
Windows 10 + WSL2 with Ubuntu and Docker

### Project

Symfony + PHP + Nginx

https://github.com/chiqui3d/symfony-docker

### commands I use
```
docker-sync start
docker-compose -f docker-compose-dev.yml up -d
```

### docker-sync

```yaml
options:
  compose-file-path: './docker-compose-dev.yml'
  verbose: true

version: '2'
syncs:
  app-sync:
    src: './app'
    sync_strategy: 'unison' # for osx use 'native_osx', for windows use 'unison'
    sync_host_ip: '127.0.0.1' #host ip isn't properly inferred
    sync_args:
      - '-perms=0'
      - "-ignore='Path .idea'"          # no need to send PHPStorm config to container
      - "-ignore='Path .git'"           # ignore the main .git repo
      - "-ignore='BelowPath .git'"      # also ignore .git repos in subfolders such as in composer vendor dirs
      - "-ignore='Path bin/*'"           # ignore the main .git repo
      - "-ignore='Path var/cache/*'"    # don't share the cache
      - "-ignore='Path var/sessions/*'" # we don't need the sessions locally
      - "-ignore='Path node_modules/*'" # remove this if you need code completion
      - "-ignore='Path vendor/*'"     # we could ignore the composer vendor folder, but then you won't have code completion in your IDE
```

### Terminal Screenshot

Part 1:
![docker-sync-console-1](https://user-images.githubusercontent.com/2461400/70620754-5a6b5d80-1c18-11ea-948d-9cb889a53654.png)
Part 2:
![docker-sync-console-2](https://user-images.githubusercontent.com/2461400/70620760-60f9d500-1c18-11ea-9b45-e1fa85f0233e.png)
