### ISSUE TITLE
Two-way sync does not work on Windows

### ISSUE THREAD

**Issue by weknowsoftware** [EugenMayer/docker-sync#707]
### Error/Feature Requestion/Docs
The documentation implies you need to use
`sync_args: ['-perms=0']`
to allow two-way sync on Windows. However, with this setting, executing an entrypoint script mounted in the shared volume fails with 'permission denied', presumably because it causes the executable bit to not be set on the shell script.
Without this setting, the entrypoint script works but sync only happens from the container back to the host, making it impossible to work with a Windows IDE.
The documentation is somewhat sparse so it is hard to know exactly why sync back from container to host isn't working or how to fix it.

### Docker Driver
d4m

### Sync strategy
unison

### your docker-sync.yml
```
version: "2"
options:
    verbose: true
syncs:
    client-php-sync:
        sync_strategy: 'unison'
        sync_userid: '1000'
        #sync_args: ['-perms=0']
        sync_excludes: ['.gitignore', '.idea/*','.git/*', '*.coffee', '*.scss', '*.sass','*.log','*.sock']
        src: './api-client'
```

### OS
Windows / WSL2
