### ISSUE TITLE
Syncing with unison-dualside is syncing across src directories

### ISSUE THREAD

**Issue by adammeghji** [EugenMayer/docker-sync#71]
Hi there!

First off -- love the amazing work you're doing here.  From my research and experience, this is by far the best solution to osxfs performance problems, until Docker for Mac is able to fix for good.

I've noticed that when sync'ing with unison-dualside (not unison), my code effectively gets copied from 1 src folder to a 2nd src folder (quite destructive, in fact).

Sync config:
```
syncs:
  web-sync:
    src: '../web'
    dest: '/app'
    sync_host_port: 10872
    sync_strategy: 'unison-dualside'
    sync_userid: 'from_host'
    unison-dualside_host_ip: 'auto'
    unison-dualside_host_server_port: 6000
  boxoffice-sync:
    src: '../boxoffice'
    dest: '/app'
    sync_host_port: 10873
    sync_strategy: 'unison-dualside'
    sync_userid: 'from_host'
    unison-dualside_host_ip: 'auto'
    unison-dualside_host_server_port: 6000
 ```

Compose Config:
```
version: '2'
services:
  web:
    build: ../web
    volumes_from:
       - container:web-sync:rw
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
      - boxoffice
      - kraken
      - geoduck
      - multiverse
      - discover
      - embed
  boxoffice:
    build: ../boxoffice
    volumes_from:
       - container:boxoffice-sync:rw
    expose:
      - 4567
    ports:
      - "4567:4567"
    depends_on:
      - postgresql
volumes:
  web-sync:
    external: true
  boxoffice-sync:
    external: true
```

Any thoughts on why it's cross-sync'ing here?  Thanks a ton!
