### ISSUE TITLE
notify_terminal does not work reliably with unison

### ISSUE THREAD

**Issue by d4rky-pl** [EugenMayer/docker-sync#711]
### Error/Feature Requestion/Docs
When running docker-sync with `notify_terminal: true`, only the very first initial sync is gets a notification. Every other subsequent file update does not trigger a notification

### Docker Driver
Docker for Mac

### Sync strategy
unison

### your docker-sync.yml
```
version: "2"
options:
  verbose: true
  compose-dev-file-path: 'docker-compose.docker-sync.yml'
syncs:
  helpling-native-sync:
    src: './'
    notify_terminal: true
    sync_strategy: 'unison'
    sync_host_ip: 'auto'
    monit_enable: true
    monit_interval: 2
    monit_high_cpu_cycles: 2
    sync_excludes: ['tmp/cache', 'tmp/data', 'tmp/pids', 'tmp/sessions', 'tmp/sockets', 'node_modules', '.idea', '.vagrant', '.docker-sync', 'log',]
```
### OS
10.14.6
