### ISSUE TITLE
rsync with container-to-host synchronization

### ISSUE THREAD

**Issue by mariusbalcytis** [EugenMayer/docker-sync#721]
### Feature Request
rsync with inverse 1-way-synchronization – from container back to the host.

Currently rsync can be used only from host to container. This is suitable for most cases, for example, syncing source code. In other cases we need inverse synchronization. Two-way sync is not required in most cases:
* src from host to container
* vendor, node_modules and such directories from container to host
* logs, cache etc. directories from container to host, if needed

### Docker Driver
d4m

### Sync strategy
rsync

### your docker-sync.yml

Example that I currently use for Symfony application:
```
    app-sync:
        src: '/Users/me/Projects/app/'
        sync_userid: 1000
        sync_strategy: rsync
        sync_host_ip: 'auto'
        sync_host_port: 10801
        sync_args: '--delete --info=skip0'
        watch_excludes: ['.*/vendor', '.*/node_modules', '.*/app/cache', '.*/app/logs', '.*/.git']
    app-vendor-sync:
        src: '/Users/me/Projects/app/vendor'
        sync_userid: 1000
        sync_strategy: native_osx
        monit_enable: true
        sync_excludes: ['*/*/.git']
    app-node-modules-sync:
        src: '/Users/me/Projects/app/node_modules'
        sync_userid: 1000
        sync_strategy: native_osx
        monit_enable: true
        sync_excludes: ['*/*/.git']
```

As both `native_osx` and `unity` are not stable (at least in my machine or with my projects), rsync from container to host would be really valuable for vendor and node_modules directories.

In those cases I always run `composer install`, `npm i` and similar from inside container – for matching PHP versions, extensions etc.

### OS
OSX
