### ISSUE TITLE
How is docker-compose used in this cased?

### ISSUE THREAD

**Issue by cabello** [EugenMayer/docker-sync#726]
Hello 👋 

I have the following docker-sync:

```yaml
# http://docker-sync.io/
version: "2"
options:
  compose-file-path: 'docker/dev/docker-compose.yml'
syncs:
  app-sync:
    src: './app
    sync_strategy: 'native_osx'
    host_disk_mount_mode: 'cached' # see https://docs.docker.com/docker-for-mac/osxfs-caching/#cached
```

And I have a script that runs the following:

```
docker-sync start
docker-compose -f docker/dev/docker-compose.yml up -d
```

But I also have a `docker/staging/docker-compose.yml` that I use in different occasions but I would still like to use docker sync. Is the `compose-file-path` being used in this case? (I am not using `docker-sync-stack start`).

If it's being used, how can I achieve the desired behaviour of using the staging compose for staging environments? Do I need two docker-sync files or can I leverage some environment variable in this case?

Thank you for taking a look into this question and providing support 💜
