### ISSUE TITLE
Ubuntu 18.04 fatal error

### ISSUE THREAD

**Issue by RespectPick** [EugenMayer/docker-sync#727]
### Error/Feature Requestion/Docs
Error

I have downloaded ocaml and unison from your gide
https://docker-sync.readthedocs.io/en/latest/getting-started/installation.html#installation-linux

```
ocaml --version
The OCaml toplevel, version 4.08.1
```

```
unison -version
unison version 2.51.2 (ocaml 4.05.0)
```

```
docker-sync-stack start
       note:  You can also run docker-sync in the background with docker-sync start
          ok  Starting unison for sync k4fntr_sync
       error  Error starting sync, exit code 0
     message  Warning: No archive files were found for these roots, whose canonical names are:
	/home/yulia/PhpstormProjects/k4fntr
	//972d21911653//app_sync
This can happen either
because this is the first time you have synchronized these roots, 
or because you have upgraded Unison to a new version with a different
archive format.  

Update detection may take a while on this run if the replicas are 
large.

Unison will assume that the 'last synchronized state' of both replicas
was completely empty.  This means that any files that are different
will be reported as conflicts, and any files that exist only on one
replica will be judged as new and propagated to the other replica.
If the two replicas are identical, then no changes will be reported.

If you see this message repeatedly, it may be because one of your machines
is getting its address from DHCP, which is causing its host name to change
between synchronizations.  See the documentation for the UNISONLOCALHOSTNAME
environment variable for advice on how to correct this.

Donations to the Unison project are gratefully accepted: 
http://www.cis.upenn.edu/~bcpierce/unison

                                                    
     message  Unison 2.51.2 (ocaml 4.05.0): Contacting server...
Connected [//972d21911653//app_sync -> //Yulia//home/yulia/PhpstormProjects/k4fntr]
Looking for changes
  Waiting for changes from server
Fatal error: Fatal error during unmarshaling (input_value: ill-formed message),
possibly because client and server have been compiled with differentversions of the OCaml compiler.
     success  Unison server started
       error  Error starting sync, exit code 0
     message  Warning: No archive files were found for these roots, whose canonical names are:
	/home/yulia/PhpstormProjects/k4fntr
	//972d21911653//app_sync
This can happen either
because this is the first time you have synchronized these roots, 
or because you have upgraded Unison to a new version with a different
archive format.  

Update detection may take a while on this run if the replicas are 
large.

Unison will assume that the 'last synchronized state' of both replicas
was completely empty.  This means that any files that are different
will be reported as conflicts, and any files that exist only on one
replica will be judged as new and propagated to the other replica.
If the two replicas are identical, then no changes will be reported.

If you see this message repeatedly, it may be because one of your machines
is getting its address from DHCP, which is causing its host name to change
between synchronizations.  See the documentation for the UNISONLOCALHOSTNAME
environment variable for advice on how to correct this.

Donations to the Unison project are gratefully accepted: 
http://www.cis.upenn.edu/~bcpierce/unison

                                                                        
     message  Unison 2.51.2 (ocaml 4.05.0): Contacting server...
Connected [//972d21911653//app_sync -> //Yulia//home/yulia/PhpstormProjects/k4fntr]
Looking for changes
  Waiting for changes from server
Fatal error: Fatal error during unmarshaling (input_value: ill-formed message),
possibly because client and server have been compiled with differentversions of the OCaml compiler.
          ok  Found explicit docker-compose-dev.yml and using it from docker-compose.dev.yml
          ok  starting compose
Unison 2.51.2 (ocaml 4.05.0): Contacting server...
Connected [//972d21911653//app_sync -> //Yulia//home/yulia/PhpstormProjects/k4fntr]
Looking for changes
  Waiting for changes from server
Fatal error: Fatal error during unmarshaling (input_value: ill-formed message),
possibly because client and server have been compiled with differentversions of the OCaml compiler.

```

### Docker Driver
overlay2

### Sync strategy
unison

### your docker-sync.yml

```
version: "2"
options:
  # default: docker-compose.yml if you like, you can set a custom location (path) of your compose file like ~/app/compose.yml
  # HINT: you can also use this as an array to define several compose files to include. Order is important!
  compose-file-path: 'docker-compose.yml'

  # optional, default: docker-compose-dev.yml if you like, you can set a custom location (path) of your compose file. Do not set it, if you do not want to use it at all

  # if its there, it gets used, if you name it explicitly, it HAS to exist
  # HINT: you can also use this as an array to define several compose files to include. Order is important!
  compose-dev-file-path: 'docker-compose.dev.yml'

syncs:
  k4fntr_sync:
    src: './'
    sync_strategy: 'unison'
    watch_excludes: ['.*/.git', '.*/node_modules', '.*/bower_components', '.*/sass-cache', '.*/.sass-cache', '.*/.sass-cache', '.coffee', '.scss', '.sass', '.gitignore']
    sync_excludes: ['Gemfile.lock', 'Gemfile', 'config.rb', '.sass-cache', 'sass', 'sass-cache', 'composer.json' , 'bower.json', 'package.json', 'Gruntfile*', 'bower_components', 'node_modules', '.gitignore', '.git', '*.coffee', '*.scss', '*.sass']

```

### OS
Ubuntu 18.04
