### ISSUE TITLE
Files are not synced upon saving, but upon inital start of docker-sync changes are applied

### ISSUE THREAD

**Issue by Izopi4a** [EugenMayer/docker-sync#749]
hi, and thx for the tool

WSL2, ubuntu 20.04 on windows. 

I followed the installation instructions here: https://docker-sync.readthedocs.io/en/latest/getting-started/installation.html#windows

What I do is I run `docker-sync-stack start` from the WSL itself and here is the output

```
izopi4a@DESKTOP-NTA2TRH:/mnt/c/goProjects/src/github.com/whatever/base2/docker$ docker-sync-stack start
       note:  You can also run docker-sync in the background with docker-sync start
          ok  Starting unison for sync app-unison-sync
          ok  app-unison-sync container not running
          ok  starting app-unison-sync container
     command  docker start app-unison-sync && docker exec app-unison-sync supervisorctl restart unison
          ok  starting initial sync of app-unison-sync
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' app-unison-sync
     command  unison -testserver /app_sync "socket://127.0.0.1:32782"
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' app-unison-sync
     command  unison -ignore='Name .gitignore' -ignore='Name .idea/*' -ignore='Name .git/*' -ignore='Name var/cache/*' -ignore='Name var/log/*' -ignore='Name var/sessions/*' '/mnt/c/goProjects/src/github.com/whatever/base2' -auto -batch -prefer '/mnt/c/goProjects/src/github.com/whatever/base2' -copyonconflict -perms=0 socket://127.0.0.1:32782
          ok  Synced /mnt/c/goProjects/src/github.com/whatever/base2
changed  ---->            templates/security/login.html.twig

     success  Unison server started
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' app-unison-sync
     command  unison -ignore='Name .gitignore' -ignore='Name .idea/*' -ignore='Name .git/*' -ignore='Name var/cache/*' -ignore='Name var/log/*' -ignore='Name var/sessions/*' '/mnt/c/goProjects/src/github.com/whatever/base2' -auto -batch -prefer '/mnt/c/goProjects/src/github.com/whatever/base2' -copyonconflict -perms=0 socket://127.0.0.1:32782
          ok  Synced /mnt/c/goProjects/src/github.com/whatever/base2

     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' app-unison-sync
     command  unison -ignore='Name .gitignore' -ignore='Name .idea/*' -ignore='Name .git/*' -ignore='Name var/cache/*' -ignore='Name var/log/*' -ignore='Name var/sessions/*' '/mnt/c/goProjects/src/github.com/whatever/base2' -auto -batch -prefer '/mnt/c/goProjects/src/github.com/whatever/base2' -copyonconflict -perms=0 socket://127.0.0.1:32782 -repeat watch
          ok  Found explicit docker-compose-dev.yml and using it from ./docker-compose.yml
          ok  starting compose
Unison 2.51.2 (ocaml 4.08.1): Contacting server...
Connected [//5e5e0691011f//app_sync -> //DESKTOP-NTA2TRH//mnt/c/goProjects/src/github.com/whatever/base2]
```

after my container is booted, saving a file does not apply changes inside the container, `cat` the file from WSL shows the changes

`docker-compose-dev.yml`

```
version: '3'
services:
  base2:
    container_name: base2
    networks:
      - internal
      - web
    build:
      context: .
      args:
        USERID: ${USRID}
        ENV: ${APPLICATION_ENV}
    image: eu.gcr.io/frontend-0/base2:v1.0.0
    environment:
      RACK_ENV: ${APPLICATION_ENV}
      MESSAGE_QUEUE_NAME: ${MESSAGE_QUEUE_NAME}
    volumes:
#    - "./../:/var/www/html"
    - app-unison-sync:/var/www/html:nocopy
    - "./etc/vhost-dev.conf:/etc/nginx/sites-available/default"
    extra_hosts:
    - "whatver:x.x.x.x"
    labels:
      - "traefik.enable=true"
      - "more traefik stuff"
networks:
  web:
    external: true
  internal:
    external: false
volumes:
  app-unison-sync:
    external: true
```

`docker-sync.yml`

```
version: "2"
options:
  compose-file-path: './docker-compose.yml'
  compose-dev-file-path: './docker-compose.yml'
  verbose: true
syncs:
  app-unison-sync: # tip: add -sync and you keep consistent names als a convention
    sync_args: ['-perms=0'] #required for two way sync ie generators, etc
    sync_strategy: 'unison'
    sync_excludes: ['.gitignore', '.idea/*','.git/*','var/cache/*','var/log/*','var/sessions/*']
    src: '../.'
    sync_userid: 33

```

i saw this issue here https://github.com/EugenMayer/docker-sync/issues/556

but when i do `gem list dwm` inside my WSL ubuntu 20.04 i don't see anything

```
gem list dwm                                                                                                                                                                                                                                                                                                                                           *** LOCAL GEMS ***                                                                                                                                                                                                                                                                                                                                                                                                                                     
```

i tried gem uninstall docker-sync && gem install docker-sync and docker-sync clean, but the same result.

```
$ unison -version

unison version 2.51.2 (ocaml 4.08.1)  
```

Perhaps I am not supposed to run it from the WSL ? or the /mnt/c/ directory is wrongly used?

p.s. I didn't do point 12 from the tutorial here https://docker-sync.readthedocs.io/en/latest/getting-started/installation.html#windows

winver: 20H2 OS build 19042.450
