### ISSUE TITLE
Wrong src path when using project_root: config_path and -c option

### ISSUE THREAD

**Issue by laurenz-glueck** [EugenMayer/docker-sync#756]
### Error
I just discovered a behavior of src directory path building which seems to be an issue to me.

If you have set the `project_root` option to `'config_path'` and then use the `docker-sync start` command with the `-c` option in a folder where you pass the docker-sync.yml from a sub-folder. In this case docker-sync will use the current directory and not the directory where the docker-sync.yml is located.

**A simple example:**

You have this folder structure:
- project_folder
- - www
- - docker-local

If you are now in your `docker-local` folder (where the docker-sync.yml is located) and run `docker-sync start` it will start syncing the `www` folder because the `src` in the docker-sync.yml is set to `'./../www'`

If you now go to the `project_folder` folder and run `docker-sync start -c ./docker-local/docker-sync.yml` I would expect it would also sync the `www` folder as the `project_root` is set to `'config_path'` and the config is placed in the `docker-local` sub-folder. But instead it throws an error because it is trying to find a www folder above the project_folder.

So I think the issue is, that the `project_root` option set to `'config_path'` is not taking the `-c` option into account.

### your docker-sync.yml
```
version: "2"
syncs:
  files-sync-dev:
    notify_terminal: true
    src: './../www'
    project_root: 'config_path'
    sync_excludes: ['.git', '.idea', 'node_modules', 'k8s', 'docker-local']
    sync_userid: '0'
    sync_groupid: '0'
    verbose: true
```

### OS
macOS

**Comment by laurenz-glueck** [comment]
Okay - nerver minde 🙈 
I just notice that the `project_root` setting needs to placed under `config` and not in the `sync`. Now it works fine 😅  

If anybody else is wondering - you need to do it like this:

```
version: "2"
options:
  project_root: 'config_path'

syncs:
  files-sync-dev:
    notify_terminal: true
    src: './..'
    sync_excludes: ['.git', '.idea', 'node_modules', 'k8s', 'docker-local']
    sync_userid: '0'
    sync_groupid: '0'
```
