### ISSUE TITLE
Hot reloading sync not working

### ISSUE THREAD

**Issue by hugoalexmartins** [EugenMayer/docker-sync#760]
Hi this the first time I've been using this package. And I'm using it because for some reason docker + symfony on my Mac is pretty much slow. 
After setup all to have the project running on my local machine, I've been trying to use docker-sync to have project running faster. And the page reload seems faster with docker-sync, although when I update code on my IDE the updates are not reflected and not updated. I tried to get into the docker-sync container a saw that code is not being updated, so it seems hot-reload of something like that is not working.
Can you please help me ?

### Sync strategy
native_osx

### your docker-sync.yml
```
version: '2'

options:
  compose-file-path: 'docker-compose-dev.yml'
  verbose: true

syncs:
  app-sync:
    src: './'
    sync_strategy: native_osx
    sync_excludes:
      - '.git'
      - '.docker'
```

### OS
macOS Catalina 10.15.6
