### ISSUE TITLE
Can't see Unison logs

### ISSUE THREAD

**Issue by astyagun** [EugenMayer/docker-sync#769]
### Error

`docker-sync logs` command contains an error (among other messages) and doesn't show actual Unison logs:

```
[2021-05-19 16:19:55 +0300] Sync Log:  tail: can't open '/tmp/unison.log': No such file or directory
```

It seems, that Unison default file location has changed from `/tmp/unison.log` to `/home/dockersync/unison.log`, but `docker-sync` is not aware of that.

Adding `- "-logfile=/tmp/unison.log"` under `sync_args:` in `docker-sync.yml` fixes the problem and can be used as a temporary workaround.

`docker-sync` gem version is 0.6.0, Unison Docker image version is `eugenmayer/unison:2.51.3-4.12.0-AMD64`.

### Docker Driver

d4m

### Sync strategy

Default for Mac, native_osx, I think

### your docker-sync.yml

```yaml
---
version: '2'
syncs:
  projectname_code:
    src: .
    sync_userid: 1000
    sync_groupid: 1000
    sync_args:
      - "-ignore='Name .*.swo'"
      - "-ignore='Name .*.swp'"
      - "-ignore='Name .git'"           # Ignore .git repos in subfolders such as in composer vendor dirs
      - "-ignore='Name .gitignore'"
      - "-ignore='Path .docker-sync'"
      - "-ignore='Path .git'"           # Ignore the main .git repo
      - "-ignore='Path log/*.log'"
      - "-ignore='Path node_modules'"
      - "-ignore='Path tmp/cache'"
      - "-ignore='Path tmp/miniprofiler'"
```

### OS

macOS Catalina 10.15.7
