### ISSUE TITLE
Ignored files and paths are still synced

### ISSUE THREAD

**Issue by ChristianVermeulen** [EugenMayer/docker-sync#771]
### Error/Feature Requestion/Docs
I have configured some paths (like node_modules) to be ignored, but they are still synced.

Sync log
<img width="532" alt="Screenshot 2021-06-24 at 13 37 07" src="https://user-images.githubusercontent.com/1062751/123256668-8647ee80-d4f1-11eb-9f0d-f47e442f20ed.png">

Container filesystem
<img width="513" alt="Screenshot 2021-06-24 at 13 40 03" src="https://user-images.githubusercontent.com/1062751/123256823-b1cad900-d4f1-11eb-97f9-df542b883729.png">

### Docker Driver
<img width="872" alt="Screenshot 2021-06-24 at 13 40 48" src="https://user-images.githubusercontent.com/1062751/123256913-cad38a00-d4f1-11eb-897d-79aab382d643.png">

### Sync strategy
native_osx + unison

### your docker-sync.yml
```
version: "2"
syncs:
  aident-app:
    src: '.'
    strategy: 'osx_native'
    sync-args:
      - "-ignore='Path .idea'"          # no need to send PHPStorm config to container
      - "-ignore='Path .git'"           # ignore the main .git repo
      - "-ignore='BelowPath .git'"      # also ignore .git repos in subfolders such as in composer vendor dirs
      - "-ignore='Path var/cache/*'"    # don't share the cache
      - "-ignore='Path var/log/*'"      # don't share the log
      - "-ignore='Path node_modules/*'" # remove this if you need code completion
```

### OS
OSX 11.4
