### ISSUE TITLE
Yarn builds do not trigger file change

### ISSUE THREAD

**Issue by ChristianVermeulen** [EugenMayer/docker-sync#772]
### Error/Feature Requestion/Docs
When building css/js with yarn, it does not trigger a file change and therefore the new files are not synced to my containers. Once I open up a built file, add e.g. a comment, it is synced due to the file change.

### Docker Driver
<img width="872" alt="Screenshot 2021-06-24 at 13 50 43" src="https://user-images.githubusercontent.com/1062751/123258008-2ce0bf00-d4f3-11eb-8750-9c1f6f44289c.png">

### Sync strategy
native_osx + unison

### your docker-sync.yml
```yml
version: "2"
syncs:
  aident-app:
    src: '.'
    strategy: 'osx_native'
    sync-args:
      - "-ignore='Path .idea'"          # no need to send PHPStorm config to container
      - "-ignore='Path .git'"           # ignore the main .git repo
      - "-ignore='BelowPath .git'"      # also ignore .git repos in subfolders such as in composer vendor dirs
      - "-ignore='Path var/cache/*'"    # don't share the cache
      - "-ignore='Path var/log/*'"      # don't share the log
      - "-ignore='Path node_modules/*'" # remove this if you need code completion
```

### OS
OSX 11.2
