### ISSUE TITLE
undefined method `unbundled_system' for Bundler:Module

### ISSUE THREAD

**Issue by mPanasiewicz** [EugenMayer/docker-sync#773]
Hi,

I have an issue with multiple projects with version docker-sync *0.6.0*
### Error/Feature Requestion/Docs
`undefined method `unbundled_system' for Bundler:Module`

### Docker Driver
d4m(downloaded from official docker page)

### Sync strategy
native_osx(default, I've changed the strategy)

### your docker-sync.yml
```
version: "2"
syncs:
  mark-fs-sync:
    src: '~/reevoo/mark/'
    sync_excludes: 
      - 'ignored_folder'
      - '.git'
      - 'node_modules'
      - '.gitignore'
      - '.git'
```
### OS
macOS Big Sur version 11.4 (OSX Version/Linux)

The docker-sync wont's start but raises above error. I've tried to google it, but there is no similar issue about that. Could someone explan me what is going on??
