### ISSUE TITLE
docker-sync synced folder is empty inside the container

### ISSUE THREAD

**Issue by plaviano** [EugenMayer/docker-sync#774]
### Error/Feature Requestion/Docs
The container folder sync with docker-sync is empty. I listed `app_sync` folder inside `magento-unison-sync` and it is empty. While starting the php-apache-dev container, the mounted folder is empty aswell so apache complaints about it. In the end, the syncing does not work.

### Docker Driver
Docker Desktop 3.4.0
Docker Engine 20.10.7
Compose 1.29.2

### Sync strategy
unison

### your docker-compose.yml

```
version: '3'
services:
    web:
        image: webdevops/php-apache-dev:7.3-alpine
        container_name: web
        restart: "no"
        environment:
          - WEB_DOCUMENT_ROOT=/app/pub
          - PHP_DATE_TIMEZONE=EST
          - PHP_DISPLAY_ERRORS=1
          - PHP_MEMORY_LIMIT=2048M
          - PHP_MAX_EXECUTION_TIME=300
          - PHP_POST_MAX_SIZE=500M
          - PHP_UPLOAD_MAX_FILESIZE=1024M
        volumes:
          - magento-unison-sync:/app:nocopy,delegated
...
volumes:
    magento-unison-sync:
        external: true
```

### your docker-sync.yml

```
version: "2"
options:
    compose-file-path: 'docker-compose.yml'
    verbose: true
    cli_mode: 'auto'
    max_attempt: 5

syncs:
    magento-unison-sync: # tip: add -sync and you keep consistent names als a convention
        notify_terminal: true
        src: '../magento'
        sync_strategy: 'unison'
        sync_excludes: [
            '.gitignore',
            '.idea/*',
            'tmp/cache/**/*',
            '.git/**/*',
            '*.coffee',
            '*.scss',
            '*.sass',
            '*.log',
            'Path .git',
            'Name .gitignore',
            'BelowPath node_modules',
            'BelowPath bower_components',
            'BelowPath sass-cache',
            'BelowPath .sass-cache',
            'Path var/cache',
            'Path var/page_cache',
            'Path var/session',
            'BelowPath .DS_Store'
        ]
```

### OS
Ubuntu 20.04.2 LTS (WSL)
