### ISSUE TITLE
Folder not syncing / empty

### ISSUE THREAD

**Issue by julianlaibach** [EugenMayer/docker-sync#789]
My docker-container "project-http" does not copy from the "project-http-vol" Volume, the host_sync folder contains the apps code but if i access the Volume from my docker-container "project-http" is empty, the app_sync folder is empty and i wonder which folder is used to be synced. My docker-compose.yml is as follows:

```
version: '3'
services:
    http:
        build:
            context: project-http
        image: project-http
        container_name: project-http
        environment:
            COMPOSER_MEMORY_LIMIT: -1
        restart: on-failure
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - project-http-vol:/var/www/html
        depends_on:
            - database
            - redis
    database:
        image: mysql:5.7.29
        container_name: project-database
        restart: on-failure
        volumes:
            - "${DATABASE_VOLUME}:/var/lib/mysql"
        env_file: .env
    redis:
        image: redis:6.0.10
        container_name: project-redis
        command: redis-server --appendonly yes
        restart: on-failure
        volumes:
            - "${REDIS_VOLUME}:/data"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: project-phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: project-database
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "${PHPMYADMIN_PORT}:80"
        restart: on-failure
        volumes:
            - "${PHPMYADMIN_CONFIG}:/etc/phpmyadmin/config.user.inc.php"
volumes:
    project-http-vol:
        external: true
```

Do you may now what i'm doing wrong? My Docker is also in the app Folder and the docker-sync.yml is in the Application root

### Docker Driver
d4m

### Sync strategy
native_osx

### my docker-sync.yml
```
version: 2
syncs:
  project-http-vol:
    notify_terminal: false
    sync_strategy: 'native_osx'
    unison_image: eugenmayer/unison:2.51.3-4.12.0-ARM64
    src: './'

    sync_excludes: [
      '.docker',
      '.docker-sync',
      '.git',
      '.DS_Store',
      'docker',
    ]
```

### OS
Version: 12.00 Monterey
