### ISSUE TITLE
Is there a command to stop all synced volumes without knowing them?

### ISSUE THREAD

**Issue by michaelkeiluweit** [EugenMayer/docker-sync#790]
### Error/Feature Requestion/Docs
Feature Requestion / Docs

### Docker Driver
Docker Desktop 4.2.0 (Docker version 20.10.10, build b485636)

### Sync strategy
unison

### your docker-sync.yml
```yml
version: "2"
syncs:
  db-sync:
    notify_terminal: true
    src: './data/mysql'
  php-www-sync:
    notify_terminal: true
    src: './data/www'
```
Please note that "php-www-sync" and "db-sync" are getting replaced by a `sed` command, e.g. `sed db-sync-"${projectName}"`:

${projectName} = example
```yml
version: "2"
syncs:
  db-sync-example:
    notify_terminal: true
    src: './data/mysql'
  php-www-sync-example:
    notify_terminal: true
    src: './data/www'
```
docker-compose-dev.yml
```yml
version: '2'
services:
  db:
    volumes:
      - db-sync-example:/var/lib/mysql:nocopy
  php:
    volumes:
      - php-www-sync-example:/var/www/html/:nocopy        
```

### OS
OSX Version 12.0.1

## Question

Hello there

Since the docker projects are slow on my system, I’ve installed docker-sync as described in the docs: https://docker-sync.readthedocs.io/en/latest/getting-started/installation.html#advanced-optional :: if you use unison.

It works fine and perfect as far as I can see, but there’s a question I can’t find an answer for. But let me explain my setup first:

The company I work at develops a PHP application which is using composer - the package distribution software for PHP. During each install procedure of the company’s software, composer has to download many packages. After that some configuration is needed to have the application running.
Since Docker is slow on Mac, I needed to speed up things, since I have sometimes to install multiple instances per day and just one needs about half an hour to be ready, whereas in the past on Linux it was about a couple of minutes.

So I’ve found docker-sync, tested it and it works pretty well. I have a pre-configured docker-sync.yml which I copy into a new instance and execute docker-sync. But as you might expect it now already, I stumbled about the fact that I re-use the volume each time now. I don’t have fresh installed instance of the application, but the volumes data of the first instance I’ve installed with docker-sync.  This means I have to stop docker-sync, get rid of the volumes and be ready to go for a fresh installing. But this means also I have to track which directory holds the latest docker-sync so I can switch the context, stop the sync, clear the volumes and switch back. And besides the effort I will lose the data of each projects.

To create a new instance, I have a bash script wich stops all running container forcefully and creates new ones. By this, I can stop the current project I’m working on, switch to a new instance, do things, and then switch back to all the projects I have installed. The command to call this script works from every context. So I added a few lines to this script which are adapting the volume names to unique ones. Now I have for each project unique volumes and those aren’t get overridden and I don’t have to track which project holds the latest docker-sync.
Except I still may have to track it, since there isn’t an option to tell docker-sync: “Please stop syncing all volumes you have registered.” Or when I have to clean up the system: “Please get rid of all desynced volumes.”

That’s the point of my question. Pretending we have a directory which holds a docker-sync.yml which created volumes. And I delete this directory by accident and I don’t know how I named the volumes. How can I tell docker-sync to delete those orphaned volumes, like docker prune container / image / network / system would do?  Is it possible to let docker-sync stop all syncing without having a docker-sync.yml in the current directory? Can I get a list of all "living" syncs without the need of a docker-sync file?

Best,
Michael
