### ISSUE TITLE
error  undefined method `unbundled_system' for Bundler:Module

### ISSUE THREAD

**Issue by khesualdo-rewind** [EugenMayer/docker-sync#794]
```
daemons 1.4.1
docker-compose 1.1.12
dotenv 2.7.6
gem_update_checker 0.2.0
os 1.1.4
terminal-notifier 2.0.0
thor 1.2.1

pry 0.12.2
```
```
Bundler version 1.17.3
```
```
ruby 2.6.6p146 (2020-03-31 revision 67876) [-darwin21]
```

### Error
```
error  undefined method `unbundled_system' for Bundler:Module
```
### Docker Driver
Storage Driver: `overlay2`

### Sync strategy
`sync_strategy: 'native_osx'`

### your docker-sync.yml

```
version: '2'
options:
  verbose: true
syncs:
  # IMPORTANT: ensure this name is unique and does not match your other application container name
  backhub-sync:
    src: ../../backhub
    sync_host_ip: 'localhost'
    sync_host_port: 10872
    sync_userid: 1000
    sync_excludes:
      - '.github'
      - 'build'

sync_strategy: 'native_osx'
```

### OS
macOS Monterey
Version 12.1
Chip Apple M1 Pro
