### ISSUE TITLE
External network access and permission problems

### ISSUE THREAD

**Issue by yyggg** [EugenMayer/docker-sync#805]
# System version: osx 12.2.1
## My MySQL server is external

docker-sync.yml 
```
version: "2"
options:
    verbose: true
syncs:
  mac-sync:
    src: "./mall2/"
    sync_excludes: ['.git','.idea']	
```
docker run -v mac-sync:/var/www/mall2 -p 80:80 -p 443:443 -p 21:21 -p 22:22 -itd contens

errors:

- `SQLSTATE[HY000] [2002] Connection refused ...`
- `could not be opened in append mode: failed to open stream: Permission denied`
