### ISSUE TITLE
docker-sync start success, but I can't use docker-sync logs

### ISSUE THREAD

**Issue by JJ-H** [EugenMayer/docker-sync#818]
### Error/Feature Requestion/Docs
- when I run `docker-sync start`，outputs is ok
<img width="416" alt="image" src="https://user-images.githubusercontent.com/54270760/189818443-3d0161e2-f8c5-4389-b93f-16abb735aac3.png">

- but when I run `docker-sync logs`, I get this
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/54270760/189820037-b3eb7aa6-18fa-4d62-b07b-c3d4e7eb63e6.png">

It doesn't seem to be really running in the background, only when I run `docker-sync sync`, it sync success，I have tried all the ways，like：`docker-sync clean && rm .docker-sync.` restart machine，reinstall gem, but all not works, how can I do, plz

by the way: It works well before I update `docker-sync`  to  `1.0.1`, but I try to reset it to `0.7.2`, nothing be changed😂

### Docker Driver
? (d4m or docker-machine+vbox/fusion)

### Sync strategy
unison

### your docker-sync.yml
```yaml
version: "2"
syncs:
  dev-m1_gitee:
    src: "/home/git/xxx"
    sync_strategy: unison
    unison_image: eugenmayer/unison:2.51.3-4.12.0-ARM64
    sync_excludes:
      - node_modules
      - Gemfile
      - Gemfile.lock

```
### OS
OSX 11.6.2
