### ISSUE TITLE
docker-sync start failed - /tmp/supervisor.sock no such file

### ISSUE THREAD

**Issue by digidycom** [EugenMayer/docker-sync#833]
# Problem
When I start `docker-sync` for the first time after I run docker, I got following error:

```
docker-sync start
          ok  Starting native_osx for sync my-project-sync
          ok  my-project-sync container not running
          ok  starting my-project-sync container
     command  docker start my-project-sync && docker exec my-project-sync supervisorctl restart unison
my-project-sync
unix:///tmp/supervisor.sock no such file
/Users/martin/.local/share/gem/ruby/2.6.0/gems/docker-sync-1.0.5/lib/docker-sync/sync_strategy/native_osx.rb:105:in `start_container': Start failed (RuntimeError)
	from /Users/martin/.local/share/gem/ruby/2.6.0/gems/docker-sync-1.0.5/lib/docker-sync/sync_process.rb:105:in `start_container'
	from /Users/martin/.local/share/gem/ruby/2.6.0/gems/docker-sync-1.0.5/lib/docker-sync/sync_manager.rb:103:in `block in start_container'
	from /Users/martin/.local/share/gem/ruby/2.6.0/gems/docker-sync-1.0.5/lib/docker-sync/sync_manager.rb:102:in `each'
	from /Users/martin/.local/share/gem/ruby/2.6.0/gems/docker-sync-1.0.5/lib/docker-sync/sync_manager.rb:102:in `start_container'
	from /Users/martin/.local/share/gem/ruby/2.6.0/gems/docker-sync-1.0.5/tasks/sync/sync.thor:181:in `daemonize'
	from /Users/martin/.local/share/gem/ruby/2.6.0/gems/docker-sync-1.0.5/tasks/sync/sync.thor:47:in `start'
	from /Users/martin/.local/share/gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/martin/.local/share/gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/martin/.local/share/gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/martin/.local/share/gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/martin/.local/share/gem/ruby/2.6.0/gems/docker-sync-1.0.5/bin/docker-sync:14:in `<top (required)>'
	from /usr/local/bin/docker-sync:23:in `load'
	from /usr/local/bin/docker-sync:23:in `<main>'
```

# Problem explained
In `https://github.com/EugenMayer/docker-sync/blob/main/lib/docker-sync/sync_strategy/native_osx.rb` file is executed command `docker start product-catalog-sync && docker exec product-catalog-sync supervisorctl restart unison`. Because the first command in not fully completed inside docker, supervisor service is not running and execution of second command `docker exec product-catalog-sync supervisorctl restart unison` fails, afterwards docker-sync command fails. When I execute this commands separately via terminal with the same conditions (docker is freshly started and nothing is running inside docker), everything works ok.

# Possible solution
Put some delay in between this two commands or create a routine to detect, that supervisor service is fully started.

### Sync strategy
native_osx

### your docker-sync.yml
```yaml
version: "2"
options:
    verbose: true
    notify_terminal: false
syncs:
    my-project-sync:
        src: "../my-project"
        sync_args: ["-perms=0"]
        sync_excludes: [".ci", ".git", ".idea", "var/cache/dev", "var/cache/prod"]
        sync_userid: "$UID"
        sync_groupid: "$GID"
        monit_interval: 10
        monit_high_cpu_cycles: 6
```
### OS
Monterey 12.6.3, docker-sync 1.0.5, docker 4.16.2, docker engine 20.10.22, docker file sharing implementation: gRPC FUSE
