### ISSUE TITLE
/docker-sync-1.0.5/tasks/sync/sync.thor:69:in `kill': Operation not permitted (Errno::EPERM)

### ISSUE THREAD

**Issue by oliveratgithub** [EugenMayer/docker-sync#834]
### Error
When using `docker-sync` commands, I get the following error:

**`docker-sync restart`**

```bash
          ok  Stopping sync container vendor-sync
          ok  Stopping sync container app-sync
          ok  Stopping sync container db-sync
/Users/myself/.gem/ruby/2.6.0/gems/docker-sync-1.0.5/tasks/sync/sync.thor:69:in `kill': Operation not permitted (Errno::EPERM)
	from /Users/myself/.gem/ruby/2.6.0/gems/docker-sync-1.0.5/tasks/sync/sync.thor:69:in `stop'
	from /Users/myself/.gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/myself/.gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/myself/.gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/myself/.gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /Users/myself/.gem/ruby/2.6.0/gems/docker-sync-1.0.5/tasks/sync/sync.thor:89:in `restart'
	from /Users/myself/.gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/myself/.gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/myself/.gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/myself/.gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/myself/.gem/ruby/2.6.0/gems/docker-sync-1.0.5/bin/docker-sync:14:in `<top (required)>'
	from /Users/myself/.gem/ruby/2.6.0/bin/docker-sync:23:in `load'
	from /Users/myself/.gem/ruby/2.6.0/bin/docker-sync:23:in `<main>'
```

**`docker-sync stop`**

```bash
/Users/myself/.gem/ruby/2.6.0/gems/docker-sync-1.0.5/tasks/sync/sync.thor:114:in `kill': Operation not permitted (Errno::EPERM)
	from /Users/myself/.gem/ruby/2.6.0/gems/docker-sync-1.0.5/tasks/sync/sync.thor:114:in `block in clean'
	from /Users/myself/.gem/ruby/2.6.0/gems/docker-sync-1.0.5/tasks/sync/sync.thor:112:in `each'
	from /Users/myself/.gem/ruby/2.6.0/gems/docker-sync-1.0.5/tasks/sync/sync.thor:112:in `clean'
	from /Users/myself/.gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/myself/.gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/myself/.gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/myself/.gem/ruby/2.6.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/myself/.gem/ruby/2.6.0/gems/docker-sync-1.0.5/bin/docker-sync:14:in `<top (required)>'
	from /Users/myself/.gem/ruby/2.6.0/bin/docker-sync:23:in `load'
	from /Users/myself/.gem/ruby/2.6.0/bin/docker-sync:23:in `<main>'
```

**`docker-sync start`**

```bash
         ok:  docker-sync already started for this configuration
```

### Docker Driver
* Docker Desktop for Mac
  * Version: 4.16.2 (95914)
  * Engine: 20.10.22
* File synchronisation: `gRPC FUSE`

### Sync strategy
`unison` & `native_osx`

### your docker-sync.yml

```
version: "2"
options:
    compose-file-path: './docker-compose.yml'
    verbose: true
syncs:
    vendor-sync:
        src: './vendor'
        sync_strategy: 'unison'
        sync_excludes: [ ]
    app-sync:
        src: './app'
        sync_strategy: 'native_osx'
        sync_excludes: [ ]
    db-sync:
        src: './mariadb'
        sync_strategy: 'unison'
        sync_excludes: [ ]

```

### OS
* macOS Ventura 13.2.1 (22D68)
* MacBook Air (M2, 2022)
